### ISSUE TITLE
Rails 4.2 Tables don´t return synonyms

### ISSUE THREAD

**Issue by rui-ribeiro** [rsim/oracle-enhanced#1018]
Hi!

Thanks for your work! Great job!

I have a problem. When I call .tables the gem don´t return the synonyms.

A more deep explanation: 

I´m using DatabaseCleaner, and when I call clear the gem (DatabaseCleaner) calls the connection.tables and only returns the tables and views not the synonyms. That cause do some tables don´t get cleaned. 

How can I fix this?

Thanks!

**Comment by yahonda** [comment]
Hi, Please give it a try upgrade Oracle enhanced adapter 1.6.5 or newer, 1.6.7 the latest for Rails 4.2 and create another connection using `schema:` option and set the schema name who owns tables pointed by schemas.

https://github.com/rsim/oracle-enhanced/blob/master/README.md#switching-to-another-schema

synonyms are not always pointing tables, synonym can point any database objects, then prefer not to return synonyms for tables (data_sources in Rails 5).

**Comment by rui-ribeiro** [comment]
Hi, I tried your suggestion. I didn't work. 

The schema is correct and the user have access. 

I managed to make a query that returns what i want.

```sql SELECT DECODE(table_name, UPPER(table_name), LOWER(table_name), table_name) 
FROM all_tables 
WHERE owner = SYS_CONTEXT('userenv', 'current_schema') AND secondary = 'N'
union all
select DECODE(synonym_name, UPPER(synonym_name), LOWER(synonym_name), synonym_name)  as table_name
from all_synonyms
where owner = SYS_CONTEXT('userenv', 'current_schema')
```

The problem is, as you are saying, synonyms can point to any database objects.

**Comment by yahonda** [comment]
Thanks for the update.  Glad you have found a way to implement it. So far this requirement is relatively specific for your use case then I'd suggest to implement your own `tables` method and use your own version.

https://github.com/rsim/oracle-enhanced/blob/release16/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb#L862-L866
