### ISSUE TITLE
Failed migration does not cleanup after itself

### ISSUE THREAD

**Issue by chadmetcalf** [rsim/oracle-enhanced#1021]
If a migration fails after table creation, the table does not get dropped. Once I fix the blocker, the migration will not run because of the left over table from the failed migration.

Steps to repro:

1. Run a failing migration

```ruby
# db/migrate/somemigration.rb
def change
  create_table :foo do |t|
    t.timestamps null: false
  end

  raise 'not this time!'
end
```

`rake db:migrate` => `StandardError: An error has occurred, all later migrations canceled`

2. Run a correct migration
remove the raise
`rake db:migrate` => `ORA-00955: name is already used by an existing object: CREATE TABLE "FOO" `

**Comment by yahonda** [comment]
Since create table and create sequence sql statements executed by `create_table` are DDL which performs implicit commit then cannot rollback.  then you need to write another migration to execute `drop_table`

https://docs.oracle.com/database/121/SQLRF/statements_4011.htm#SQLRF01110

**Comment by chadmetcalf** [comment]
@yahonda Thanks for your fast response and for your dedication to the maintenance of this library! 

I think that there was a misunderstanding of the issue. This is a valid issue and that this ticket should be re-opened. I'm happy to do the work and submit a PR with some guidance.

Other ActiveRecord RDB adapters gracefully handle failed create table migrations and return the database to the pre-migration condition that matches the schema. The `oracle-enhanced` ActiveRecord adapter fails mid-migration and forces manual database manipulation to return the database/schema to a matching state. Leaving the database and the rails schema in a conflicting state a clear bug in an ActiveRecord adapter.

I'll try to spend a little time seeing how SQLite, PostgreSQL, and MySQL adapters handle this case. If you have any insight on how they handle it that would be great. If the time works out, hopefully I'll submit a PR to patch this issue in the next couple weeks.
