### ISSUE TITLE
Is possible set CONNECT_TIMEOUT via DATABASE_URL?

### ISSUE THREAD

**Issue by lazaronixon** [rsim/oracle-enhanced#1022]
I tried to set CONNECT_TIMEOUT as oracle-enhanced://localhost/XE?CONNECT_TIMEOUT=5 but it does'nt work... All ok with TNS connection

**Comment by yahonda** [comment]
It uses EZConnect syntax. I do not think it supports connect_timeout parameter. If you would like to set this parameter value, I'd suggest you to use TNS alias.
