### ISSUE TITLE
Rails5:not work with awesome_nested_set, closure_tree...

### ISSUE THREAD

**Issue by shenhf** [rsim/oracle-enhanced#1025]
I tested some nested set gem work with oracle-enhanced, none of them passed test. 

closure_tree gem:
2.3.0 :013 > p
 => #<Dept id: 10006, name: "信息处", dwh: nil, dzyx: nil, parent_id: nil, created_at: "2016-10-21 01:44:58", updated_at: "2016-10-21 01:44:58">
2.3.0 :014 > c
 => #<Dept id: 10007, name: "信息中心", dwh: nil, dzyx: nil, parent_id: 10006, created_at: "2016-10-21 01:45:20", updated_at: "2016-10-26 00:09:38">
2.3.0 :015 > p.children << c
  Dept Exists (18.2ms)  SELECT  1 AS one FROM "DEPTS" INNER JOIN "DEPT_HIERARCHIES" ON "DEPTS"."ID" = "DEPT_HIERARCHIES"."ANCESTOR_ID" WHERE "DEPT_HIERARCHIES"."DESCENDANT_ID" = :a1 AND "DEPTS"."ID" = :a2 AND ROWNUM <= :a3   [["descendant_id", 10006], ["id", 10007], ["LIMIT", 1]]
  SQL (5.4ms)  UPDATE "DEPTS" SET "PARENT_ID" = :a1, "UPDATED_AT" = :a2 WHERE "DEPTS"."ID" = :a3  [["parent_id", 10006], ["updated_at", 2016-10-26 00:09:38 UTC], ["id", 10007]](4.0ms)  DELETE FROM "DEPT_HIERARCHIES"
WHERE descendant_id IN (
  SELECT DISTINCT descendant_id
  FROM (SELECT descendant_id
    FROM "DEPT_HIERARCHIES"
    WHERE ancestor_id = 10007
       OR descendant_id = 10007
  ) AS x )

ActiveRecord::StatementInvalid: OCIError: ORA-00907: 缺失右括号: DELETE FROM "DEPT_HIERARCHIES"
WHERE descendant_id IN (
  SELECT DISTINCT descendant_id
  FROM (SELECT descendant_id
    FROM "DEPT_HIERARCHIES"
    WHERE ancestor_id = 10007
       OR descendant_id = 10007
  ) AS x )

**Comment by yahonda** [comment]
I'm not familiar with "nested set gem". Would you create a test case to reproduce `ActiveRecord::StatementInvalid: OCIError: ORA-00907`. 

https://github.com/rsim/oracle-enhanced/tree/master/guides/bug_report_templates

Thanks.
