### ISSUE TITLE
default_tablespace haven't stored index of primary key to the index tablespace

### ISSUE THREAD

**Issue by koic** [rsim/oracle-enhanced#1027]
I want to specify default tablespace of AR::Base.primary_key used by
`ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter.default_tablespaces`.

``` ruby
ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter.default_tablespaces =
  {clob: 'TS_LOB', blob: 'TS_LOB', index: 'TS_INDEX', table: 'TS_DATA'}
```

I expect an index of AR::Base.primary_key (`SYS_XXXXXXXX`) to stored in `index: 'TS_INDEX'` tablespace.
But actually, stored in `table: 'TS_DATA'` tablespace.

I did fix that by following forked branch.
- branch ... https://github.com/koic/oracle-enhanced/tree/alter_primary_key_rebuild_tablespace (based on `master` branch)
- commit ... https://github.com/koic/oracle-enhanced/commit/15f666704be07dead297ae62c2c71898c66675ac

I'm going to open a pull request to `master` branch if you'd like to.

In addition, I'm having trouble as the Rails 4.2.7.1 with activerecord-oracle_enhanced-adapter 1.6.7, Then I want going to open a backporting pull request to `release16` branch too.
- branch ... https://github.com/koic/oracle-enhanced/tree/backport_alter_primary_key_rebuild_tablespace (based on `release16` branch)
- commit ... https://github.com/koic/oracle-enhanced/commit/cd69593327d8e8af930c7c02c2e44c5b37081012

How about you?

**Comment by yahonda** [comment]
Please go ahead to open a pull request to master branch then we can review it.

**Comment by koic** [comment]
I opened [a pull request](https://github.com/rsim/oracle-enhanced/pull/1028) . Thanks.
