### ISSUE TITLE
Connections to Secondary Oracle Databases Fail in Rails 5

### ISSUE THREAD

**Issue by hermiti** [rsim/oracle-enhanced#1031]
I just wanted to document and perhaps offer a suggestion to the Rails 5 documentation that if you are connecting to multiple databases that the establish_connection requires a symbol instead of a string in Rails 5.  I'm not sure if this is just a Rails 5 issue or some interaction between Rails 5 and Oracle-Enhanced.  See below:

Works

    establish_connection :secondary_database

Where as the following no longer works:

    establish_connection "secondary_database"

In my case some of my old database connections had used the string argument and were failing, causing me to think that there was an incompatibility between Rails 5 and Oracle-Enhanced.  Anyways, this isn't documented anywhere on the web to my knowledge.

The error that you will receive upon rails server startup is somewhat cryptic:

    ...connection_specification.rb:170:in `spec': database configuration does not specify adapter (ActiveRecord::AdapterNotSpecified)

**Comment by yahonda** [comment]
Thanks for sharing the information.

It looks like this behavior was deprecated in Rails 4.1
https://github.com/rails/rails/commit/ec11807368318845a2542e8f5f51f3f5280135f5
and removed since Rails 5.0.
https://github.com/rails/rails/commit/efdc20f36ccc37afbb2705eb9acca76dd8aabd4f
