### ISSUE TITLE
create_table with custom sequence name?

### ISSUE THREAD

**Issue by bpatram** [rsim/oracle-enhanced#1044]
I'm running version: 1.7.4 of this gem

I am running a legacy database with sequence names for tables that do not follow the default sequence naming scheme this gem defines (table_name_seq). However, when we run unit tests we do so on a new database instance which requires us to migrate our database to the current schema. We have models which define their sequence name (which works great on the existing legacy db!) but when we go to run migrations to re-create those tables in a new test db it uses the default gem defined sequence name. This causes issues such as `OCIError: ORA-02289: sequence does not exist` when doing queries with the model since it is looking for the sequence defined in the model.

Example:

Model:
```ruby
class Foo < ActiveRecord::Base
  self.table_name = "Foo"
  self.primary_key = "FooId"
  self.sequence_name = "Foo_SEQ"
end
```

Migration:
```ruby
create_table "Foo", primary_key: "FooId", force: :cascade do |t|
  t.text    "Name"
end
```

After running a migration on a new db instance we get a sequence named `Foo_seq` instead of `Foo_SEQ`.  Which is to be expected since there is no way to define a custom sequence name.

Is there anyway to define the sequence name when creating a table or maybe a way to override the default sequence naming scheme?

**Comment by yahonda** [comment]
Hi, I'd suggest you to take a look at these methods:

https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb#L478-L484

https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced/quoting.rb#L78-L81

https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced/quoting.rb#L9-L20

Thanks.

**Comment by bpatram** [comment]
Ah very nice, completely overlooked this! Thank you for the quick response!
