### ISSUE TITLE
Locking doesn't work anymore, even with old Oracle visitor

### ISSUE THREAD

**Issue by remofritzsche** [rsim/oracle-enhanced#1066]
Pessimistic locking still doesn't seem to work, even with `use_old_oracle_visitor` set to `true` (see #920):

```
pry(main)> ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter.use_old_oracle_visitor
=> true
pry(main)> u = User.first.lock!
  User Load (106.0ms)  SELECT  "USERS".* FROM "USERS" ORDER BY "USERS"."ID" ASC FETCH FIRST :a1 ROWS ONLY  [["LIMIT", 1]]
ArgumentError:             'Combination of limit and lock is not supported.
            because generated SQL statements
            `SELECT FOR UPDATE and FETCH FIRST n ROWS` generates ORA-02014.`
from /path/to/vendor/gems/gems/arel-7.1.4/lib/arel/visitors/oracle12.rb:9:in `visit_Arel_Nodes_SelectStatement'
```

Funny thing is, `User.connection.arel_visitor` returns `Arel::Visitors::Oracle`, so the old one. But above stack trace indicates the Oracle12 visitor.

In my opinion, this usage is not a corner case but the regular way of doing it. Even the Rails examples (http://api.rubyonrails.org/classes/ActiveRecord/Locking/Pessimistic.html) don't work anymore.

I'd be thrilled if there was a solution for this. Thanks a bunch for having a look at this :)

**Comment by yahonda** [comment]
Thanks for the report. I have updated README #1068 and create a sample repository to use `use_old_oracle_visitor` It needs to be set in initializers as follows.

* https://github.com/yahonda/rep1066

https://github.com/yahonda/rep1066/blob/master/config/initializers/oracle.rb

```ruby
ActiveSupport.on_load(:active_record) do
  ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter.class_eval do
    self.use_old_oracle_visitor = true
  end
end
```

Please reopen if you still reproduces it. Pull request for documents are also welcomed.

Thanks.

**Comment by remofritzsche** [comment]
Thanks a bunch for your help. I've tried your sample application and there it worked. I debugged a little further and noticed that the problem was that our initializer `oracle.rb` was executed *after* we already talked to the database. Renaming our initializer to `0_oracle.rb` solved the issue as it now runs first.

So it definitely wasn't the adapter's fault, sorry for the hassle.
