### ISSUE TITLE
Missing IN or OUT parameter at index:: with `use_old_oracle_visitor` and offset / limit

### ISSUE THREAD

**Issue by remofritzsche** [rsim/oracle-enhanced#1070]
Sorry for bothering you again.

We had to turn on `use_old_oracle_visitor` in order for locking to work (e.g. `User.first.lock!`). However, this reinstates the issue described in #1030 and #1033:

```ruby
User.limit(5).offset(1).to_a
```

results in

```
ActiveRecord::StatementInvalid: Java::JavaSql::SQLException: Missing IN or OUT parameter at index:: 3:
              SELECT * FROM (
                SELECT raw_sql_.*, rownum raw_rnum_
                FROM (SELECT  "USERS".* FROM "USERS" ) raw_sql_ WHERE rownum <= (:a1 + :a2) ) WHERE raw_rnum_ > :a1
from oracle.jdbc.driver.OraclePreparedStatement.processCompletedBindRow(oracle/jdbc/driver/OraclePreparedStatement.java:2076)
```

I really hope there is a way of combining these two fixes as both locking and limiting / ofsetting is crucial for us. Many thanks for your help!

**Comment by yahonda** [comment]
Would you add this entry to your Gemfile and see if this issue still reproduces or not.

``` ruby
gem 'activerecord-oracle_enhanced-adapter', git: 'git@github.com:yahonda/oracle-enhanced.git', branch: 'diag1070'
```

Thanks.

**Comment by remofritzsche** [comment]
Thanks a lot for your quick response! I've just tried your branch and it does not use the old visitor anymore (I think it's because of the removal of `use_old_oracle_visitor`), so locking doesn't work anymore. Would be wonderful if you could have a look at this.

**Comment by yahonda** [comment]
Thanks for testing.  I have updated and confirm the fix locally. 

Would you give it a try by executing `bundle update` to get the updated branch.
```
$ bundle update
..
Using activerecord-oracle_enhanced-adapter 1.7.7 from git@github.com:yahonda/oracle-enhanced.git (at /home/yahonda/git/oracle-enhanced@339b561)
```

Thanks.

**Comment by remofritzsche** [comment]
Brilliant. I'll try it first thing tomorrow. Thanks a lot!

**Comment by remofritzsche** [comment]
Works like a charm, many thanks! Sorry it took me so long to try it out.

Do you know when about we could expect a new release?

**Comment by yahonda** [comment]
#1075 has been merged to master. Thanks for testing.

**Comment by yahonda** [comment]
Oracle enhanced adapter 1.7.8 has been released include this fix.

**Comment by remofritzsche** [comment]
Very nice, thank you. I think it hasn't been pushed to rubygems.org though: https://rubygems.org/gems/activerecord-oracle_enhanced-adapter

**Comment by yahonda** [comment]
Pushed to rubygems.org . Thanks for the reminder.
