### ISSUE TITLE
Rails 3.1 - TypeError: can't dump anonymous class

### ISSUE THREAD

**Issue by frugardc** [rsim/oracle-enhanced#110]
ActiveRecord::StatementInvalid (TypeError: can't dump anonymous class Class: INSERT INTO "ACTIVITIES" ("BROWSER", "CREATED_AT", "DOMAIN", "ENGINE", "FORMAT", "HEADERS", "HOST", "ID", "METHOD", "OS", "PATH_PARAMETERS", "PORT", "PROTOCOL", "QUERY_PARAMETERS", "QUERY_STRING", "REMOTE_IP", "REQUEST_PARAMETERS", "UPDATED_AT", "URL", "USER_AGENT", "USER_ID", "VERSION") VALUES (:a1, :a2, :a3, :a4, :a5, :a6, :a7, :a8, :a9, :a10, :a11, :a12, :a13, :a14, :a15, :a16, :a17, :a18, :a19, :a20, :a21, :a22)):
  app/controllers/application_controller.rb:27:in `log_activity'

Error on insert.  Just upgraded to Rails 3.1, with ruby 1.8.7

activerecord-oracle_enhanced-adapter (1.4.0)
ruby-oci8 (2.0.6)

**Comment by yahonda** [comment]
Closing since it has not been updated recently.
