### ISSUE TITLE
Rails 3.1 - ActiveRecord::StatementInvalid (OCIError: ORA-01741: illegal zero-length identifier:

### ISSUE THREAD

**Issue by frugardc** [rsim/oracle-enhanced#111]
Inserting a null field as alias

"LOOKUP"."SERVICES"."" AS t1_r0

ActiveRecord::StatementInvalid (OCIError: ORA-01741: illegal zero-length identifier: SELECT "LOOKUP"."EQ_MODEL"."MODEL_KEY" AS t0_r0, "LOOKUP"."EQ_MODEL"."VENDOR_KEY" AS t0_r1, "LOOKUP"."EQ_MODEL"."MODEL_NAME" AS t0_r2, "LOOKUP"."EQ_MODEL"."IS_QCD" AS t0_r3, "LOOKUP"."EQ_MODEL"."IS_ACTIVE_YN" AS t0_r4, "LOOKUP"."SERVICES"."" AS t1_r0, "LOOKUP"."SERVICES"."ID" AS t1_r1, "LOOKUP"."SERVICES"."NAME" AS t1_r2, "LOOKUP"."SERVICES"."DESCRIPTION" AS t1_r3, "LOOKUP"."SERVICES"."BUILDING_LIST_SUFFIX" AS t1_r4, "LOOKUP"."EQ_VENDOR"."VENDOR_KEY" AS t2_r0, "LOOKUP"."EQ_VENDOR"."VENDOR_NAME" AS t2_r1 FROM "LOOKUP"."EQ_MODEL" LEFT OUTER JOIN "MODELS_SERVICES" ON "MODELS_SERVICES"."MODEL_ID" = "LOOKUP"."EQ_MODEL"."MODEL_KEY" LEFT OUTER JOIN "LOOKUP"."SERVICES" ON "LOOKUP"."SERVICES"."ID" = "MODELS_SERVICES"."SERVICE_ID" LEFT OUTER JOIN "LOOKUP"."EQ_VENDOR" ON "LOOKUP"."EQ_VENDOR"."VENDOR_KEY" = "LOOKUP"."EQ_MODEL"."VENDOR_KEY" WHERE (is_active_yn like '%%' and upper(model_name) <> upper('unknown'))):

Error on insert. Just upgraded to Rails 3.1, with ruby 1.8.7

activerecord-oracle_enhanced-adapter (1.4.0)
ruby-oci8 (2.0.6)

**Comment by yahonda** [comment]
Closing since it has not been updated recently.
