### ISSUE TITLE
TNS:no listener error

### ISSUE THREAD

**Issue by zmitzie** [rsim/oracle-enhanced#1128]
I have created a rails 4 app and I'm using the `activerecord-oracle_enhanced-adapter` to use Oracle as my database. I'm on MacOS and I have installed all the dependencies properly (ruby-oci8, instantclient, etc). I have inserted my database credentials in my database.yml file, but when I run the server I get the following error `ORA-12541: TNS:no listener` . 

I have checked all the similar questions in Stackoverflow but none of them seems to solve my problem. I have also configured a `tnsname.ora` and `listener.ora` file under `$ORACLE_HOME/network/admin`. I am able to connect to the database from the Oracle SQL Developer running in my laptop successfully.

I'm also attaching my Gemfile, database.yml, tnsname.ora and listener.ora files below:

**Gemfile:**

    source 'https://rubygems.org'
    
    
    gem 'rails', '4.2.7'
    gem 'sqlite3'
    gem 'sass-rails', '~> 5.0'
    gem 'uglifier', '>= 1.3.0'
    gem 'coffee-rails', '~> 4.1.0'
    
    gem 'activerecord-oracle_enhanced-adapter', '~> 1.6.0'
    gem 'jquery-rails'
    gem 'turbolinks'
    gem 'jbuilder', '~> 2.0'
    gem 'sdoc', '~> 0.4.0', group: :doc
    
    gem 'ruby-oci8', '~> 2.2.3'
    
    group :development, :test do
      gem 'byebug'
    end
    
    group :development do
      gem 'web-console', '~> 2.0'
      gem 'spring'
    end

**database.yml:**

    default: &default
      adapter: oracle_enhanced
    
    development:
      <<: *default
      database: mydb.amazonaws.com/ORCL
      port: 1521
      username: user
      password: pass

**listener.ora:**

    LISTENER =
      (DESCRIPTION_LIST =
        (DESCRIPTION =
          (ADDRESS = (PROTOCOL = TCP)(HOST = mydb.amazonaws.com)(PORT = 1521))
        )
      )
**tnsname.ora**

    ORCL =
      (DESCRIPTION =
        (ADDRESS = (PROTOCOL = TCP)(HOST = mydb.amazonaws.com)(PORT = 1521))
        (CONNECT_DATA =
          (SERVER = DEDICATED)
          (SERVICE_NAME = ORCL)
        )
      )

The environment variable `TNS_ADMIN` points to `/opt/oracle/network/admin`, where the 2 .ora files are located. I have also edited my hosts file and added my DB's host under 127.0.0.1. I'm using Oracle 12c.

Any help is highly appreciated. Thank you.

**Comment by yahonda** [comment]
Hi,

Assume your environment have TNS_ADMIN environment variable correctly and tnsnames.ora file entry is valid `database:` entry can be same as ths alias name `ORCL`.

https://github.com/rsim/oracle-enhanced/blob/master/README.md#usage

> If TNS_ADMIN environment variable is pointing to directory where tnsnames.ora file is located then you can use TNS connection name in database parameter.


database.yml:
```ruby
default: &default
  adapter: oracle_enhanced

development:
  <<: *default
  database: ORCL
  port: 1521
  username: user
  password: pass
```

Please give it a try, it it does not solve, please provide some more detailed information.

**Comment by zmitzie** [comment]
I have checked every possible different option in `database.yml`. I checked again now to use TNS but I still get the same error. I double checked that the TNS_ADMIN env variable is set by typing `echo $TNS_ADMIN`, and I got the path `/opt/oracle/network/admin`, the location of the tnsname and listener file

**Comment by yahonda** [comment]
Thanks for the update. Sorry I do not have other information.

**Comment by kubo** [comment]
The `database.yml` creates incorrect connection_string.
```ruby
#
# config created by the database.yml
#
config = {
  database: "mydb.amazonaws.com/ORCL",
  port: 1521,
  username: "user",
  password: "pass",
}

#
# copied from https://github.com/rsim/oracle-enhanced/blob/v1.7.9/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb#L319-L345
#
        username = config[:username] && config[:username].to_s
        password = config[:password] && config[:password].to_s
        database = config[:database] && config[:database].to_s
        schema = config[:schema] && config[:schema].to_s
        host, port = config[:host], config[:port]
        privilege = config[:privilege] && config[:privilege].to_sym
        async = config[:allow_concurrency]
        prefetch_rows = config[:prefetch_rows] || 100
        cursor_sharing = config[:cursor_sharing] || 'force'
        # get session time_zone from configuration or from TZ environment variable
        time_zone = config[:time_zone] || ENV['TZ']

        # using a connection string via DATABASE_URL
        connection_string = if host == 'connection-string'
          database
        # connection using host, port and database name
        elsif host || port
          host ||= 'localhost'
          host = "[#{host}]" if host =~ /^[^\[].*:/  # IPv6
          port ||= 1521
          database = "/#{database}" unless database.match(/^\//)
          "//#{host}:#{port}#{database}"
        # if no host is specified then assume that
        # database parameter is TNS alias or TNS connection string
        else
          database
       end

#
# print the connection_string created by the config
#
puts connection_string
```
This code prints `//localhost:1521/mydb.amazonaws.com/ORCL`.
It must be `//mydb.amazonaws.com/ORCL` or `//mydb.amazonaws.com:1521/ORCL`.

@zmitzie Could you change the `development` entry in the `database.yml` as follows?
```
development:
  <<: *default
  database: mydb.amazonaws.com/ORCL
  username: user
  password: pass
```
or
```
development:
  <<: *default
  host: mydb.amazonaws.com
  port: 1521
  database: ORCL
  username: user
  password: pass
```

**Comment by zmitzie** [comment]
@kubo the first configuration did the job for me. I can't see how I missed that. 

Thank you very much for the help!
