### ISSUE TITLE
Different types for created_at and updated_at

### ISSUE THREAD

**Issue by istrasci** [rsim/oracle-enhanced#1141]
Trying to upgrade my app to Rails 5.0.1, so I upgrade activerecord-oracle_enhanced-adapter to 1.7.0 (and ruby-oci8 to 2.2.3).  Now when I query the class of a `created_at` or `updated_at` column, it returns `Date` instead of `ActiveSupport::TimeWithZone` as it did in Rails 4.2.7.  What gives?

See my [Stackoverflow post](http://stackoverflow.com/q/41603279/209107) for more details and output.

**Comment by yahonda** [comment]
Hi,

Would you refer this [Upgrade Rails 4.2 or older version to Rails 5](
https://github.com/rsim/oracle-enhanced/blob/master/README.md#upgrade-rails-42-or-older-version-to-rails-5) section and change `created_at` and `updated_at` attributes to `:datetime`.

I'd suggest using the latest version of Oracle enhanced adapter 1.7.9 (as of today).

Thanks.

**Comment by istrasci** [comment]
My apologies, I hadn't seen this upgrade procedure.

**Comment by yahonda** [comment]
Thanks for the update.  Glad to know your issue has been resolved.

**Comment by istrasci** [comment]
This works, but the migration itself never runs to completion.  It changes the columns, but then hangs on something and I have to Ctrl+C to cancel it.  Is this caused by the gem, or possibly something else?
