### ISSUE TITLE
ORA-12545: Connect failed because target host or object does not exist

### ISSUE THREAD

**Issue by rajcybage** [rsim/oracle-enhanced#1165]
I have done

Gemfile

    #gem 'httparty'
    gem 'activerecord'
    
    gem 'activerecord-oracle_enhanced-adapter'
    
    gem 'ruby-oci8' 

in config/database.yml

    development:
      adapter: 'oracle_enhanced'
      database: '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=#{lctcst0049})(PORT=#{25881})))(CONNECT_DATA=(SID=#{AWNTST01})))'
      username: 'MODA_RO'
      password: 'merck123'

not working

and also We tried it by url

development:
 adapter: 'oracle_enhanced'
 url: "oracle-enhanced:MODA_RO@merck123//lctcst0049:25881/AWNTST01"

But I got error

    ORA-12545: Connect failed because target host or object does not exist

Please help me

I am already using OracleSql Developer and able to connect the remote database.

Please help

also We got

    irb(main):002:0*       ActiveRecord::Base(url: "oracle-enhanced:MODA_RO@merck123//lctcst0049:25881/AWNTST01", adapter: 'oracle_enhanced')
    NoMethodError: undefined method `Base' for ActiveRecord:Module
            from (irb):2
            from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/commands/console.rb:110:in `start'
            from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/commands/console.rb:9:in `start'
            from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:68:in `console'
            from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
            from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
            from bin/rails:4:in `require'
            from bin/rails:4:in `<main>'
    irb(main):003:0>       ActiveRecord::Base.establish_connection(url: "oracle-enhanced:MODA_RO@merck123//lctcst0049:25881/AWNTST01", adapter: 'oracle
    => #<ActiveRecord::ConnectionAdapters::ConnectionPool:0x5d039f0 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x5d03900>, @spec=#<ActiveRecord::
     @config={:url=>"oracle-enhanced:MODA_RO@merck123//lctcst0049:25881/AWNTST01", :adapter=>"oracle_enhanced"}, @adapter_method="oracle_enhanced_conne
    :ConnectionAdapters::ConnectionPool::Reaper:0x5d038b8 @pool=#<ActiveRecord::ConnectionAdapters::ConnectionPool:0x5d039f0 ...>, @frequency=nil>, @si
    3828 @backend={}, @default_proc=nil>, @connections=[], @automatic_reconnect=true, @available=#<ActiveRecord::ConnectionAdapters::ConnectionPool::Qu
    s::ConnectionPool:0x5d039f0 ...>, @cond=#<MonitorMixin::ConditionVariable:0x5d03780 @monitor=#<ActiveRecord::ConnectionAdapters::ConnectionPool:0x5
    750>>, @num_waiting=0, @queue=[]>>
    irb(main):004:0> class User < ActiveRecord::Base
    irb(main):005:1> self.table_name = "V_BSNSS_SRVC_MDRNZTN"
    irb(main):006:1> end
    => "V_BSNSS_SRVC_MDRNZTN"
    irb(main):007:0> User.new
    OCIError: ORA-12560: TNS:protocol adapter error
            from oci8.c:656:in oci8lib_210.so
            from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/ruby-oci8-2.1.8-x86-mingw32/lib/oci8/oci8.rb:148:in `initialize'
            from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/
            from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/
    ion'
            from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/

**Comment by yahonda** [comment]
Would you refer this document https://github.com/rsim/oracle-enhanced#usage and replace `#{lctcst0049}` style value to the actual string, such as `lctcst0049`.
