### ISSUE TITLE
CRUD operation with nclob data type

### ISSUE THREAD

**Issue by sumantacaptain** [rsim/oracle-enhanced#1166]
Hi,

I have a existing table APPROVALMEMORANDUM table CSCCOMMENTS field & NCLOB datatype. though the field is having data[data is getting stored via another project] but it is not showing with my rails app. I also want to do CRUD operation with that CSCCOMMENTS field.

Version Details =>
Rails 5.0.1
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
activerecord-oracle_enhanced-adapter (1.7.8)

Any help will be highly appreciated.

**Comment by yahonda** [comment]
Hi, Thanks for reporting. Oracle enhanced adapter does not support `NCLOB`.  Pull requests are welcomed but sorry I have no plan to develop it by myself.

**Comment by luke2237** [comment]
I was able to get NCLOB (basic crud + migration) work with a simple change to NATIVE_DATABASE_TYPES. Could this be pulled into the next release? I can create a pull request if needed. This is the minimal change that got be to create a table in a migration. The create table syntax was different though. 

Migration:
class CreateDummies < ActiveRecord::Migration[5.1]
  def change
    create_table :dummies do |t|
      # t.nstring :name_nv #does not work. undefined method 'nstring' for TableDefinition
      t.column :name_nv, :nstring
      t.column :name_nt, :ntext
      t.string :name
      t.timestamps
    end
  end
end


Changes:
diff --git a/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb b/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
index b8aefa8..f1e4398 100644
--- a/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
+++ b/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb
@@ -338,7 +338,9 @@ module ActiveRecord
       NATIVE_DATABASE_TYPES = {
         primary_key: "NUMBER(38) NOT NULL PRIMARY KEY",
         string: { name: "VARCHAR2", limit: 255 },
+        nstring: { name: "NVARCHAR2", limit: 255 },
         text: { name: "CLOB" },
+        ntext: { name: "NCLOB" },
         integer: { name: "NUMBER", limit: 38 },
         float: { name: "BINARY_FLOAT" },
         decimal: { name: "DECIMAL" },
@@ -916,6 +918,7 @@ module ActiveRecord
           register_class_with_limit m, %r(raw)i,            ActiveRecord::OracleEnhanced::Type::Raw
           register_class_with_limit m, %r(char)i,           ActiveRecord::OracleEnhanced::Type::String
           register_class_with_limit m, %r(clob)i,           ActiveRecord::OracleEnhanced::Type::Text
+          register_class_with_limit m, %r(nclob)i,           ActiveRecord::OracleEnhanced::Type::NationalText
 
           m.register_type "NCHAR", ActiveRecord::OracleEnhanced::Type::NationalCharacterString.new
           m.alias_type %r(NVARCHAR2)i,    "NCHAR"
