### ISSUE TITLE
Decouple Composite Primary Keys code from Oracle enhanced adapter

### ISSUE THREAD

**Issue by yahonda** [rsim/oracle-enhanced#1223]
This is rather a proposal and direction, not an issue.

I'm going to decouple Composite Primary Keys code from Oracle enhanced adapter.
Because Oracle enhanced adapter contains some code to support composite primary keys, but these codes have not been tested more than 5 years at Oracle enhanced adapter unit tests.

Here is the high-level overview to decouple Composite Primary Keys code from Oracle enhanced adapter.

#### Test Oracle enhanced adapter `release17` branch with Composite Primary Keys:
* Perform ActiveRecord `5-0-stable` branch unit tests
* Perform Oracle enhanced adapter `release17` branch unit tests
* Perform Composite Primary Keys `master` branch unit tests

#### Decouple Composite Primary Keys code from Oracle enhanced adapter
* Clean up the unnecessary code from Oracle enhanced to satisfy these unit tests above.
* Open pull request(s) to Composite Primary Keys gem
* Remove code from Oracle enhanced adapter `release17` branch

Since Composite Primary Key master now works with Rails 5.0, not 5.1 yet. This plan will be done for `release17` branch first. then move forward this change to Oracle enhanced adapter `master` branch.

**Comment by net1957** [comment]
this project https://github.com/composite-primary-keys/composite_primary_keys already exist.
Is this comparable to Composite Primary Keys code from Oracle enhanced adapter ?

Thanks for your work.

**Comment by yahonda** [comment]
Thanks for the question. Yes. this goal is working with current Composite Primary gem managed at https://github.com/composite-primary-keys/composite_primary_keys

**Comment by net1957** [comment]
Nice.

**Comment by yahonda** [comment]
Here are updates.

I've been working on [decouple_cpk_release17](https://github.com/rsim/oracle-enhanced/tree/decouple_cpk_release17) branch forked from `release17` branch, the removed Composite Primary Key specific code from `decouple_cpk_release17` branch.  No regressions found.

### ActiveRecord unit test results: No regressions same number of failures

- Test with Oracle enhanced adapter `release17` branch
https://circleci.com/gh/yahonda/rails/tree/circleci_5-0-stable

- Test with Oracle enhanced adapter `decouple_cpk_release17` branch
https://circleci.com/gh/yahonda/rails/tree/circleci_5-0-stable_decouple_cpk_release17

### Oracle enhanced adapter unit test results: Both branches passed all unit tests

- Test with Oracle enhanced adapter `release17` branch
https://travis-ci.org/rsim/oracle-enhanced/builds/208742486

- Test with Oracle enhanced adapter `decouple_cpk_release17` branch
https://travis-ci.org/rsim/oracle-enhanced/builds/208664613 

### Composite Primary Key unit test results: Both branches passed all unit tests

- Test with Oracle enhanced adapter `release17` branch
https://circleci.com/gh/yahonda/composite_primary_keys/tree/circleci

- Test with Oracle enhanced adapter `decouple_cpk_release17` branch
https://circleci.com/gh/yahonda/composite_primary_keys/tree/circleci_decouple_cpk_release17

I have opened https://github.com/composite-primary-keys/composite_primary_keys/pull/392 to allow composite primary key unit test can run with Oracle database, but this is just for testing. No need to add some code to Composite Primary Key gem.

I'll open pull requests to Oracle enhanced adapter `master` branch to decouple Composite Primary Key code. But no plan to decouple Composite Primary Key code from `release17` branch since it is a kind of stable branch.

**Comment by yahonda** [comment]
Closed by #1224
