### ISSUE TITLE
ruby 2.4 / Rails 4.2.8 oci_connection.rb:242: warning: constant ::Fixnum is deprecated

### ISSUE THREAD

**Issue by sockmonk** [rsim/oracle-enhanced#1234]
When running Ruby 2.4.0 and Ruby on Rails 4.2.8, I get lots of these warnings when I run rspec:

activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:242: warning: constant ::Bignum is deprecated

activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:242: warning: constant ::Fixnum is deprecated

Note that Rails 4.2.8 supports Ruby 2.4.0.  Are there any plans to backport the fix from Rails 5.0?

**Comment by koic** [comment]
Thanks for the feedback. I have confirmed this issue.

@yahonda
I'm going to open a PR of backport #1048 to the `release16` branch.

And if it's OK with you, I'd like to release oracle-enhanced 1.6.8, after passing the tests and open the pull request for preparing to 1.6.8 release.

How do you think about this?

**Comment by yahonda** [comment]
Closed as #1237 merged to release16 branch. Thanks for reporting.

**Comment by koic** [comment]
Hi @sockmonk 

This warning was resolved oracle-enhanced 1.6.8.

https://rubygems.org/gems/activerecord-oracle_enhanced-adapter/versions/1.6.8

Please try upgrading to oracle-enhanced 1.6.8.
