### ISSUE TITLE
Release 1.6.8 procedures

### ISSUE THREAD

**Issue by yahonda** [rsim/oracle-enhanced#1239]
It explains procedures how to release Oracle enhanced adapter v1.6.8 from release16 branch.

- [x] Compare differences between the previous version of Oracle enhanced adapter and the current one https://github.com/rsim/oracle-enhanced/compare/v1.6.7...release16

- [x] Create a branch from release16 named `prepare_v168`

- [x] Update History.md at `prepare_v168` branch

- [x] Open a pull request to `release16` branch for History.md change with this subject
`Prepare release v1.6.8`

- [x] Review and merge the pull request for History.md
Let me review and merge this pull request. 

- [x] Update VERSION and activerecord-oracle_enhanced-adapter.gemspec and commit at release16 branch directly

- [x] Add tag and push changes to `upstream` (git@github.com:rsim/oracle-enhanced.git)

```
$ git tag v1.6.8
$ git push upstream release16
$ git push upstream --tags
```
- [x] Build Oracle enhanced adapter 1.6.8 to rubygems.org
```
$ rake build
$ cd pkg
$ gem push activerecord-oracle_enhanced-adapter-1.6.8.gem
```
- [x] Release announcement to "oracle-enhanced@googlegroups.com"

- [x] Validate the new version of Oracle enhanced adapter is available at [rubygems.org](https://rubygems.org/gems/activerecord-oracle_enhanced-adapter)

Congratulations, you have all done.

**Comment by yahonda** [comment]
@koic Would you take a look at precedes. This is based on my previous experience then feel free to comment and fix them.

**Comment by koic** [comment]
@yahonda Thank you for showing me the release procedure. I opened a PR that updated History.md. #1241

**Comment by koic** [comment]
I'm worried whether the release announcement to "oracle-enhanced@googlegroups.com" was successful, but I have done the release procedure.

**Comment by yahonda** [comment]
Thank you for your work releasing 1.6.8. 

I have not received a email from google group. hmm may be you need to be a member of the group.

**Comment by koic** [comment]
Thanks for your advice. However, I'm participating in group members... I will post an announcement again.

**Comment by yahonda** [comment]
https://groups.google.com/forum/#!aboutgroup/oracle-enhanced says 

> Only members can post.
> Posts from new members are held for moderation.

Suppose "new members" means those who never posted, your post may held for moderation by owner. I think @rsim owns this group then he will review your email sometime soon. Or would you send him a email asking to approve your post.

**Comment by koic** [comment]
Ah, I see. Thanks for your information. I will send him an email.

**Comment by yahonda** [comment]
I have received the release notification email from google group.  

URL for this history is:
https://github.com/rsim/oracle-enhanced/blob/release16/History.md

Since this is the backport release, then master branch does not have it, Would you reply to the thread to update the URL for history then we will have all done.

**Comment by koic** [comment]
You have a point. I have posted it.

**Comment by yahonda** [comment]
Great we are all set.
