### ISSUE TITLE
Question [Is oracle-enhanced support DRCP]

### ISSUE THREAD

**Issue by coolflighter** [rsim/oracle-enhanced#1294]
Dear Rsim

Please do me a favor let me  ask a question.
There is a Ruby Program access DB with Oracle-enhanced.
The Ruby Program trigger hundreds of new connections very frequently , 
and the connections also stay long time on db(from a few minutes to around 1 hour).
I want to know Is DRCP can alleviate the concurrency issue caused by frequent connections ?
Oracle version is 11.2.0.3 .  If oracle-enhanced support DRCP, 
Can you give me some advice about How to configure Oracle-enhanced & DRCP ?

Thank you very much.
menglong.zheng@oracle.com

**Comment by yahonda** [comment]
I did not know what DRCP means [Database Resident Connection Pooling
](http://docs.oracle.com/database/121/CNCPT/dist_pro.htm#CNCPT1896) . Oracle enhanced adapter is using ActiveRecord connection pooling, not Oracle native ones. Then the answer is no.

**Comment by coolflighter** [comment]
Dear Rsim

Thank you for your answer.
