### ISSUE TITLE
Schema Dump Broken When Also Using Postgres Adapter

### ISSUE THREAD

**Issue by barrettclark** [rsim/oracle-enhanced#1332]
### Steps to reproduce
Please refer https://github.com/rsim/oracle-enhanced/tree/master/guides/bug_report_templates
to create an executable test case

With Rails 5.1 that uses Postgres as it's primary database, and have v1.8 of the AR Oracle adapter (and ruby-oci) also in the Gemfile. Generate a new Rails app. Create 2 simple models (both Postgres tables):

    rails g model something foo bar
    rails g model floop bing:index bong

### Expected behavior
Tell us what should happen

When you run `rake db:migrate` you should get the tables in Postgres, and a clean schema dump that represents the schema.

### Actual behavior
Tell us what happens instead

You get the tables, and the `floops` table with the index cannot be dumped:

```
ActiveRecord::Schema.define(version: 20170509185441) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

# Could not dump table "floops" because of following NoMethodError
#   undefined method `tablespace' for #<ActiveRecord::ConnectionAdapters::IndexDefinition:0x007f9f03a2b5f8>
Did you mean?  table=

  create_table "somethings", force: :cascade do |t|
    t.string "foo"
    t.string "bar"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

end

```

If I comment out the Oracle adapter and ruby-oci gem and rerun the migration I get a clean schema.rb.

### System configuration
**Rails version**: 5.1

**Oracle enhanced adapter version**: 1.8

**Ruby version**: 2.3.0

**Oracle Database version**: InstantClient 12.1

**Comment by yahonda** [comment]
Thanks for the report with exact steps to reproduce. I think #1334 addresses this one. 
Please test by updating your `Gemfile` and update if it fixes your errors.

```ruby
gem 'activerecord-oracle_enhanced-adapter', github: "rsim/oracle-enhanced", branch: "release18_call_super_index_parts"
```

**Comment by barrettclark** [comment]
I get an error that the branch does not exist. I looked in the repo, and I don't see any release* branches.

**Comment by yahonda** [comment]
My bad. I pushed it to my repository.

```ruby
gem 'activerecord-oracle_enhanced-adapter', github: "yahonda/oracle-enhanced", branch: "release18_call_super_index_parts"
```

**Comment by barrettclark** [comment]
Confirmed. This works great! 👍 

I did a `bundle exec rake db:migrate:redo` and verified that the `db/schema.rb` is good:

```
ActiveRecord::Schema.define(version: 20170509185441) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "floops", force: :cascade do |t|
    t.string "bing"
    t.string "bong"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["bing"], name: "index_floops_on_bing"
  end

  create_table "somethings", force: :cascade do |t|
    t.string "foo"
    t.string "bar"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

end
```

**Comment by yahonda** [comment]
Thanks for the validation.  I'm going to release Oracle enhanced adapter 1.8.1 including this fix.

**Comment by yahonda** [comment]
Oracle enhanced adapter 1.8.1 has been released.
