### ISSUE TITLE
Views are not dumped into structure.log

### ISSUE THREAD

**Issue by deepj** [rsim/oracle-enhanced#1339]
### Steps to reproduce

Migration
```ruby
class CreateSomeView < ActiveRecord::Migration[5.0]
  def up
    execute <<~SQL.squish
      CREATE VIEW "SOME_VIEW" AS ...
    SQL
  end
end
```

After then, run `bin/rails db:migrate`

### Expected behavior
See `CREATE VIEW "SOME_VIEW" AS ...` in `db/structure.sql`

### Actual behavior
Nothing like that is there

### System configuration
**Rails version**: 5.0.3

**Oracle enhanced adapter version**: 1.7.11

**Ruby version**: 2.3.1

**Oracle Database version**: 12.1.0.2

**Comment by yahonda** [comment]
Database views are generated to `db/structure.sql` only when `structure_dump` set to `db_stored_code`

https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced/database_tasks.rb#L48-L50


```ruby
          if @config["structure_dump"] == "db_stored_code"
            File.open(filename, "a") { |f| f << connection.structure_dump_db_stored_code }
          end
```

* database.yml

```ruby
default: &default
  adapter: oracle_enhanced
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: username
  password: password
  structure_dump: db_stored_code
```

If you still reproduce this after changing database.yml please update.

**Comment by deepj** [comment]
Hello,

after enabling the options it started working. Is it possible to mention in `README.md`? I guess many people using this adapter don't know about this option.

And thank you a lot of the help!

**Comment by yahonda** [comment]
Thanks for the update. 
I'm thinking about to dump views by default in 1.9.  Pull requests for documents is always welcomed.
