### ISSUE TITLE
Bundler could not find compatible versions for gem "activerecord":

### ISSUE THREAD

**Issue by muaaz-vf** [rsim/oracle-enhanced#1341]
Bundler could not find compatible versions for gem "activerecord":
                      In Gemfile:
                       activerecord-oracle_enhanced-adapter (~> 1.8.0) was resolved to 1.8.0, which depends on
                             activerecord (~> 5.1.0.rc)

                  rails (~> 5.0.1) was resolved to 5.0.1, which depends on
                      activerecord (= 5.0.1)

**Comment by yahonda** [comment]
Would you provide step to reproduce and your application `Gemfile`?

**Comment by yahonda** [comment]
Closing since no response.
