### ISSUE TITLE
ActiveRecord::StatementInvalid: OCIError: ORA-12801: error signaled in parallel query server P000

### ISSUE THREAD

**Issue by sockmonk** [rsim/oracle-enhanced#1343]
### Steps to reproduce
See https://github.com/rsim/oracle-enhanced/issues/1130.
In "Steps to reproduce", I cloned the same docker image of oracle, 12.1.0.2 EE.

### Expected behavior
I should successfully execute a test case using the oracle database.
I wonder if I need to upgrade not just my local Docker version of Oracle, but all versions in QA and Production. If so, that will be a while, since they just upgraded late last year.

### Actual behavior
When I run any test case that touches the database:

     ActiveRecord::StatementInvalid:
       OCIError: ORA-12801: error signaled in parallel query server P000
       ORA-01006: bind variable does not exist: SELECT LOWER(view_name) FROM all_views WHERE owner = SYS_CONTEXT('userenv', 'current_schema')

### System configuration
**Rails version**:
Attempted upgrade to Rails 5.1.1.  Rails 5.0 did not have this behavior.

**Oracle enhanced adapter version**:
1.8.1

**Ruby version**:
2.3.4 

**Oracle Database version**:
12.1.0.2 EE

**Comment by yahonda** [comment]
Thanks for the report.

Take one of these two actions:

* Apply "DB PSU 12.1.0.2.161018 (Oct2016)" or later. See "https://github.com/oracle/docker-images/tree/master/OracleDatabase/samples/applypatch" how to.

* Use Oracle Database 12cR2 12.2.0.1

#1190 changes at Oracle enhanced adapter 1.8 to use `current_schema` may trigger `ORA-12801`
