### ISSUE TITLE
ActiveRecord::StatementInvalid: OCIError: ORA-01002: fetch out of sequence: SELECT 

### ISSUE THREAD

**Issue by Messinger** [rsim/oracle-enhanced#1345]
### Steps to reproduce

Just try a Model.lock.find_by(:key => value)

### Expected behavior
When found a row-locked result, otherwise nil

### Actual behavior
Raises a "ActiveRecord::StatementInvalid: OCIError: ORA-01002: fetch out of sequence: SELECT" error

### System configuration
**Rails version**: 4

**Oracle enhanced adapter version**:
1.6.7

**Ruby version**:
2.3.4

**Oracle Database version**:
12

**Comment by yahonda** [comment]
Thanks for opening an issue. Please create an executable test case by following https://github.com/rsim/oracle-enhanced/tree/master/guides/bug_report_templates

**Comment by yahonda** [comment]
Closing since no reponse.
