### ISSUE TITLE
Add triggers to structure dump

### ISSUE THREAD

**Issue by jlahtinen** [rsim/oracle-enhanced#1355]
It would be nice if there could be triggers in structure dump.

This could work quite well but not 100% well formatted and not sure if any other problems.
```ruby
def structure_dump_triggers(table_name)
  trigger_names = select_values("select trigger_name from user_triggers where table_name = '#{table_name}'")
  trigger_names.map do |trigger_name|
    select_values("select dbms_metadata.get_ddl('TRIGGER','#{trigger_name}') from dual")
  end
end
```

Is there problems using get_ddl function? Should this be make differently e.g. reading text from all_source? Can triggers in recyclebin be mistakenly seen if using user_triggers?

**Comment by yahonda** [comment]
Triggers and other stored programs and database views are generated `db/structure.sql` only when `structure_dump` set to `db_stored_code` as discussed in #1339 
* database.yml

```ruby
default: &default
  adapter: oracle_enhanced
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: username
  password: password
  structure_dump: db_stored_code
```

**Comment by jlahtinen** [comment]
Thanks this looks good.
