### ISSUE TITLE
Insertion doesn't work when composite primary_key is defined in the rails model 

### ISSUE THREAD

**Issue by sumitdey035** [rsim/oracle-enhanced#1356]
### Steps to reproduce
I added a composite key in the model Link
**Link Model**
```
class Link < ActiveRecord::Base
  self.primary_keys = :link_id, :map_id
end
```
**Link migration**
```
class CreateLinks < ActiveRecord::Migration
  def change
    create_table :links do |t|
      t.integer :link_id
      t.integer :map_id
      t.string :name
    end
  end
end
```
**Trying to create links from console**

> [1] pry(main)> Link.create(link_id: 12345, map_id: 100, name: "kj")
>  
>   SQL (63.0ms)  INSERT INTO "LINKS" ("LINK_ID", "MAP_ID", "NAME", "link_id,map_id") VALUES (:a1, :a2, :a3, :a4)  [["link_id", 12345], ["map_id", 100], ["name", "kj"], [nil, 1]]
> ActiveRecord::StatementInvalid: NoMethodError: undefined method `returning_id?' for nil:NilClass: INSERT INTO "LINKS" ("LINK_ID", "MAP_ID", "NAME", "link_id,map_id") VALUES (:a1, :a2, :a3, :a4)

### System configuration
**Rails version**: 4.2.8

**Oracle enhanced adapter version**: 1.6.9

**Ruby version**: JRuby 9.1.5.0

**Oracle Database version**: 12c(1st release)

**composite_primary_keys**:  8.1.6 (this gem is for composite primary keys)

**Comment by yahonda** [comment]
There are two 3rd party Rails gems involved, Oracle enhanced adapter and Composite Primary Keys.
Also Rails version 4.2 is almost ending support, please try these items:

- Create an executable testcase, not just code snippets
- Upgrade Rails version to 5.0, Oracle enhanced adapter 1.7.10 and validate if this testcase reproduce it using Rails 5.0.
Looks like Composite Primary Key gem does not support Rails 5.1 yet.


If you are interested in diving into the source code, I'd suggest to take a look at `sql_for_insert` method here.

https://github.com/rsim/oracle-enhanced/blob/release16/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb#L107-L114

Thanks.
