### ISSUE TITLE
It seems that before_save leaks cursors

### ISSUE THREAD

**Issue by jlahtinen** [rsim/oracle-enhanced#1358]
### Steps to reproduce
https://github.com/jlahtinen/oracle-enhanced/commit/f5ae709cc9f57d72532f4e72fd88ce6caa2e3141
(includes $stdin.gets so spec can be paused and database can be queried to see how many cursors are opened)

### Expected behavior
All used cursors should be released

### Actual behavior
java.sql.SQLException: ORA-01000: maximum open cursors exceeded

### System configuration
5.1.0 - 5.2-alpha

**Oracle enhanced adapter version**:
master

**Ruby version**:
jruby 9.1.10.0

**Oracle Database version**:
Oracle Database 12c Standard Edition Release 12.1.0.2.0 - 64bit Production

**Comment by jlahtinen** [comment]
With ojdbc7.jar and ojdbc8
Also with 2.4.0p0 and ruby-oci8 (2.2.4)

**Comment by yahonda** [comment]
Would you check these two values and configure `:statement_limit` value at database.yml 
is larger than `open_cursors` at database instance.

* `open_cursors` at database instance

```sql
SQL> select name,value from v$parameter where name = 'open_cursors';

NAME
--------------------------------------------------------------------------------
VALUE
--------------------------------------------------------------------------------
open_cursors
1200

```


* `:statement_limit` value at database.yml

Since Oracle enhanced adapter 1.8.0 including this pull request https://github.com/rsim/oracle-enhanced/pull/1228, this default value changed from 250 to 1000.

**Comment by jlahtinen** [comment]
`alter system set open_cursors = 100 scope=both;`

Then in `database.yml` in our application
```
test:
  adapter: oracle_enhanced
  driver: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521/oracle
  username: x_test
  password: x_test
  statement_limit: some_limit
```
1) `statement_limit: 50` => ORA-01000: maximum open cursors exceeded
2) `statement_limit: 100` => ORA-01000: maximum open cursors exceeded
3) `statement_limit: 200` => ORA-01000: maximum open cursors exceeded

**Comment by jlahtinen** [comment]
I used statement_limit in wrong place in our database.yml. I also used it in this project `spec/spec_config.yml` but it does not have effect there.

It now seems that curors are not leaked at all.

**Comment by jlahtinen** [comment]
@yahonda I think history should mention that 250 is changed to 1000 when speaking about  #1228 and statement_limit?

**Comment by yahonda** [comment]
#1362 has been merged to add upgrade section for `:statement_limit` value. please feel free to open a pull request if you need more information.

**Comment by KidA001** [comment]
@jlahtinen @yahonda I'm not sure I quite understand what resolved this issue. I'm still having problems in my test database. My cursor limit was 300 when I ran `select name,value from v$parameter where name = 'open_cursors';` I changed `statement_limit: 300` in database.yml but that had no effect.

**Comment by KidA001** [comment]
Maybe this will be helpful for someone else coming here, but I didn't realize in `database.yml` that `statement_limit: some_number` needs to be _lower_ than the result of your open cursors in `select name,value from v$parameter where name = 'open_cursors';`

My open cursors were `300` and I set `statement_limit` to `250` and it resolved the error

**Comment by veejar** [comment]
From this guide:
https://github.com/rsim/oracle-enhanced
If your application gets ORA-01000: maximum open cursors exceeded after upgrading to Rails 5.1 check these two values and configure :statement_limit value at database.yml is larger than open_cursors at Oracle database instance.

I think upgrade guide above is incorrect. :statement_limit should be smaller then open_cursors. I have fixed the same issue with such values:
statement_limit = 250, open_cursors = 300
statement_limit = 1000, open_cursors = 1200

**Comment by yahonda** [comment]
#1573 has been opened to fix it. Thanks for the reporting.
