### ISSUE TITLE
rails 5 attribute api not properly changing date column to ruby DateTime

### ISSUE THREAD

**Issue by InteNs** [rsim/oracle-enhanced#1370]
### Steps to reproduce
have a oracle DATE column with date and time information

| name | type | value | 
|---------------|------|---------------------|
| planned_start | DATE | 2014-12-16 19:41:50 | 

in rails add this to the model:
```ruby
Class TestModel
  attribute :planned_start, :datetime
end
```

### Expected behavior
after reading the documentation and especially this part about legacy schema support:
```ruby
  # set which DATE columns should be converted to Ruby Date using ActiveRecord Attribute API
  # Starting from Oracle enhanced adapter 1.7 Oracle `DATE` columns are mapped to Ruby `Date` by default.
  attribute :hired_on, :date
  attribute :birth_date_on, :date

  # set which DATE columns should be converted to Ruby Time using ActiveRecord Attribute API
  attribute :last_login_time, :datetime
```
I expect the planned_start attribute to have date and time information

btw, we have 100's of tables with DATE columns, and we're not the only company using this database so writing one huge migration changing all this is not really on the table.

### Actual behavior
what happens is that the planned_start attribute still only has date information

### System configuration
**Rails version**: 5.0.4

**Oracle enhanced adapter version**: 1.7.11

**Ruby version**: 2.3.1

**Oracle Database version**: 11g(test)  and 12c(prod)

**Comment by koic** [comment]
Thanks for reporting. Would you please create a reproduce script based on this template below.

https://github.com/rsim/oracle-enhanced/tree/master/guides/bug_report_templates

Thank you.

**Comment by InteNs** [comment]
Ah, I found the issue after making the reproduce script and it working there.

apparently `alias_attribute` can't be used together with the rails attribute api 😞
