### ISSUE TITLE
ROWNUM() not consistent with big tables

### ISSUE THREAD

**Issue by mickael-palma-argus** [rsim/oracle-enhanced#1393]
### Steps to reproduce
```ruby
model.offset(0).limit(100).to_sql
"SELECT * FROM (SELECT raw_sql_.*, rownum raw_rnum_ FROM (SELECT  \"table\".* FROM \"table\" ) raw_sql_ WHERE rownum <= (0 + 100) ) WHERE raw_rnum_ >"
```

### Expected behavior
Consistency with the rownum value with big tables.

### Actual behavior
When using `model.find_each` method to generate a CSV for an ETL process.
When I import the CSV it raises : `Key (id)=(X) already exists`
When I check the ID in my Oracle DB I have only one record while the CSV has duplicated rows.

A DBA explained to me that it is preferable to use `DENSE_RANK()` instead of `ROWNUM()`

How can I override the default behaviour ?

### System configuration
**Rails version**: not used but I'm using activerecord 5.1.2

**Oracle enhanced adapter version**: Using activerecord-oracle_enhanced-adapter 1.8.1

**Ruby version**: Ruby 2.4.1

**Oracle Database version**: Oracle 10g

**Comment by yahonda** [comment]
Thanks for the report. 

Without `order` the result is UNKNOWN.  Then the result of  `model.offset(0).limit(100)` is not guaranteed.  I think you will need to add `order` to guarantee the result of this like `model.order(:some_attribute).offset(0).limit(100)`

I have created a sample test case to explain this.
https://github.com/yahonda/rep1393/blob/master/rep1393.rb

```ruby
$ ruby rep1393.rb
...
Finished in 0.374368s, 10.6847 runs/s, 85.4775 assertions/s.

  1) Failure:
BugTest#test_offset_and_limit_does_not_guarantee_order_data_created_in_descending_order [rep1393.rb:106]:
Expected /Peter/ to match "Natasha".

4 runs, 32 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by mickael-palma-argus** [comment]
The order is specified when I use `find_each` or `find_in_batch`.

**Comment by yahonda** [comment]
Thanks for the update.

Unfortunately, this sql statement provided does not have any `ORDER BY` clause. Here the order is not guaranteed.

```sql
"SELECT * FROM (SELECT raw_sql_.*, rownum raw_rnum_ FROM (SELECT  \"table\".* FROM \"table\" ) raw_sql_ WHERE rownum <= (0 + 100) ) WHERE raw_rnum_ >"
```
Would you provide a executable test case using the template available from https://github.com/rsim/oracle-enhanced/tree/master/guides/bug_report_templates

Thanks.

**Comment by mickael-palma-argus** [comment]
Here is the `find_each`query from AR logger :
```sql
 SELECT * FROM (SELECT  "table".* FROM "table" WHERE ("table"."ID" > 1) ORDER BY "table"."ID" ASC ) WHERE ROWNUM <= :a1  [["LIMIT", 50000]]
```

As you can see `ROWNUM()` is used, `DENSE_RANK()` would a more precise choice. What do you think ?

**Comment by yahonda** [comment]
Since I am not able to recreate this issue without a test case, I would prefer not to try to create a test cases from code snippets provided. I have no answer from my side now.

If you are interested in changing SQL function from `ROWNUM()` to `DENSE_RANK()` ,  Feel free to take a look at `Arel::Visitors::Oracle::ToSql`.

**Comment by yahonda** [comment]
`Arel::Visitors::Oracle::ToSql` souce code location is https://github.com/rails/arel/blob/master/lib/arel/visitors/oracle.rb

**Comment by mickael-palma-argus** [comment]
Nice, I will take a look at it and try monkey patching.
If it solves my use case I'll make a pull request with proper test cases.

Thx.

**Comment by javornikolov** [comment]
@mickael-palma-argus,

The following query looks correct to me:

``` SQL
 SELECT * FROM (SELECT  "table".* FROM "table" WHERE ("table"."ID" > 1) ORDER BY "table"."ID" ASC ) WHERE ROWNUM <= :a1  [["LIMIT", 50000]]
```

The result would be consistent as soon as ID column is unique in the table (and soon as you're not hitting some Oracle bug). You may run the query directly in the database to see the result.

`DENSE_RANK()` and `ROWNUM()` are different functions and the result would differ in certain cases. E.g.:

|Record ID| x | dense_rank(x) over (order by x) | rownum() over (order by x) |
|---|---|---|---|
1|1|1|1|
2|7|2|2|
3|8|3|3|
4|8|3|4|
5|9|4|5|

`dense_rank` may be useful for getting the answer of a question like "give me the records with the lowest 3 values of x". The answer would be:

|Record ID| x | dense_rank(x) over (order by x) | rownum() over (order by x) |
|---|---|---|---|
1|1|1|1|
2|7|2|2|
3|8|3|3|
4|8|3|4|

Note that there are 4 records here. My point is that "first N records ordered by x" and "the records with lowest N values of x" are different things. You won'd benefit of `DENSE_RANK` in the latter case, and that's only makes sense only when x is not unique.

In the special case when x is a **unique column (or set of columns)** in the resultset - then `dense_rank()` and `rownum()` would return the same result. So it doesn't really matter which one would be used - I would vote for `rownum()` for sake of simplicity.


The problem should be something else. I may think of potential risk if the data is feteched in several batches - i.e. several executions of similar SQL query with different offsets: it might be something wrong with the calculation of start/end of each batch. (That's a wild guess though, I'm not familiar with the underlying code).

**Comment by mickael-palma-argus** [comment]
@javornikolov thank you for your detailed insights.
I am actually experiencing this problem while exporting join tables so there is no uniq ID involved.
I'm pretty confident in ActiveRecord find_each underlying code. I think it is very specific to old Oracle version.
