### ISSUE TITLE
valid_table_name returns false when owner and table name are in different case

### ISSUE THREAD

**Issue by mlh758** [rsim/oracle-enhanced#1408]
### Steps to reproduce
Please refer https://github.com/rsim/oracle-enhanced/tree/master/guides/bug_report_templates
to create an executable test case

https://github.com/rsim/oracle-enhanced/blob/be25c410a71684c912d0135a0d52b31091f574ea/lib/active_record/connection_adapters/oracle_enhanced/quoting.rb#L75

Run this method against 'TEST_DBA.some_table_name'

### Expected behavior
Method should return `true`

### Actual behavior
Method returns `false`

### System configuration
**Rails version**: 4.2.8

**Oracle enhanced adapter version**: 1.6.9

**Ruby version**: 2.4.1

**Oracle Database version**: 11g

It should probably just split on the `.` if one exists and then run the second half of the validation, checking for camelcase, against the table name portion.

Alternatively, this line:
https://github.com/rsim/oracle-enhanced/blob/be25c410a71684c912d0135a0d52b31091f574ea/lib/active_record/connection_adapters/oracle_enhanced/connection.rb#L42

Should just upcase unless the table name is quoted instead of using `valid_table_name?` to decide.

**Comment by yahonda** [comment]
Hi, Would you open a pull request with fix and test cases to master branch?

**Comment by mlh758** [comment]
I can do that. It might be a couple of days though.

**Comment by mlh758** [comment]
I created a fork and followed the instructions [here](https://github.com/rsim/oracle-enhanced/blob/master/RUNNING_TESTS.md).

I'm getting 5 failures out of the box.

3 of them look like this:
```
  3) OracleEnhancedAdapter schema definition lob in table definition should use default tablespace for clobs
     Failure/Error: expect(TestPost.connection.select_value("SELECT tablespace_name FROM user_lobs WHERE table_name='TEST_POSTS' and column_name = 'TEST_BLOB'")).not_to eq(DATABASE_NON_DEFAULT_TABLESPACE)

       expected: value != "SYSTEM"
            got: "SYSTEM"

       (compared using ==)
```

One looks like this:
```
  2) OracleEnhancedAdapter timestamp with timezone support / TIMESTAMP WITH TIME ZONE values from ActiveRecord model should return Time value with fractional seconds from TIMESTAMP columns
     Failure/Error: if row = @raw_cursor.fetch

     ActiveRecord::StatementInvalid:
       OCIError: ORA-01805: possible error in date/time operation: SELECT  "AR_INTERNAL_METADATA".* FROM "AR_INTERNAL_METADATA" WHERE "AR_INTERNAL_METADATA"."KEY" = :a1 AND ROWNUM <= :a2
```

and the last is this:
```
  1) OracleEnhancedAdapter explain should explain query with binds
     # Pending until further investigation made for #908 JRuby and #1386 for CRuby
     Failure/Error: sub = Arel::Nodes::BindParam.new.to_sql

     ArgumentError:
       wrong number of arguments (0 for 1)
```

I don't want to move forward making changes until the tests pass on the code I checked out from master.
