### ISSUE TITLE
schema: setting not honored by structure dump

### ISSUE THREAD

**Issue by dgarwood** [rsim/oracle-enhanced#1421]
Background: I'm working for a company that has an oracle system with decades worth of PL/SQL in the database, and need a way to stand up a local copy with the least amount of effort.

I haven't had a chance to build a test case for this yet, but wanted to report the problem in case someone else was also dealing with this.  I'm hoping to get a PR with working tests together this weekend.

### Steps to reproduce
Please refer https://github.com/rsim/oracle-enhanced/tree/master/guides/bug_report_templates
to create an executable test case

1. create oracle database with two different users/schemas
1. add tables to one schema, give the other schema dba permissions
1. run `bin/rake db:structure:dump` from the config that has the dba permissions with it's schema configured to use the table schema

### Expected behavior
db/structure.sql should have fully populated information for tables and columns

### Actual behavior
db/structure.sql is missing table columns

this is caused because [structure_dump.rb](https://github.com/rsim/oracle-enhanced/blob/0fad179f220c660f0f946ae6e559aac8b09df1d7/lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb#L14-L24) has these references `SYS_CONTEXT('userenv', 'session_user')` when it should have the following `SYS_CONTEXT('userenv', 'current_user')`.  (first line in linked code works as expected, last line shows the problem code).

This also affects much of the pl/sql code that would be dumped by the `structure_dump: db_stored_code` setting, reading from the user schema and not the configured schema.

Changing these settings in the adapter's code after it's been installed by bundler solves the problem, but obviously isn't a long term solution.  I also didn't see any test cases in [oracle_enhanced_structure_dump.rb](https://github.com/rsim/oracle-enhanced/blob/master/spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb) to indicate if the schema support was working for structure dump.

### System configuration
**Rails version**: 4.1.16, 4.2.9, 5.0.5

**Oracle enhanced adapter version**: 1.5.6, 1.6.9, 1.7.11

**Ruby version**: 2.3.0

**Oracle Database version**: 12c

**Comment by yahonda** [comment]
Thanks for explaining your use cases. Would you mind opening a pull request to satisfy your requirement?

**Comment by dgarwood** [comment]
in looking into our environment further, I discovered there are also several other areas broken in the structure dump, and it looks like most of this is related to the change to support Rails default foreign_key format.

https://github.com/rsim/oracle-enhanced/pull/618

Since it looks like you pulled the code that supported composite foreign keys, I wanted to find out if you have any objections to adding support for those back in, and what your thoughts are related to that.

**Comment by yahonda** [comment]
Thanks for the update. Unfortunately, I prefer not to add composite foreign key support back to Oracle enhanced adapter.
