### ISSUE TITLE
maximum open cursors exceeded error

### ISSUE THREAD

**Issue by Dusht** [rsim/oracle-enhanced#1426]
### Steps to reproduce
Simple loop with database queries

```
10000.times do |i|
  User.find_by_id(i)
  Person.find_by_id(i)
  Company.find_by_id(i)
  # couple of select queries for 10000 times (In real example, these queries are little intense, take around 100ms for each select to complete)
  # It halts somewhere between 700 to 800 most of the times
end
```

### Expected behavior
Should do the search queries for 10000 times.
Note: It runs fine on *XE* (development) but not on *Enterprise edition* (production). 

### Actual behavior
Halts in between with error `ORA-01000: maximum open cursors exceeded: SELECT  ...`

### System configuration
**Rails version**: 5.1.1

**Oracle enhanced adapter version**: 1.8.1

**Ruby version**: 2.4

**Oracle Database version**: Oracle Database 12c Enterprise Edition (12.1.0.2.0)

I have already tried setting `statement_limit: 1000` (500 and 800 as well, where it is 300 in my database) in database.yml. Further I tried setting `cursor_sharing: exact` in database.yml, but doesn't work out. 

Also I have same code working for Rails 2.3, Ruby 1.8.7 and enhanced_adapter version 1.4.1 with same database.

**Comment by koic** [comment]
Thanks for reporting. There is a possibility of the same problem as #1358.
Would you please try the following upgrade guide?
https://github.com/rsim/oracle-enhanced/#upgrade-rails-50-or-older-version-to-rails-51

**Comment by Dusht** [comment]
@koic I have followed the upgrade guide already and I have been through all the issues reported related to cursors + any article/blog/SO I found related to it, but no luck.

**Comment by yahonda** [comment]
What I can suggest now is create a reproducible test case (not just code snippets) would be helpful. 
That is the why issue template has link to https://github.com/rsim/oracle-enhanced/tree/master/guides/bug_report_templates

**Comment by KidA001** [comment]
I'm having the same issue. ATM I'm not sure exactly sure how to reproduce it. It's happening when I'm running a particular test-case. Any workarounds?

**Comment by KidA001** [comment]
For anyone else coming here, I was able to resolve it, see my comment at https://github.com/rsim/oracle-enhanced/issues/1358#issuecomment-329925397

**Comment by tagliala** [comment]
Hi, I'm experiencing this issue when using Rails with a [delayed job](https://github.com/collectiveidea/delayed_job) background process.

Unfortunately I'm not able to provide a reproducible test case, it appears to be random, usually after some days of uptime. The background process itself gets killed after 10 tries

Rails log (last 3 events):
```
D, [2017-09-25T20:50:11.071672 #24129] DEBUG -- :   Delayed::Backend::ActiveRecord::Job Load (7.4ms)  SELECT * FROM (SELECT  "DELAYED_JOBS".* FROM "DELAYED_JOBS" WHERE ((run_at <= '2017-09-25 18:50:11.062236' AND (locked_at IS NULL OR locked_at < '2017-09-25 18:45:11.062320') OR locked_by = 'delayed_job host:hostname pid:24129') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC ) WHERE ROWNUM <= :a1  [["LIMIT", 5]]
D, [2017-09-25T20:51:11.077521 #24129] DEBUG -- :   Delayed::Backend::ActiveRecord::Job Load (2.7ms)  SELECT * FROM (SELECT  "DELAYED_JOBS".* FROM "DELAYED_JOBS" WHERE ((run_at <= '2017-09-25 18:51:11.072657' AND (locked_at IS NULL OR locked_at < '2017-09-25 18:46:11.072751') OR locked_by = 'delayed_job host:hostname pid:24129') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC ) WHERE ROWNUM <= :a1  [["LIMIT", 5]]
D, [2017-09-25T20:52:11.083033 #24129] DEBUG -- :   Delayed::Backend::ActiveRecord::Job Load (2.8ms)  SELECT * FROM (SELECT  "DELAYED_JOBS".* FROM "DELAYED_JOBS" WHERE ((run_at <= '2017-09-25 18:52:11.078261' AND (locked_at IS NULL OR locked_at < '2017-09-25 18:47:11.078335') OR locked_by = 'delayed_job host:hostname pid:24129') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC ) WHERE ROWNUM <= :a1  [["LIMIT", 5]]
F, [2017-09-25T20:52:11.206842 #24129] FATAL -- : OCIError: ORA-01000: maximum open cursors exceeded:           SELECT DECODE(table_name, UPPER(table_name), LOWER(table_name), table_name)
          FROM all_tables WHERE owner = SYS_CONTEXT('userenv', 'current_schema') AND secondary = 'N'
```

Delayed Job log (last 3 events):
```
I, [2017-09-25T20:50:11.071944 #24129]  INFO -- : 2017-09-25T20:50:11+0200: [Worker(delayed_job host:hostname pid:24129)] Error while reserving job: OCIError: ORA-00604: error occurred at recursive SQL level 1
ORA-01000: maximum open cursors exceeded: SELECT * FROM (SELECT  "DELAYED_JOBS".* FROM "DELAYED_JOBS" WHERE ((run_at <= '2017-09-25 18:50:11.062236' AND (locked_at IS NULL OR locked_at < '2017-09-25 18:45:11.062320') OR locked_by = 'delayed_job host:hostname pid:24129') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC ) WHERE ROWNUM <= :a1
I, [2017-09-25T20:51:11.077799 #24129]  INFO -- : 2017-09-25T20:51:11+0200: [Worker(delayed_job host:hostname pid:24129)] Error while reserving job: OCIError: ORA-00604: error occurred at recursive SQL level 1
ORA-01000: maximum open cursors exceeded: SELECT * FROM (SELECT  "DELAYED_JOBS".* FROM "DELAYED_JOBS" WHERE ((run_at <= '2017-09-25 18:51:11.072657' AND (locked_at IS NULL OR locked_at < '2017-09-25 18:46:11.072751') OR locked_by = 'delayed_job host:hostname pid:24129') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC ) WHERE ROWNUM <= :a1
I, [2017-09-25T20:52:11.083765 #24129]  INFO -- : 2017-09-25T20:52:11+0200: [Worker(delayed_job host:hostname pid:24129)] Error while reserving job: OCIError: ORA-00604: error occurred at recursive SQL level 1
ORA-01000: maximum open cursors exceeded: SELECT * FROM (SELECT  "DELAYED_JOBS".* FROM "DELAYED_JOBS" WHERE ((run_at <= '2017-09-25 18:52:11.078261' AND (locked_at IS NULL OR locked_at < '2017-09-25 18:47:11.078335') OR locked_by = 'delayed_job host:hostname pid:24129') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC ) WHERE ROWNUM <= :a1
```

I'm going to try @KidA001 's suggestion, by decreasing the number of cursors from 300 to 250.

I would like to know if I need extra configuration, e.g.: specifying a different number of cursor for background processes

**Comment by veejar** [comment]
From this guide:
https://github.com/rsim/oracle-enhanced
If your application gets ORA-01000: maximum open cursors exceeded after upgrading to Rails 5.1 check these two values and configure :statement_limit value at database.yml is larger than open_cursors at Oracle database instance.

I think upgrade guide above is incorrect. :statement_limit should be smaller then open_cursors. I have fixed the same issue with such values:
statement_limit = 250, open_cursors = 300
statement_limit = 1000, open_cursors = 1200
