### ISSUE TITLE
Congratulations to @yahonda on becoming an Oracle ACE

### ISSUE THREAD

**Issue by cjbj** [rsim/oracle-enhanced#1444]
@yahonda has become an [Oracle ACE](https://apex.oracle.com/pls/apex/f?p=19297:4:::NO:4:P4_ID:16420). Congratulations!  More info is [here](http://www.oracle.com/technetwork/community/oracle-ace/index.html).

**Comment by yahonda** [comment]
Thanks for the nomination. Let me close since 1 week passed.
