### ISSUE TITLE
Float field rounded, cannot set precision

### ISSUE THREAD

**Issue by KidA001** [rsim/oracle-enhanced#1487]
How can I create a float field that keeps the set precision and value?

### Steps to reproduce
* Create a DB Field with a type of `Float` (i.e. `t.float :lat, null: false`)
* Create and save your object in the database (i.e. `Location.create(lat: 42.123456, lon: 120.123456)`)
* Note that the field precision changes
```
#<Location:0x007fddd8632758> {
            :id => 10000,
           :lat => 42.12345504760742,
           :lon => 120.12345886230469
```

### Expected behavior
I would expect it leaves the fields as set, or allows you to set float precision.

### Actual behavior
Float field precision is changed and rounded

### System configuration
`ruby 2.3.4p301`  `Rails 5.1.3`
`activerecord-oracle_enhanced-adapter (1.8.1)` `ruby-oci8 (2.2.4.1)`
`oracle-12c`

**Comment by koic** [comment]
Thank you for opening issue.
AFAIK, `float` is almost based on [IEEE 754 standard](https://en.wikipedia.org/wiki/IEEE_754). To keep precision, use `decimal`. The following is an example.

```ruby
t.decimal: :lat, precision: 15, scale: 6, null: false
```

Please replace `precision` and `scale` with arbitrary values.
For details, refer to Oracle documentation.
https://docs.oracle.com/database/121/SQLRF/sql_elements001.htm#SQLRF50979

Would you please try this to fix it? Thank you.

**Comment by KidA001** [comment]
That did the trick, thank you!
