### ISSUE TITLE
Basic Model.find(id) query slow

### ISSUE THREAD

**Issue by KidA001** [rsim/oracle-enhanced#1507]
I'm reviewin some of our transaction times and am seeing that Oracle is consuming a significant amount of time in our web transactions. Digging into it a bit more, basic `SomeModel.find(id)` queries are consuming the most time, which is opposite of what I'd expect.

Am I missing some configuration on our oracle db? Does oracle not use indices for ID by default? Below are some screenshots from New Relic showing the transactions

![image](https://user-images.githubusercontent.com/8673088/31002506-fcc83168-a49f-11e7-93b7-289498c90759.png)
![image](https://user-images.githubusercontent.com/8673088/31002529-17a70842-a4a0-11e7-81aa-6c14d5c0a497.png)

Our server is by no means under any heavy load, it's a AWS hosted server used by a few devs connected to an oracle DB instance.

**Rails version**:
`5.1.2`
**Oracle enhanced adapter version**:
`1.8.0`
**Ruby version**:
`2.3.4`
**Oracle Database version**:
`oracle-12c`

**Comment by yahonda** [comment]
Hi, There is almost nothing I can get from the screenshot, you will need to which SQL statement and/or which method is consuming time. 

Thanks.

**Comment by KidA001** [comment]
Here are some transaction logs, is this helpful?
```
Patient.find(10000)
   (47.3ms)  SELECT LOWER(view_name) FROM all_views WHERE owner = SYS_CONTEXT('userenv', 'current_schema')
  Sequence (14.6ms)  select us.sequence_name from all_sequences us where us.sequence_owner = 'SYSTEM' and us.sequence_name = upper('PATIENTS_seq')
  Primary Key (933.4ms)  SELECT cc.column_name FROM all_constraints c, all_cons_columns cc WHERE c.owner = 'SYSTEM' AND c.table_name = 'PATIENTS' AND c.constraint_type = 'P' AND cc.owner = c.owner AND cc.constraint_name = c.constraint_name
   (199.0ms)  SELECT cols.column_name AS name, cols.data_type AS sql_type, cols.data_default, cols.nullable, cols.virtual_column, cols.hidden_column, cols.data_type_owner AS sql_type_owner, DECODE(cols.data_type, 'NUMBER', data_precision, 'FLOAT', data_precision, 'VARCHAR2', DECODE(char_used, 'C', char_length, data_length), 'RAW', DECODE(char_used, 'C', char_length, data_length), 'CHAR', DECODE(char_used, 'C', char_length, data_length), NULL) AS limit, DECODE(data_type, 'NUMBER', data_scale, NULL) AS scale, comments.comments as column_comment FROM all_tab_cols cols, all_col_comments comments WHERE cols.owner = 'SYSTEM' AND cols.table_name = 'PATIENTS' AND cols.hidden_column = 'NO' AND cols.owner = comments.owner AND cols.table_name = comments.table_name AND cols.column_name = comments.column_name ORDER BY cols.column_id
  Patient Load (15.5ms)  SELECT  "PATIENTS".* FROM "PATIENTS" WHERE "PATIENTS"."ID" = :a1 FETCH FIRST :a2 ROWS ONLY  [["id", 10000], ["LIMIT", 1]]
```

**Comment by rsim** [comment]
It does not look good that Oracle metadata are queried for each database request. Probably you are running the application in the development mode and each request reloads all models and all Oracle metadata (columns, primary key) are reloaded on each request.

**Comment by yahonda** [comment]
I agree with Raimond's suggestion.

**Comment by KidA001** [comment]
@rsim @yahonda I'm running on an AWS server in our own environment called `develop`. The `config/environments/develop.rb` was copied from `production.rb`. Is there some config setting I'm missing for AR/Oracle?

**Comment by yahonda** [comment]
Orale enhanced adapter enables `cache_columns = true` to cache metadata when Rails.env is test or production. If you need to use non-default environment, you will need to set this value in the initializers.

https://github.com/rsim/oracle-enhanced/blob/release18/lib/activerecord-oracle_enhanced-adapter.rb#L13-L15

```ruby
          if Rails.env.test? || Rails.env.production?
            ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter.cache_columns = true
          end
```

**Comment by KidA001** [comment]
@yahonda thank you, let me update my environment and see if that makes a difference. I really appreciate your responsiveness on any issue I've posted here 🙏

**Comment by KidA001** [comment]
@yahonda @rsim Even with `cache_colums` set to `true`, I'm still experiencing latency on the first call I do on a table. All calls going forward are faster. Does the cache need to be warmed up? It seems to only be valid per instance as when I kill my rails console and go back in it does another call to the `all_tab_cols` table.

![image](https://user-images.githubusercontent.com/8673088/31093052-510f2340-a765-11e7-94be-bf53351f8b65.png)

I'm also still experiencing significant latency overall. In the past I've always worked with PSQL and haven't seen these kind of query times on `select * from table_name where ID = ? limit 1` statements.

![image](https://user-images.githubusercontent.com/8673088/31093223-e291f130-a765-11e7-9b40-f51ac928e3c3.png)

**Comment by yahonda** [comment]
This is an expected behavior of `cache_columns`. 



> In the past I've always worked with PSQL and haven't seen these kind of query times on select * from table_name where ID = ? limit 1 statements. 

For that one, unfortunately, there is no useful information I can get from your comment. I'd suggest you to take a look at `explain` for this query.

**Comment by KidA001** [comment]
Explain doesn't give that much information that seems out of the ordinary. Does my experience seem out of the ordinary in terms of response time, or is this expected?

```
irb(main):002:0> Patient.where(id: 10330).explain
  Patient Load (239.1ms)  SELECT "PATIENTS".* FROM "PATIENTS" WHERE "PATIENTS"."ID" = :a1  [["id", 10330]]
=> EXPLAIN for: SELECT "PATIENTS".* FROM "PATIENTS" WHERE "PATIENTS"."ID" = :a1 [["id", 10330]]
Plan hash value: 1018249579

--------------------------------------------------------------------------------------------
| Id  | Operation                   | Name         | Rows  | Bytes | Cost (%CPU)| Time     |
--------------------------------------------------------------------------------------------
|   0 | SELECT STATEMENT            |              |     1 |   137 |     1   (0)| 00:00:01 |
|   1 |  TABLE ACCESS BY INDEX ROWID| PATIENTS     |     1 |   137 |     1   (0)| 00:00:01 |
|*  2 |   INDEX UNIQUE SCAN         | SYS_C0010841 |     1 |       |     0   (0)| 00:00:01 |
--------------------------------------------------------------------------------------------

Predicate Information (identified by operation id):
---------------------------------------------------

   2 - access("PATIENTS"."ID"=TO_NUMBER(:A1))
```

**Comment by yahonda** [comment]
Thanks for the update. 

I just run a sample application to see how long it take to perform a simple query using `Model.where(id: n)`. It finished in `8.3ms` and explain for the same query took `4.6ms`.  

If you are not satisfied with the response time in your environment, I think most of the elapsed time differences come from some environment specific one.  Please have a look at your environment. 

```sql
irb(main):001:0> Book.where(id: 10500)
.... snip ...
  Book Load (8.3ms)  SELECT  "BOOKS".* FROM "BOOKS" WHERE "BOOKS"."ID" = :a1 FETCH FIRST :a2 ROWS ONLY  [["id", 10500], ["LIMIT", 11]]
```

```ruby
irb(main):002:0> Book.where(id: 10500).explain
  Book Load (4.6ms)  SELECT "BOOKS".* FROM "BOOKS" WHERE "BOOKS"."ID" = :a1  [["id", 10500]]
=> EXPLAIN for: SELECT "BOOKS".* FROM "BOOKS" WHERE "BOOKS"."ID" = :a1 [["id", 10500]]
Plan hash value: 2136241077
```

Here I'm running Rails in development mode, please ignore elapsed time for metadata queries.


#### Steps to get the output above:

- clone https://github.com/yahonda/diag1507

- Generate 10000 records by activerecord-import
```ruby
    books = []
    10000.times do |i|
      books << Book.new(:name => "emp_#{i}")
    end
    Book.import books
```

- Startup rails console and execute `Book.where(id: 10500)`
```ruby
$ rails c
Running via Spring preloader in process 13071
Loading development environment (Rails 5.1.4)
irb(main):001:0> Book.where(id: 10500)
   (234.0ms)  SELECT cols.column_name AS name, cols.data_type AS sql_type, cols.data_default, cols.nullable, cols.virtual_column, cols.hidden_column, cols.data_type_owner AS sql_type_owner, DECODE(cols.data_type, 'NUMBER', data_precision, 'FLOAT', data_precision, 'VARCHAR2', DECODE(char_used, 'C', char_length, data_length), 'RAW', DECODE(char_used, 'C', char_length, data_length), 'CHAR', DECODE(char_used, 'C', char_length, data_length), NULL) AS limit, DECODE(data_type, 'NUMBER', data_scale, NULL) AS scale, comments.comments as column_comment FROM all_tab_cols cols, all_col_comments comments WHERE cols.owner = 'DIAG1507' AND cols.table_name = 'BOOKS' AND cols.hidden_column = 'NO' AND cols.owner = comments.owner AND cols.table_name = comments.table_name AND cols.column_name = comments.column_name ORDER BY cols.column_id
  Book Load (8.3ms)  SELECT  "BOOKS".* FROM "BOOKS" WHERE "BOOKS"."ID" = :a1 FETCH FIRST :a2 ROWS ONLY  [["id", 10500], ["LIMIT", 11]]
   (298.5ms)  SELECT LOWER(view_name) FROM all_views WHERE owner = SYS_CONTEXT('userenv', 'current_schema')
  Sequence (29.2ms)  select us.sequence_name from all_sequences us where us.sequence_owner = 'DIAG1507' and us.sequence_name = upper('BOOKS_seq')
  Primary Key (659.1ms)  SELECT cc.column_name FROM all_constraints c, all_cons_columns cc WHERE c.owner = 'DIAG1507' AND c.table_name = 'BOOKS' AND c.constraint_type = 'P' AND cc.owner = c.owner AND cc.constraint_name = c.constraint_name
=> #<ActiveRecord::Relation [#<Book id: 10500, name: "emp_500", created_at: "2017-10-02 20:47:21", updated_at: "2017-10-02 20:47:21">]>
irb(main):002:0> Book.where(id: 10500).explain
  Book Load (4.6ms)  SELECT "BOOKS".* FROM "BOOKS" WHERE "BOOKS"."ID" = :a1  [["id", 10500]]
=> EXPLAIN for: SELECT "BOOKS".* FROM "BOOKS" WHERE "BOOKS"."ID" = :a1 [["id", 10500]]
Plan hash value: 2136241077

---------------------------------------------------------------------------------------------
| Id  | Operation                   | Name          | Rows  | Bytes | Cost (%CPU)| Time     |
---------------------------------------------------------------------------------------------
|   0 | SELECT STATEMENT            |               |     1 |   551 |     2   (0)| 00:00:01 |
|   1 |  TABLE ACCESS BY INDEX ROWID| BOOKS         |     1 |   551 |     2   (0)| 00:00:01 |
|*  2 |   INDEX UNIQUE SCAN         | SYS_C00146777 |     1 |       |     1   (0)| 00:00:01 |
---------------------------------------------------------------------------------------------

Predicate Information (identified by operation id):
---------------------------------------------------

   2 - access("BOOKS"."ID"=TO_NUMBER(:A1))
irb(main):003:0> Book.count
   (12.9ms)  SELECT COUNT(*) FROM "BOOKS"
=> 10000
irb(main):004:0>
```

#### Environment:
```
Oracle enhanced adapter 1.8.2
Rails 5.1.4
Ruby 2.4.1
Oracle Database 12.2.0.1 running on Docker
```

**Comment by KidA001** [comment]
Thanks for the example above.

Our Oracle DB is hosted on an Oracle Cloud service, where our Rails application is on AWS EB. I'm thinking the majority of our DB transaction time is due to the web transport as it's not in the same VPC as our application.

Personal question out of curiosity, how do you host your oracle DB and Rails applications? Are you keeping them in the same network? Locally I'm running Oracle in docker, but I'm not sure what license requirements I need to successfully run that container on AWS.

**Comment by yahonda** [comment]
Locating Rails server and Oracle database server in the separate cloud service could cause longer latency. 

I am maintaining this gem but do not run production Rails applications then I do not have an answer for the second question. You will get some more practical advice how to locate Rails server and database servers at stackoverflow.com or something like that.

**Comment by KidA001** [comment]
I haven't had the time to dig into this...I'm almost positive it's due to the time it takes to connect to the remote server over web since it's not on the same VPC. Before this project goes to production I'll have to take a look into it and will post what I find, but for now I'm going to close this issue.

**Comment by ioev** [comment]
We're experiencing this same exact same problem, and have mitigated it a bit by setting self.primary_key = :id on all of our models by default (It's actually set and inherited through ApplicationRecord).  This prevents this initial primary key query on selects, which takes anywhere from 400-800ms on a new connection.  

Prior to applying this fix (in production) the majority of times connections would be re-used, but the initial connect would cause the schema to load and be slow, and then future requests would have cached the schema.  However it seems like some Oracle background tasks can sometimes cause connections to be reset and renewed more frequently, which then brings our entire application to a crawl as the schema is reloaded on every request.

I should also note that setting the primary key manually also doesn't remove this particular query when saving records, so a request on a new connection to insert is slow.  This change also doesn't speed up dumping the schema, and rake db:schema:dump takes minutes to execute (which occurs every time a migration is run.)
