### ISSUE TITLE
jruby 9.1.5 + Rails 4.2.7 + JNDI + Oracle 12c release 2 + Weblogic 12c, active record object having text datatype is null

### ISSUE THREAD

**Issue by skarmakar** [rsim/oracle-enhanced#1549]
### Steps to reproduce

- Clone the project https://github.com/skarmakar/blog 
- Create a JNDI connection
- Create a war file as mentioned in the README
- deploy in Weblogic

### Expected behavior
Once application is deployed, visit http://localhost:7001/blog/posts, description should not be null

### Actual behavior
description is null. 
`text` datatype (rails migration) which is actually CLOB in the oracle db always returns null. Same result for BLOB.

### System configuration
**Rails version**:
4.2.7
**Oracle enhanced adapter version**:
1.6.9
**Ruby version**:
jruby-9.1.5.0
**Oracle Database version**:
12c release 2

**Comment by yahonda** [comment]
Thanks for the report.

Would you upgrade Oracle enhanced adapter version to 1.8.2 and Rails version to 5.1.4 
to see if it still reproduces.

If it still reproduces with Oracle enhanced adapter 1.8.2 and Rails 5.1.4, 
would you create a test case without WebLogic server environment. 

Thanks.

**Comment by skarmakar** [comment]
@yahonda I have found the issue and sent a PR https://github.com/rsim/oracle-enhanced/pull/1552 . Most likely, it will cause issues using latest version as well, as I see the code did not change much. Thanks.

**Comment by yahonda** [comment]
Thanks for the investigation. 

Looks like WebLogic wraps " Array, Blob, Clob, NClob, Ref, SQLXML, and Struct, plus ParameterMetaData and ResultSetMetaData objecs". Actually, I'd like to reduce the code to support 3rd party (non OCI, JDBC) codes as much as possible.

I have found this document to disable this wrapping at WebLogic server side.
"Weblogic 12c"

https://docs.oracle.com/cd/E24329_01/apirefs.1211/e24401/pagehelp/JDBCjdbcdatasourcesjdbcdatasourceconfigconnectionpooltitle.html

> Wrap Data Types
> 
> By default, data type objects for Array, Blob, Clob, NClob, Ref, SQLXML, and Struct, plus ParameterMetaData and ResultSetMetaData objects are wrapped with a WebLogic wrapper. This allows for features like debugging and connection usage to be done by the server.
> 
> The wrapping can be turned off by setting this value to false. This improves performance, in some cases significantly, and allows for the application to use the native driver objects directly.
> 
> MBean Attribute (Does not apply to application modules) : 
> JDBCConnectionPoolParamsBean.WrapTypes
> 
> Changes take effect after you redeploy the module or restart the server.

Would you disable this option and see if it works?

Thanks.

**Comment by skarmakar** [comment]
@yahonda Yes, this works! Thanks for this. I think this should be mentioned in readme. 
But, I am concerned, whether the gem should heavily depend on this not so obvious and optional configuration tweak.

**Comment by yahonda** [comment]
Thanks for the update.
Glad to know that disabling `JDBCConnectionPoolParamsBean.WrapTypes` works in your environment.

I understand you have some concern to change some configurations at WebLogic. But as far as this setting is valid, I prefer not to add codes to support WebLogic wrapper class into Oracle enhanced adapter. These codes would not be tested at least in my local development environment nor Travis CI.

Also, please feel free to open a pull request to README about `JDBCConnectionPoolParamsBean.WrapTypes`  setting. 

Thanks.
