### ISSUE TITLE
Order statement with NULLS LAST creates bad FIRST_VALUE statements

### ISSUE THREAD

**Issue by oakly** [rsim/oracle-enhanced#157]
If code is written like the following 

order('receipt_date desc NULLS LAST') 

there are certain conditions when the statement created includes:

FIRST_VALUE(receipt_date desc NULLS LAST) .....

regex in the distinct() method currently only matches statements with ASC or DESC if they have additional text it will all be included in the FIRST_VALUE()

---------------------------
Setup that  I believe would recreate the problem. 

class Test < ActiveRecord::Base
  has_many :items
  has_many :deliveries, :through => :items, :uniq => true
end

Sorting test.deliveries is when the problem occurs.  Adding NULLS LAST to an order statement creates the strange FIRST_VALUE statement.

**Comment by yahonda** [comment]
Closing since it has not been updated recently.
