### ISSUE TITLE
JRuby + JDBC supports Oracle 12c or higher PDB (Pluggable database) connection by default

### ISSUE THREAD

**Issue by yahonda** [rsim/oracle-enhanced#1582]
JRuby + JDBC supports Oracle 12c or higher PDB (Pluggable database) connection by default

Oracle PDB just allows service name, not Oracle SID by default.
Oracle enhanced adapter with JRuby creates the connection string like this:

```ruby
jdbc:oracle:thin:@127.0.0.1:1521:orclpdb1
```

Here `orclpdb1` is a pluggable database which can be connected via service name like this by default:

```ruby
jdbc:oracle:thin:@127.0.0.1:1521/orclpdb1
````

To workaround listener.ora at database server needs this entry.

```
USE_SID_AS_SERVICE_listener=on
```

**Comment by mskutin** [comment]
Is there any progress on this? The workaround is not helpful if you don't have control on the database server.
