### ISSUE TITLE
update_all with clob column sets value to empty_clob

### ISSUE THREAD

**Issue by mlh758** [rsim/oracle-enhanced#1588]
### Steps to reproduce
Schema:
```
create_table "formatted_texts", force: :cascade do |t|
    t.text     "content"
    t.boolean  "shared_ind", limit: nil, default: false
    t.datetime "created_at",                             null: false
    t.datetime "updated_at",                             null: false
  end
```

Column hash:
```
 @cast_type=#<ActiveRecord::Type::Text:0x007fab75aea740 @limit=nil, @precision=nil, @scale=nil>,
 @default=nil,
 @default_function=nil,
 @name="content",
 @null=true,
 @object_type=false,
 @returning_id=false,
 @sql_type="CLOB",
 @table_name="formatted_texts",
 @virtual=false>
```

In the console:
```
FormattedText.update_all(content: 'Some value')
```

### Expected behavior
I should see my string as the value.

### Actual behavior
`UPDATE "FORMATTED_TEXTS" SET "FORMATTED_TEXTS"."CONTENT" = empty_clob()`

### System configuration
**Rails version**: 4.2.8

**Oracle enhanced adapter version**: 1.6.9

**Ruby version**: 2.4.1

**Oracle Database version**: 11g

I've been going through source code for a while, I don't see any way to declare a clob myself for the insert either.

Edit: It looks like this works if I do:
```
FormattedText.update_all("content = to_clob('Some string')")
```
Is this just how we should be updating clob columns with oracle_enhanced?

**Comment by yahonda** [comment]
Hi,

http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-update_all
> This method constructs a single SQL UPDATE statement and sends it straight to the database

As `update_all` works as explained, sending a single sql update statement to the database.
However, to update LOB at Oracle database it needs to execute `empty_clob()` first.

https://github.com/rsim/oracle-enhanced/blob/f6a6acfeae4c40c47e3aa56af46a0e122b2c5352/lib/active_record/connection_adapters/oracle_enhanced/quoting.rb#L100-L101

As long as writing `to_clob` function inside the `update_all` method is working for you it should be fine.

Also, these specs show how to write lobs. 
https://github.com/rsim/oracle-enhanced/blob/master/spec/active_record/oracle_enhanced/type/text_spec.rb

**Comment by mlh758** [comment]
On that same line:
`However, values passed to update_all will still go through Active Record's normal type casting and serialization.`

I would expect to be able to safely update a text column using the hash syntax just like I can other column types, or text columns in other adapters like MySQL. I would hope it would at least throw an exception instead of just silently wiping out all my data.

**Comment by yahonda** [comment]
Unfortunately, it does not work as you expect. Sorry that you wiped out all your data but it is an expected behavior.

**Comment by mlh758** [comment]
Fortunately it was just in a CERT environment, but considering the docs say it's still supposed to be type cast I'm curious why this isn't an issue.

It's supposed to build a query and send it directly to the database, bypassing callbacks. I would expect the query built to be correct for the type still. Knowing the workaround makes this less of an issue, but it certainly seems incorrect.

**Comment by mikz** [comment]
This not only affects `update_all` but also APIs like `update_column`. I think this should raise exception instead of silently dropping data you have in the column or try to convert data using `to_clob` & friends.

**Comment by mikz** [comment]
Yes, the quoting code converts any text to empty clob.

**Comment by edlebert** [comment]
Yikes.

**Comment by edlebert** [comment]
I support this being WAD for update_all.  However, update_columns/update_column should actually update the LOB columns, I think.  They do not have the constraint of only "being one query"

**Comment by mlh758** [comment]
It's not at all clear to me how `SomeModel.update_all(column: 'value')` setting everything to an empty clob is working as designed. The documentation yohanda quoted shows that it should go through appropriate type casting. This adapter is generating a statement like `update some_models set column=empty_clob()` instead of correctly creating a statement like `update some_models set column=to_clob('value')`.

**Comment by mlh758** [comment]
Going off of the model I originally opened this issue for, I can manually run the sql:

```
update formatted_texts set content = to_clob('<p>Some new sample content in here</p>\n') where id = 13020;
```

and it changes the content from whatever it was before to that new value. FormattedText.where(id: 13020).update_all(content: '...')` should set content, or at least throw an error, instead of wiping out the value.
