### ISSUE TITLE
(ORA-12170: TNS:Connect timeout occurred)

### ISSUE THREAD

**Issue by ankita199** [rsim/oracle-enhanced#1603]
Hi,

I am using rails 5.0.2 and i am trying to connect remote oracle db with my local rails app. it continuous giving  (ORA-12170: TNS:Connect timeout occurred) error.. here are my configuration in database.yml

  adapter:  oracle_enhanced
  encoding: utf8
  pool: 5
  host: xx.xxx.x.xxx
  username: dbname
  password: dbname
  database: "//dbname/XE"

**Comment by koic** [comment]
Hm, Can you use the local sqlplus to connect to the remote Oracle server with this connection information? If not, you should first connect to the remote Oracle server with the local sqlplus.
