### ISSUE TITLE
Missing views in structure.sql

### ISSUE THREAD

**Issue by Bjoernsen** [rsim/oracle-enhanced#1624]
Currently, I try to update a Rails app (4.2) to 5.0.
Because I had some DB views, I switched from `schema.rb` to `structure.sql` (`config.active_record.schema_format = :sql`). I used migrations to create them.

When using Rails 4.2 and the oracle enhanced adapter branch `release16`, the views are present in `structure.sql` using `rake db:structure:dump`
```sql
CREATE OR REPLACE FORCE VIEW SUPER_IMPORTANT_VIEW AS …
```

When using Rails 5.0 with oracle enhanced adapter release `~> 1.7.0`, the views are not present anymore.  This brakes my CI pipeline.

Is there a way to re-enable the old behavior?

**Comment by yahonda** [comment]
Would you refer https://github.com/rsim/oracle-enhanced/issues/1339#issuecomment-3017793679 and set `structure_dump: db_stored_code` at your database.yml to see if views are generated to structure.sql

Thanks.

**Comment by Bjoernsen** [comment]
@yahonda You are my hero! I do not know why I was not able to find issue #1339 ...
