### ISSUE TITLE
Unicode Strings

### ISSUE THREAD

**Issue by mlh758** [rsim/oracle-enhanced#1626]
### Steps to reproduce
Insert a unicode string into any string column either as a literal or as a decoded string:
```
ApplicationRecord.connection.create_table(:users) do |t|
  t.string :fullname
end

class User < ApplicationRecord
end

u = User.create(fullname: '(\0e07 \0360\00b0 \035f\0644\035c \0361\00b0)\0e07')
u2 = User.create(fullname: '(ง ͠° ͟ل͜ ͡°)ง')
u.reload.fullname
u2.reload.fullname
```

### Expected behavior
One of those should yield the face

### Actual behavior
In the first case, the adapter retrieves the value exactly as it was saved without converting the characters back into viewable text. In the second case, the adapter fails to save the non-ascii values at all.

In the first case I can retrieve the values in Rails like this:
`User.select('UNISTR(users.fullname) as fullname').where(id: u.id)`

Is there a proper way to handle this in the adapter? Do I need to provide custom sql for any columns that might hold non-ascii characters such as a foreign language?

### System configuration
**Rails version**: 5.1

**Oracle enhanced adapter version**: 1.82.

**Ruby version**: 2.4.1

**Oracle Database version**: 11g

**Comment by yahonda** [comment]
Hi,

For the first case Oracle database adapter is not responsible for converting unicode encoding to characters.

For the second one I am not able to reproduce it.
https://gist.github.com/yahonda/80664ed7de2c3b8fa270ac4d8f1edcbc

Please contact with administrators to confirm Oracle database has been configured to store unicode character sets.

SQL> select parameter, value from v$nls_parameters where parameter = 'NLS_CHARACTERSET';

PARAMETER
----------------------------------------------------------------
VALUE
----------------------------------------------------------------
NLS_CHARACTERSET
AL32UTF8


SQL>

$ echo $NLS_LANG
American_America.AL32UTF8

**Comment by mlh758** [comment]
The first case was closest to correct since it actually stored the values, using `UNISTR` to retrieve the column gave the expected result. However, if you're unable to reproduce it then you're right, this is probably a configuration thing.

`NLS_CHARACTERSET: WE8MSWIN1252`

That's probably my issue right there. I had checked the `NLS_NCHAR_CHARACTERSET` which was `AL16UTF16` and thought it was correct.
