### ISSUE TITLE
Documentation of connection-string: LDAP

### ISSUE THREAD

**Issue by kingdonb** [rsim/oracle-enhanced#1631]
I've been using oracle-enhanced driver with a database that has a TNS name that comes from LDAP via settings in TNS_ADMIN through sqlnet.ora and ldap.ora, and I just created a new project... I swear I've been able to use these TNS names by specifying the DATABASE_URL as in:

`oracle-enhanced://user:pass@/tns-service`

On the latest version, this didn't work anymore.  I eventually found this:

https://github.com/rsim/oracle-enhanced#usage

```
You can also specify a connection string via the DATABASE_URL, as long as it doesn't have any whitespace:

DATABASE_URL=oracle-enhanced://user:secret@connection-string/(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=localhost)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=xe)))
```

So I connected the dots and realized that I could use the tns name as long as I include this literal `'connection-string'`.

Please add an example of this to the documentation!  It was very surprising in the old version when that `@/` worked, and it was just as surprising in the new version that now I needed to include this string literal in the place of host and port values.

I'm almost sure this can't be a very uncommon configuration, lots of people are probably using `DATABASE_URL` as it's the expected way to point at your database in a Heroku dyno, however this particular usage is basically undocumented anywhere in Oracle rubygems land.

The example:

```
DATABASE_URL=oracle-enhanced://[username]:[password]@connection-string/myoradbdev1
```

(Thank you for putting it in the spec, I'm not sure I would have figured it out otherwise!)

**Comment by kingdonb** [comment]
I'm sure that TNS and LDAP configuration are out of scope for the documentation of oracle-enhanced adapter, but in case anyone stumbles upon this issue while trying to make a Rails app with this configuration, here is a sample set of config files that we've used with our LDAP/oracle setup:

(place them in any directory and set the value of `TNS_ADMIN` environment variable to point at that location, I use /etc, many are probably using `$ORACLE_HOME/network/admin` as that appears to be the default with a full-client install)

`ldap.ora`
```
DIRECTORY_SERVERS = (oid-server-1.example.com:389:636,oid-server-2.example.com:389:636)
DEFAULT_ADMIN_CONTEXT = "dc=something,dc=example,dc=com"
DIRECTORY_SERVER_TYPE = OID
```

`sqlnet.ora`
```
NAMES.DIRECTORY_PATH = (LDAP,TNSNAMES)
```

`tnsnames.ora`
```
myoradbdev1=()
myoradbtest1=()
myoradbprod1=()
```

(The TNSNAMES setting and tnsnames.ora file are both optional, but helpful for enumerating and selecting from the databases you use most frequently in the user interface of PL/SQL Developer)

**Comment by yahonda** [comment]
Thanks for the update.  Pull requests are welcomed for better documentation.

**Comment by kingdonb** [comment]
I will put together a PR! *remindme

**Comment by kingdonb** [comment]
Wow, how handy stalebot, I just got a new macbook so had to do this configuration again today.

I will review the docs and put together a PR if it is still needed.
