### ISSUE TITLE
How to write hint in rails scope method

### ISSUE THREAD

**Issue by ghost** [rsim/oracle-enhanced#1644]
Hi this is not an issue but I didn't find answer for my problem anywhere.

In my rails model I have a `scope` method 

    class User
        scope :failed,
          :select => %{
            /*+ some hint */ *
          } ,
         :joins => :address,
         :conditions => %{
          addresses.location_id IS NULL
         }

My problem is first is this the right way of introducing `hint` in scope method and second when I run `User.failed.count` it doesn't consider the hint. Please help

**Comment by yahonda** [comment]
Hi, Thanks for using Oracle enhanced adapter.
 
As far as I know, Active Record itself does not have a feature to add SQL hints. There are some discussions and pull request https://github.com/rails/rails/issues/27110 and https://github.com/rails/rails/pull/30514 but none of them are merged. Actually, I am against for merging MySQL specific `use_index` features. 

If you really want to add some hints to your SQL statement, you will need to use raw SQL statements. I have no plan and honestly speaking no interest to add hint features to Oracle enhanced adapter.

Thanks.
