### ISSUE TITLE
warning: constant ::NativeException is deprecated

### ISSUE THREAD

**Issue by yahonda** [rsim/oracle-enhanced#1666]
### Steps to reproduce
Execute `bundle exec rake spec` with `jruby-head` 

### Expected behavior
No deprecate warnings are welcomed.

### Actual behavior

```ruby
oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb:210: warning: constant ::NativeException is deprecated
oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb:241: warning: constant ::NativeException is deprecated
oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb:384: warning: constant ::NativeException is deprecated
oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb:402: warning: constant ::NativeException is deprecated
oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb:460: warning: constant ::NativeException is deprecated
```

### System configuration
**Rails version**:master

**Oracle enhanced adapter version**:master

**Ruby version**:
jruby 9.2.0.0-SNAPSHOT (2.4.1) 2018-03-02 a480e8a Java HotSpot(TM) 64-Bit Server VM 25.151-b12 on 1.8.0_151-b12 [linux-x86_64]

**Oracle Database version**:
Oracle Database 11.2.0.1

**Comment by yahonda** [comment]
It is likely https://github.com/jruby/jruby/commit/fda488bdd891ea4e5b9f268a227c21db96d341e7 commit of https://github.com/jruby/jruby/pull/5065 triggers these `warning: constant ::NativeException is deprecated` warnings.

**Comment by jlahtinen** [comment]
https://github.com/jeremyevans/sequel/commit/4e03d342db9b609a369eaad0f3513055a8eeec96 could help

**Comment by jlahtinen** [comment]
@yahonda I think `/^java\.sql\.SQL(Recoverable)?Exception/` catches instances of `SQLException` and `SQLRecoverableException` but not i.e. `SQLTransientException`.

Should all subclasses of `SQLException` be caught now when replacing `NativeException` when `JRUBY >= "9.2"`?

All tests passes if done so.

**Comment by remofritzsche** [comment]
Will there be a Rails 5 release for this as well? I'm getting the warning with Rails 5.2 and Ruby 2.5.

**Comment by remofritzsche** [comment]
Many thanks @yahonda 🥇
