### ISSUE TITLE
[Active Record] Controlling connection timeouts 

### ISSUE THREAD

**Issue by mskutin** [rsim/oracle-enhanced#1677]
Is it possible to use the following settings in `database.yml` with `oracle_enhanced` adapter?
- `checkout_timeout`
- `connect_timeout`
- `read_timeout`
- `reaping_frequency`
- `reconnect`

Settings that works for mysql adapter:

|Option|Description|Source|Default|
|-|-|-|-|
|`pool`|This specifies the maximum number of connections to the database that ActiveRecord will maintain per server.|Native to the [ActiveRecord ConnectionPool](http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionPool.html)|[5 connections](http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionPool.html#class-ActiveRecord::ConnectionAdapters::ConnectionPool-label-Options)
|`checkout_timeout`|When making a ActiveRecord call, ActiveRecord tries to checkout a database connection from the pool. If the pool is at maximum capacity, ActiveRecord will wait for this timeout to elapse before raising an `ActiveRecord ConnectionTimeoutError` exception.| Native to the [ActiveRecord ConnectionPool](http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionPool.html) |[5 seconds ](https://github.com/rails/rails/blob/e5dc756bf9424086c403d1025971c3e704e1dcfa/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L328) |
|`connect_timeout`|If there are no available connections to the database in the connection pool, a new connection will have to be established. connect_timeout, specifies the timeout to establish a new connection to the database before failing.|Native to the [mysql2](https://github.com/brianmario/mysql2) library, passed to `libmysqlclient` as [MYSQL_OPT_CONNECT_TIMEOUT](https://dev.mysql.com/doc/refman/5.7/en/mysql-options.html)|[120 seconds](https://github.com/brianmario/mysql2/blob/a1c198ee4c8d4d32dfa79f207ec7d0524c5f7bcc/lib/mysql2/client.rb#L31)|
|`read_timeout`|Read timeout is used by the libmysqlclient library to identify whether the MySQL client is still alive and sending data. As we know that TCP sends data in chunks, the client waits for this timeout when reading from the socket, before deeming that there is an error and closing the connection.|Native to the [mysql2](https://github.com/brianmario/mysql2) library, passed to `libmysqlclient` as [MYSQL_OPT_READ_TIMEOUT](https://dev.mysql.com/doc/refman/5.7/en/mysql-options.html)|3 × 10 minutes [Source](https://dev.mysql.com/doc/refman/5.7/en/mysql-options.html)|

oracle_enhanced version:
```yml
adapter: oracle_enhanced
  reconnect: false
  database: /CDB1
  pool: 25
  reaping_frequency: 120
  connect_timeout: 5
  read_timeout: 5
  username: username
  password: password
  host: hostname
```

**Comment by yahonda** [comment]
Thanks for opening an issue. Honestly speaking I have no priority to make these timeout values configurable. Happy to review pull request but no plan to develop them by myself.

Thank you.

**Comment by mskutin** [comment]
@yahonda, this PR is meant to address the following issues:
- stuck threads when application is idle
- stuck threads for heavy load
