### ISSUE TITLE
DATE column with specifier :datetime produces ORA-01830 during UPDATE via JDBC

### ISSUE THREAD

**Issue by agungl** [rsim/oracle-enhanced#1679]
### Steps to reproduce
Create a table with an ID and a DATE column.
Specify :datetime for the DATE column attribute in the related ActiveRecord model:
_attribute :<date_column_name>, :datetime_
Manually insert a record into the table via sqlplus or any other tool.

### Expected behavior
If you retrieve the record from the DB, the value of the DATE column should contain date and time portion. If you update the attribute of the DATE column e.g. with Time.now, you should be able to save that ActiveRecord instance to the DB.

### Actual behavior
Reading (via SELECT) works as expected. When trying to save (via UPDATE) the modified data into the DB, you get:
_ActiveRecord::StatementInvalid: Java::JavaSql::SQLDataException: ORA-01830: date format picture ends before converting entire input string_

You can work around that by using _Time.now.round_ but this requires a lot of changes in existing applications. Alternatively, one could change the column type from DATE to TIMESTAMP, which is an overkill precision- and memory-wise. It would be better if the binding could respect the SQL type and skip the precision (microseconds) if DATE is used while still using the precision for TIMESTAMP.

### System configuration
**Rails version**: 5.1.5

**Oracle enhanced adapter version**: 1.8.0 (applys to 5.2.0rc1 as well)

**Ruby version**: jruby-9.1.13.0

**Oracle Database version**: 12.1.0.2

**Comment by yahonda** [comment]
Thanks for using Oracle enhanced adapter.

Would you create an executable test case to reproduce this error?
https://github.com/rsim/oracle-enhanced/tree/master/guides/bug_report_templates

Thanks.

**Comment by agungl** [comment]
Here is a testcase:

[testcase1679.txt](https://github.com/rsim/oracle-enhanced/files/1840495/testcase1679.txt)

**Comment by yahonda** [comment]
Thanks for providing a test case. I'd suggest you change `DATE` column to `TIMESTAMP` column which is default SQL type for Rails `:datetime` attribute since Rails 5.

https://github.com/rsim/oracle-enhanced#upgrade-rails-42-or-older-version-to-rails-5

Thanks you.

**Comment by agungl** [comment]
That might be okay for green field development projects. However, if you want to use Ruby to access existing DB schemas, you often can't simply change the table structures.

Until Rails 4 we could use DATE columns without problems. It's broken now, and it would be nice to have it fixed instead of telling people to use something else for their work.

**Comment by tillsc** [comment]
I also have some bigger problems introduced by this change. Did anybody find a workaround?

**Comment by codymartin2005** [comment]
In similar situation here--multiple projects sitting on legacy databases with no chance of having a schema change.

Here is what we have done to move forward though your milage may vary. We are in Rails 5.2.

Add a new file into your config/initializers with the content below. The ActiveRecord override cause the fractional seconds to be dropped and the OracleEnhanced changes forces us to use RubyDatetime for Oracle Date columns. *Note I have not tried added a new migration in yet, so you are on your own their.

`module ActiveRecord
  module ConnectionAdapters # :nodoc:
    module Quoting
    
      #stop sending the fractional seconds to the DB 
      #activerecord/lib/active_record/connetion_adapters/abstract/quoting.rb

      def quoted_date(value)
        if value.acts_like?(:time)
          zone_conversion_method = ActiveRecord::Base.default_timezone == :utc ? :getutc : :getlocal

          if value.respond_to?(zone_conversion_method)
            value = value.send(zone_conversion_method)
          end
        end

        value.to_s(:db)
      end      
    end

    class OracleEnhancedAdapter
      NATIVE_DATABASE_TYPES = {
        primary_key: "NUMBER(38) NOT NULL PRIMARY KEY",
        string: { name: "VARCHAR2", limit: 255 },
        text: { name: "CLOB" },
        ntext: { name: "NCLOB" },
        integer: { name: "NUMBER", limit: 38 },
        float: { name: "BINARY_FLOAT" },
        decimal: { name: "DECIMAL" },
        datetime: { name: "DATE" },
        timestamp: { name: "TIMESTAMP" },
        timestamptz: { name: "TIMESTAMP WITH TIME ZONE" },
        timestampltz: { name: "TIMESTAMP WITH LOCAL TIME ZONE" },
        time: { name: "TIMESTAMP" },
        date: { name: "DATE" },
        binary: { name: "BLOB" },
        boolean: { name: "NUMBER", limit: 1 },
        raw: { name: "RAW", limit: 2000 },
        bigint: { name: "NUMBER", limit: 19 }
      }
    private

      def initialize_type_map(m = type_map)
        super
        # oracle
        register_class_with_limit m, %r(date)i,           Type::DateTime
        register_class_with_precision m, %r(WITH TIME ZONE)i,       Type::OracleEnhanced::TimestampTz
        register_class_with_precision m, %r(WITH LOCAL TIME ZONE)i, Type::OracleEnhanced::TimestampLtz
        register_class_with_limit m, %r(raw)i,            Type::OracleEnhanced::Raw
        register_class_with_limit m, %r(char)i,           Type::OracleEnhanced::String
        register_class_with_limit m, %r(clob)i,           Type::OracleEnhanced::Text
        register_class_with_limit m, %r(nclob)i,           Type::OracleEnhanced::NationalCharacterText

        m.register_type "NCHAR", Type::OracleEnhanced::NationalCharacterString.new
        m.alias_type %r(NVARCHAR2)i,    "NCHAR"

        m.register_type(%r(NUMBER)i) do |sql_type|
          scale = extract_scale(sql_type)
          precision = extract_precision(sql_type)
          limit = extract_limit(sql_type)
          if scale == 0
            Type::OracleEnhanced::Integer.new(precision: precision, limit: limit)
          else
            Type::Decimal.new(precision: precision, scale: scale)
          end
        end

        if OracleEnhancedAdapter.emulate_booleans
          m.register_type %r(^NUMBER\(1\))i, Type::Boolean.new
        end
      end
    end
  end
end
`

**Comment by dhilton7** [comment]
For anyone else who encounters this issue, I've found a workaround by creating a custom Rails type to use with the `:attribute` api.
```
class OracleDateType < ActiveRecord::Type::DateTime
  # cast the value from user input (e.g. from a setter)
  # Truncate the milliseconds so that Oracle does not error out on update/insert statements
  def cast(value)
    value.is_a?(String) ? super(value) : super(value&.change(usec: 0))
  end

  # Cast the value for DB input. This is needed for date range queries that cannot accept the whole timestamp
  def serialize(value)
    value.is_a?(String) ? super(value) : super(value&.change(usec: 0))
  end
end
```
and in your model use the attribute api with custom type: `attribute :column_name, :oracle_date`

Make sure you register the custom type in an initializer file if you do this approach (more info [here](https://api.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html))
