### ISSUE TITLE
Unexpected behavior when using bind params for CHAR column

### ISSUE THREAD

**Issue by agungl** [rsim/oracle-enhanced#1680]
### Steps to reproduce
Create a table with a column of type CHAR(10) as primary key and some other columns.
Construct an ActiveRecord instance related to this table and _id = "ABC"_, then save it to the DB.
Update another attribute and _call_ save to update the record in the DB.

### Expected behavior
The existing record in the DB should get updated and reflect the change of the other attribute.

### Actual behavior
The record is not updated. The problem might be, that the parameter binding for the CHAR column uses a binding for type VARCHAR2. CHAR would be correct which blank pads the "ABC" (length = 3) to "ABC       " (length = 10). Only then the existing record would be found and updated.
Find more details about it at: https://asktom.oracle.com/pls/asktom/f?p=100:11:0::::P11_QUESTION_ID:656026400346262738
The current behavior makes working with legacy schemas containing many CHAR columns difficult.

### System configuration
**Rails version**: 5.1.5

**Oracle enhanced adapter version**: 1.8.0

**Ruby version**: jruby-9.1.13.0

**Oracle Database version**: 12.1.0.2

**Comment by yahonda** [comment]
Hi, As I have asked #1679 would you create an executable test case to reproduce it? 

Thanks.

**Comment by agungl** [comment]
Here is a testcase:

[testcase1680.txt](https://github.com/rsim/oracle-enhanced/files/1840613/testcase1680.txt)

**Comment by yahonda** [comment]
Thanks for providing the test case. As you already aware this error only reproduces if you add `CHAR` column manually. Oracle enhanced adapter maps `string` type to `VARCHAR2` sql type. 

https://github.com/rsim/oracle-enhanced/blob/f843447cdd626c295aa7d00dfd09000c7b9a3abd/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb#L333

I understand there are some cases who want to use `CHAR` but I would like to say that users who need non-default configuration will need to investigate and handle these cases by themselves. You may dig in  `bind_params` method . 

https://github.com/rsim/oracle-enhanced/blob/f843447cdd626c295aa7d00dfd09000c7b9a3abd/lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb#L311-L344

Thank you.

**Comment by agungl** [comment]
Well, as far as I understand the binding, you choose based on the type of the value the bind method. This looks strange for example in line 334 (`new_value = Java::java.sql.Timestamp.new(...)`) because you should consider the DB column type when binding. There you should not use the microseconds, because it is Time and not Timestamp. (see issue 1679)

Here, in this case, I don't see how to make a difference in the binding for CHAR and VARCHAR2 if all I have is a string variable. If I knew the DB column type, the decision were easier. Would be nice if you could provide a hint on how to implement such a solution without using CHAR hardcoded in the adapter instead of VARCHAR2.

If you work not only with databases generated by AR Migrations, you'll find CHAR and VARCHAR2 side-by-side. It would be nice if the adapter could handle that.
