### ISSUE TITLE
Wrong number of arguments

### ISSUE THREAD

**Issue by demedos** [rsim/oracle-enhanced#1695]
### Steps to reproduce
rails new app
In gemfile add 
```
gem 'activerecord-oracle_enhanced-adapter', '~> 1.8.0'
gem 'ruby-oci8' # only for CRuby users
```

### Expected behavior
Query would return the results

### Actual behavior
Database wrong argument error (:a1 / LIMIT I suppose)
```
irb(main):015:0> Item.first
  Item Load (0.0ms)  SELECT  "MY_ITEMS_TABLE".* FROM "MY_ITEMS_TABLE" ORDER BY "MY_ITEMS_TABLE"."ITEMID" ASC FETCH FIRST :a1 ROWS ONLY  [["LIMIT", 1]]
ArgumentError: wrong number of arguments (given 1, expected 0)
        from (irb):15
```

### System configuration
**Rails version**: Rails 5.1.6
**Oracle enhanced adapter version**: gem 'activerecord-oracle_enhanced-adapter', '~> 1.8.0'
**Ruby version**: ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]
**Oracle Database version**: Oracle Database 12c Release 12.1.0.1.0 - 64bit Production

**database.yml**:
```
development:
  adapter: oracle_enhanced
  database: mydb
  username: myuser
  password: mypass
```

**Comment by koic** [comment]
Thanks for opening an issue. Would you please create a reproduce script based on the following template.
https://github.com/rsim/oracle-enhanced/tree/master/guides/bug_report_templates

**Comment by demedos** [comment]
@koic I followed the instructions on the link you provided but both RSpec and Minitest fails; Here's the Minitest error

```
C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/installer.rb:174:in 
`block in ensure_specs_are_compatible!': activesupport-6.0.0.alpha requires ruby version >= 2.4.1, 
which is incompatible with the current version, ruby 2.3.3p222 
(Bundler::InstallError)
```

But even if I could manage to get those testing frameworks up and running I still woul'd know how to use them.
Would a repository with a fresh sample project be of any help?
