### ISSUE TITLE
String's default value 'N' are recognised as false

### ISSUE THREAD

**Issue by jameschenjav** [rsim/oracle-enhanced#1721]
### Steps to reproduce
1. Create a table `BARS` with column `FOO`, which type is `VARCHAR2(255)` with default value `'N'`
1. Create model `Bar`

### Expected behavior
1. `Bar.columns_hash['foo'].default` should be `'N'`
1. `Bar.new` should be `{ 'foo' => 'N' }`

### Actual behavior
1. `Bar.columns_hash['foo'].default` will be `false`.
1. `Bar.new` will be `{ 'foo' => 'f' }`. It converts `false` to string and only reserves the 1st char.

### Cause and Fix
There in a line in function `ActiveRecord::ConnectionAdapters::OracleEnhanced::SchemaStatements.new_column_from_field`:
```ruby
              # TODO: Needs better fix to fallback "N" to false
              field["data_default"] = false if (field["data_default"] == "N" && OracleEnhancedAdapter.emulate_booleans_from_strings)
```
Which `TODO` lasts there for years. 

It always converts `'N'` to boolean `false`. Several lines below will be the code to fetch type metadata. This issue could be simply fixed by fetching type first, then adding another condition whether it's boolean.

**Comment by yahonda** [comment]
Thanks for opening an issue.

I think this conversion is expected behavior if `emulate_booleans_from_strings = true`. If you do not want to convert `N` to `false`. you can set `emulate_booleans_from_strings = false`

TODO comment is not for a behavior. it was added to remember this code needs refactoring. 

Thank you.

**Comment by jameschenjav** [comment]
We have 'N' presents both boolean and status string in our db. The difference is the boolean columns are always VARCHAR2(1) and strings length > 1, which types can be recognized correctly as boolean/string. Would you like to tell me, what values of the boolean VARCHAR2(1) will be stored in db when `OracleEnhancedAdapter.emulate_booleans_from_strings = false`? Take a guess will it break any existing stored procedures? 

@yahonda 
Your reply does not help anything and sounds very rude. Would you like to tell me wth does your **FIX** mean pls? Apparently, it is a known issue. I just wanted to provide a "better fix" which I already applied to the old version for Rails 4. Since I already found the issue, I can survive without your official fix, and I don't even have to suggest you anything. Now you tell me it's not your shit? 

I had a lot of conversations with different developers. Sometimes they made me felt bad but still quite understandable: someones are just lazy, someones like to blame others, someones told me won't fix but still tried providing useful suggestions. But you are the only one denying your own known issue I don't understand why at all, even you don't get paid from oracle. If I was the boss I would switch to postgres asap.
