### ISSUE TITLE
Do not log schema statements

### ISSUE THREAD

**Issue by remofritzsche** [rsim/oracle-enhanced#1722]
### Steps to reproduce

1. Set rails log level to `:debug`
2. Do not use a schema dump
3. Load any page that involves AR

### Expected behavior

There should be no schema log statements (compared to the mysql-adapter built-in to Rails).

### Actual behavior

The schema statements are logged.

### System configuration

**Rails version**: 5.2

**Oracle enhanced adapter version**: 1.8.2 / 5.2.2

**Ruby version**: jruby 9.1.14.0 (2.3.3) 2017-11-08 2176f24 Java HotSpot(TM) 64-Bit Server VM 25.66-b17 on 1.8.0_66-b17 +jit [darwin-x86_64]

**Oracle Database version**: Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

### Solution

The solution, if I get this right, would be to use "SCHEMA" as the name for internal queries in `lib/active_record/connection_adapters/oracle_enhanced_adapter.rb`. For instance, in `column_definitions` we'd use `SCHEMA` instead of `Column definitions` as a name for the query. This causes AR's log subscriber (`activerecord/lib/active_record/log_subscriber.rb` in Rails source) to ignore these queries.

I'd open a PR but I'm not sure for which methods to change this - the enhanced adapter seems to have many more schema loading methods than i.e. the MySQL adapter so I have nothing to compare it to. Let me know if I can be of any assistance.

This is a very minor issue of course, but I just stumbled across this difference when comparing the behavior of MySQL vs. Oracle in Rails. Sorry for bugging you that often.

**Comment by yahonda** [comment]
Thanks for the information. Let me take a look at https://github.com/rails/rails/commit/37852726c93 and related information.

**Comment by yahonda** [comment]
Reminder for myself. This is the first commit introduced `SCHEMA`

**Comment by remofritzsche** [comment]
I hope this can be unstaled again ;) Thanks for having a look at this!
