### ISSUE TITLE
40 seconds timeout after numerous ORA-12545

### ISSUE THREAD

**Issue by anb555** [rsim/oracle-enhanced#1723]
_sorry, my English is very bad_
### Steps to reproduce
Connection with a fictional host in an infinite cycle

Examle database: (DESCRIPTION=(TRANSPORT_CONNECT_TIMEOUT=3)(CONNECT_TIMEOUT=3)(TCP_CONNECT_TIMEOUT=3)(RETRY_DELAY=0)(RETRY_COUNT=0)(SEND_TIMEOUT=3)(RECV_TIMEOUT=5)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=BLABLABLA)(PORT=1521)))(CONNECT_DATA=(SID=ORCL)(SERVER=DEDICATED)))

```
loop do
begin
        logger.info("#{aaa}   #{Time.now}")
        InactiveStore.establish_connection :inactive_store
        InactiveStore.connection.check
rescue => exception
...
ensure
      InactiveStore.remove_connection
end
end
```
### Expected behavior
Time for every iteration less then 1 second

### Actual behavior
first set(random 100..1000) of iterations take less then 1 second
all other iterations take **exactly 40 seconds**

in the real application between these iterations there are connections to the existing databases and to inaccessible hosts (at which there are errors ORA-12170 |ORA-12543| ORA-1254 |ORA-12609| ORA-12571 occurs), and all of them pass without delays of the exceeding CONNECT_TIMEOUT

but only at connection to the host which isn't registered in DNS has ORA-12545 and such behavior is observed.
At restart of rails the behavior repeats (there are fast iterations, then something clicks, and there are delays of exactly 40 seconds)

From where can this strange delay in 40 seconds be?

### System configuration
**Rails version**:
5.1.4
**Oracle enhanced adapter version**:
1.8.2
**Ruby version**:
2.4.2
**Oracle Database version**:
client: Client Shared Library 64-bit - 12.2.0.1.0

**as it looks**:
386   2018-05-11 17:01:55 
387   2018-05-11 17:01:55 
388   2018-05-11 17:01:55 
389   2018-05-11 17:01:55 
390   2018-05-11 17:01:55 
391   2018-05-11 17:01:56 
392   2018-05-11 17:01:56 
393   2018-05-11 17:01:56 
394   2018-05-11 17:01:56 
395   2018-05-11 17:01:56 
396   2018-05-11 17:01:56 
**397   2018-05-11 17:02:41 
398   2018-05-11 17:03:21 
399   2018-05-11 17:04:01 
400   2018-05-11 17:04:41
401   2018-05-11 17:05:21
402   2018-05-11 17:06:01
403   2018-05-11 17:06:41
404   2018-05-11 17:07:21
405   2018-05-11 17:08:01
406   2018-05-11 17:08:41
407   2018-05-11 17:09:21
408   2018-05-11 17:10:01**

**Comment by yahonda** [comment]
HI,

> but only at connection to the host which isn't registered in DNS has ORA-12545 and such behavior is observed.
At restart of rails the behavior repeats (there are fast iterations, then something clicks, and there are delays of exactly 40 seconds)

As far as I remember there is no "40 seconds" value configured in Oracle enhanced adapter.

If you are interested in timeout for connecting to the host not registered to DNS, I'd suggest you to work with more "lower" layer such as Oracle Net Services (aka SQL*Net) and/or TCP/IP. 

Thank you.
