### ISSUE TITLE
next_sequence_value is being cached by the Rails QueryCache

### ISSUE THREAD

**Issue by andynu** [rsim/oracle-enhanced#1733]
next_sequence_value queries should not be cached -- [this comment](https://github.com/rsim/oracle-enhanced/commit/18c61c8f8f23b6f6924f5ea285412cf99fe2cade#diff-5f0f777a4a68c6f18abdc0d01b253e7eL407) from the method suggests that the intention is to not cache these queries. 

This change in behavior was introduced with 18c61c8f8f23b6f6924f5ea285412cf99fe2cade which was part of a move from using this library's select_value [1] function to using active_record's version of the select_value [2] -- the latter uses the query cache.
1 ActiveRecord::ConnectionAdapters::OracleEnhancedConnection#select_value
2 ActiveRecord::ConnectionAdapters::DatabaseStatements#select_value

### Steps to reproduce
```
ApplicationRecord.connection.enable_query_cache!
a = ApplicationRecord.connection.next_sequence_value('your_oracle_sequence')
b = ApplicationRecord.connection.next_sequence_value('your_oracle_sequence')
refute_equal a, b, 'These should not be equal'
```

### Expected behavior
next_sequence_number should not be cached

### Actual behavior
next_sequence_number is being cached

### Workaround
You can wrap your calls in an `uncached` block.
```
uncached do
  ApplicationRecord.connection.next_sequence_value('your_oracle_sequence')
end
```
You could wrap the select_value call in #next_sequence_number in an uncached block. That would fix it. I'd be happy to submit a PR to that effect after I get the test environment running.

### System configuration
**Rails version**: 5.2.0

**Oracle enhanced adapter version**: 5.2.2

**Ruby version**: 2.4.0

**Oracle Database version**: 11G

Thanks! --Andy

**Comment by yahonda** [comment]
Thanks for opening an issue.

I recall Rails implemented `query_value ` method not to cache schema statement queries by https://github.com/rails/rails/pull/29634

Would you consider to open a pull request with some specs?

**Comment by andynu** [comment]
I'd be happy to, unfortunately I have been unable to replicate a test environment. It seems boxcutter.io (a dependency of the rails-dev-box) no longer exists. The reproduction steps above come from a unit test in my own project, I'm afraid that's the best I have to offer given the circumstances.

**Comment by yahonda** [comment]
Thanks for the update.
