### ISSUE TITLE
Multiline definition in tnsnames.ora 

### ISSUE THREAD

**Issue by MartinKoerner** [rsim/oracle-enhanced#1756]
### Steps to reproduce
1. define a tnsnames.ora entry with spaces and multiple lines
   - note, that the very same entry is working for sqlplus, shell or C sources on the same machine (they use the exact same tnsnames.ora)
```
# Names were switched for the ticket, but format is exactly the same
MYTEST =
  (DESCRIPTION =
    (CONNECT_TIMEOUT=5)
    (ADDRESS_LIST =
      (LOAD_BALANCE=off)
      (failover=on)
      (ADDRESS = (PROTOCOL = TCP)(HOST = my1.some_longer.host_name.com)(PORT = 1521))
      (ADDRESS = (PROTOCOL = TCP)(HOST = my2.some_longer.host_name.com)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVICE_NAME = MYTEST)
      (SERVER = DEDICATED)
    )
  )
```

2. connect to it
```
ActiveRecord::Base.establish_connection(adapter: 'oracle_enhanced',
                                        database: 'MYTEST',
                                        username: '...',
                                        password: '...' )
```
3. use it
`ActiveRecord::Base.connection.execute("SELECT 1 FROM dual")`

### Expected behavior
Query gets executed.
It works, if I remove all spaces and line breaks like so:
```
# Names were switched for the ticket, but format is exactly the same
MYTEST=(DESCRIPTION=(CONNECT_TIMEOUT=5)(ADDRESS_LIST=(LOAD_BALANCE=off)(failover=on)(ADDRESS=(PROTOCOL=TCP)(HOST=my1.some_longer.host_name.com)(PORT=1521))(ADDRESS=PROTOCOL=TCP)(HOST=my2.some_longer.host_name.com)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=MYTEST)(SERVER=DEDICATED)))
```
### Actual behavior
Exception "oci8.c:561:in oci8lib_250.so: ORA-12169: TNS:Net service name given as connect identifier is too long"

### System configuration
**Rails version**:
No rails, plain Ruby

**Oracle enhanced adapter version**:
5.2.2.

**Ruby version**:
2.5.1p57 (2018-03-29 revision 63029)

**Oracle Database version**:
`SELECT version FROM V$INSTANCE;`: 12.1.0.2.0 
TNS Ping Utility for Linux: Version 12.1.0.2.0 

I think, it might NOT be a bug in the oracle enhanced adapter, because If I copy the same entry to another machine, were all versions of ruby, adapter and oracle are the same, it works.
The question is - is there another dependency, which might be different, which I don't know of?

**Comment by yahonda** [comment]
Hi,

Would you read this document and contact Oracle customer support if you need some more help.
 https://docs.oracle.com/cd/B28359_01/server.111/b28278/net12150.htm#ORA-12150

```
ORA-12169: TNS:Net service name given as connect identifier is too long
Cause: The net service name you are attempting to resolve is too long.
Action: The maximum length of a net service name is 255 bytes; this limit has been exceeded. Use a smaller net service name. If this is not possible, contact Worldwide Customer Support.
```

Thanks.

**Comment by MartinKoerner** [comment]
Of course I read this document. The thing ist, my Service name has 3 characters and as I wrote, the same configuration is working for sqlplus and C services on the same machine (and for Ruby on other machines as well). That's why I concluded, it has to be some speciality inside the ruby access code.
