### ISSUE TITLE
Incomplete database settings leads to java.lang.NullPointerException

### ISSUE THREAD

**Issue by jlahtinen** [rsim/oracle-enhanced#1757]
### Steps to reproduce
In `config/database.yml` remove `username` or `password` configuration and then try to run specs.

### Expected behavior
Error message: "Database connection could not be established. Missing username/password."

### Actual behavior
java.lang.NullPointerException

### System configuration
**Rails version**:
5.2.0

**Oracle enhanced adapter version**:
5.2.3

**Ruby version**:
9.2.0.0

Problem is in `activerecord-oracle_enhanced-adapter-5.2.3/lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb:129` where nil is added to `java.util.Properties`. Would be better to first check that all needed properties are set and give a good error message if not.

**Comment by yahonda** [comment]
Thanks for opening an issue. To be honestly speaking I would not address myself for missing `username` and `password` cases.  Pull requests are welcomed.

Thanks.

**Comment by yahonda** [comment]
Closed since #1763 has been merged to master.
