### ISSUE TITLE
XML data type not supported

### ISSUE THREAD

**Issue by abhikur** [rsim/oracle-enhanced#1776]
### Steps to reproduce
Create a table with column type xmltype.
Insert some hash in the coulun. Now get the data from table. Data is not getting inserted not retreived
### Expected behavior
The given Hash should be insert into the table as XML. And while reteive data(XML) should come as Hash.
### Actual behavior
Data is not getting stored in the DB not retreived.
### System configuration
**Rails version**:
4.2.0
**Oracle enhanced adapter version**:
1.6.9
**Ruby version**:
2.0.0
**Oracle Database version**:
11g

**Comment by yahonda** [comment]
Thanks for opening an issue. 

As you already aware of it Oracle enhanced adapter does not support XML type. I do not think I'll implement it by myself then what I can say now is pull requests are welcomed. 

Thank you.

**Comment by abhikur** [comment]
Hi Yasuo,
Thanks for your reply. I have some code with me that adds xml_type
functionality to the adapter. I will send a pull request to your Github
repository. It will be a great help if you can see my commit and can add to
your repository.

Thanks and regards,
Abhishek (Abhikur)

>

**Comment by yahonda** [comment]
Thanks for the update. Please go ahead to open a pull request to `master` branch.
