### ISSUE TITLE
JSON::ParserError:        751: unexpected token at '' for serialized column

### ISSUE THREAD

**Issue by ajaya** [rsim/oracle-enhanced#1779]
As part of  rsim/oracle-enhanced#798, commit rsim/oracle-enhanced@4281a153b22f0df49063d6baabc503f5109c87a1 broke serialized columns marked as JSON.  If one sets the serialized column to [] or {}, then nil is written to DB.  On reload of the object, JSON parser raises exception due not being able to parse an empty string.  This happens ONLY during UPDATE phase of a record and ONLY if table has more than one column to update.

```ruby
     JSON::ParserError:
       751: unexpected token at ''
```

### Steps to reproduce
```ruby
class AddDentsToCar < ActiveRecord::Migration
  def change
    add_column :cars, :dents, :text
    add_column :cars, :lock_version, :number
  end
end
```

```ruby
class Cars < ActiveRecord::Base
  serialize :dents, JSON
end
```

Updating
```ruby
car = Car.new(dents: [])
car.save!
car.reload
car.dents # => []
car.dents = {}
car.save! # => true
car.reload # => JSON::ParserError:
```

### Expected behavior
It should save JSON serialized {} which is "{}" in db.

### Actual behavior
Saves ""

### System configuration
**Rails version**:
4.2
**Oracle enhanced adapter version**:
1.6.9
**Ruby version**:
2.4.5
**Oracle Database version**:
18.  Same problem in every oracle version

**Comment by yahonda** [comment]
Thanks for opening an issue and pull request. Would you see if it reproduces with master branch of Oracle enhanced adapter?

**Comment by yahonda** [comment]
Thanks for the update. 

I should have clearly mentioned in advance that I am maintaining `master` branch and `release52` branch but not maintaining `release18` and lower version of Oracle enhanced adapter. You may not be happy with this policy but please understand. Of course, Oracle enhanced adapter is open source software, you can apply your fixes to your branches.

Thanks again for the investigation and pull request.

**Comment by ajaya** [comment]
Understood.   Thanks for this great gem.  I will close this ticket and MR.
