### ISSUE TITLE
Long Identifiers in Oracle Database 12c Release 2 (12.2) not supported

### ISSUE THREAD

**Issue by reemanaik** [rsim/oracle-enhanced#1819]
### Steps to reproduce
Create table with name more than 30 characters
### Expected behavior
With Oracle12c release 2 i.e oracle 12.2, it should allow the names with length till 128 as the identifier length has been increased this version onwards. 
 
### Actual behavior
The table cannot be created. It gives table name length error. The table needs to be manually created instead of a migration.

### System configuration
**Rails version**: 3.2.22

**Oracle enhanced adapter version**: 1.4.3

**jRuby version**:  9.1.5.0 

**Oracle Database version**:  Oracle12c release 2 i.e oracle 12.2

**Comment by koic** [comment]
I think this issue is implemented in #1703 for Rails 6.0 (and this has not been released yet). But unfortunately it will not be backported to Rails 3.

@yahonda What do you think about that?

**Comment by koic** [comment]
@yahonda Can we close this issue?

**Comment by yahonda** [comment]
Thanks for the reminder. I'm closing this issue.
