### ISSUE TITLE
Use of Aggregate functions in Rails 3

### ISSUE THREAD

**Issue by weexpectedTHIS** [rsim/oracle-enhanced#187]
Using an aggregate function while also using ".first" in order to get the first resulting row will actually add ROWNUM <= 1 to the query, which in Oracle will limit the aggregate to only consider the first row of the table.

    Foo.select('MAX(bar)').first.attributes
    Foo Load (2.3ms) SELECT MAX(bar) FROM "FOOS" WHERE ROWNUM <= 1
    > {"max(bar)"=>2012-02-03 00:00:00 UTC}

However, if I use "[0]" instead of ".first", the aggregate is calculated using the full table and then the first row is returned.

    Foo.select('MAX(bar)')[0].attributes
    Foo Load (2.3ms) SELECT MAX(bar) FROM "FOOS"
    > {"max(bar)"=>2012-02-04 00:00:00 UTC}

I think this problem crosses the line form gotcha to bug.  Using ".first" should not ROWNUM <= 1 to the query if an aggregate function is being selected in the query.

**Comment by yahonda** [comment]
Closing since it has not been updated recently.

**Comment by weexpectedTHIS** [comment]
So you're closing it without fixing it?

**Comment by douglaslise** [comment]
You used the aggregate function in a wrong way. To achieve what you are expecting you should only use this syntax:

    Foo.maximum(:bar)
