### ISSUE TITLE
"DESC " (no table name) failed while self.abstract_class = true

### ISSUE THREAD

**Issue by mkolmar** [rsim/oracle-enhanced#1881]
### Steps to reproduce
Please refer https://github.com/rsim/oracle-enhanced/tree/master/guides/bug_report_templates
to create an executable test case

When find_by_sql is called, ActiveRecord / oracle-enhanced still try to get the structure of an empty table name when self.abstract_class = true. Something like this:

```ruby
class MyClass < ApplicationRecord
  self.abstract_class = true
  # Should not have to specify table?
  # self.table_name = 'mytable'

  def self.get_this(p1, p2)
    find_by_sql(['SELECT mycol FROM mytable JOIN another WHERE... AND EXISTS (...)', p1, p2])
  end
end
```

In other words, the goal is to have a model for a relatively complex query. Attributes are not based on one table. (The application uses third-party, legacy databases.)

### Expected behavior

Execute the raw SQL without regard for the table structure, which is what happens using SQL Server and activerecord-sqlserver-adapter 5.2.0.

Further research suggests the real purpose of self.abstract_class = true is to be able to use a table name specified in a subclass instead of the parent class -- not necessarily to have no table name.

Fundamentally, it is not clear to me whether ActiveRecord is designed to handle a model that is not tied closely enough to a single table that it should be necessary to specify a table outside raw SQL.

### Actual behavior

"DESC " failed; does it exist?

If I specify a correct table name instead of using "self.abstract_class = true", the query for table structure uses that table name and succeeds.

Using activerecord-sqlserver-adapter, when self.table_name = '_non-existent table_', nothing is logged, no error when find_by_sql is called. It does not appear that find() tries to get the table structure first in activerecord-sqlserver-adapter. Then the generated query from non-existent table fails as expected. This behavior is different from activerecord-oracle_enhanced-adapter.

### System configuration
**Rails version**:
5.2.3

**Oracle enhanced adapter version**:
5.2.5

**Ruby version**:
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]

**Oracle Database version**:
12c

**Comment by mkolmar** [comment]
SQL Server adapter returns [] (empty Array) for the description of blank table name. This seems like sensible behavior, if not standard.

One workaround is to to set self.table_name = 'DUAL'. The description is relatively inexpensive.

**Comment by yahonda** [comment]
Thanks for opening a issue. I think the workaround `set self.table_name = 'DUAL'. ` which you provided should be enough to satisfy your requirements.

**Comment by mkolmar** [comment]
The workound of `set self.table_name = 'DUAL'` does reduce the cost of #column_definitions when not needed. I do not think this is completely satisfactory.

The workaround is specific to Oracle, although it should not break other databases either when the table_name really is not used. No workaround is required with other databases that I have tested. Gem sqlite3 also behaves similarly to activerecord-sqlsever-adapter. Source code related to MySQL and Postgres look like they would behave the same in this regard. It seems that oracle_enhanced is the outlier when an exception is raised for non-existent or blank `self.table_name` for the class when find_by_sql is called.

I would suggest adding a line to these files in #describe:

`./active_record/connection_adapters/oracle_enhanced/connection.rb
./active_record/connection_adapters/oracle_enhanced/oci_connection.rb`

`return [] if name.blank?`

Or possibly to #column_definitions in:

`./active_record/connection_adapters/oracle_enhanced_adapter.rb`

`return [] if table_name.blank?`

Would such changes have any other bad effect?
