### ISSUE TITLE
OCIError - ORA-01861: literal does not match format string:

### ISSUE THREAD

**Issue by braham-shakti** [rsim/oracle-enhanced#1882]
### Steps to reproduce
I have a `Post` model having `title`,  `text`, `posted_at`, `created_at`, `updated_at` attributes, simple enough :-)

    class CreatePosts < ActiveRecord::Migration[5.2]
      def change
        create_table :posts do |t|
          t.string :title
          t.text :text
          t.date :posted_at
          t.timestamps
        end
      end
    end

Now lets create a post from `rails c`

    2.6.3 :002 > post = Post.create(:title => 'Ist post', :text => 'Ist post text', :posted_at => Date.current)

### Expected behavior
So simple, now it should create a new `post` record in `posts` table. Yeah I can see from console

    next sequence value (300.8ms)  SELECT "POSTS_SEQ".NEXTVAL FROM dual
    Post Create (610.3ms)  INSERT INTO "POSTS" ("TITLE", "TEXT", "POSTED_AT", "CREATED_AT", "UPDATED_AT", "ID") VALUES (:a1, :a2, :a3, :a4, :a5, :a6)  [["title", "Ist post"], ["text", #<OCI8::CLOB:0x000055cd75582d28>], ["posted_at", "2019-06-06"], ["created_at", "2019-06-06 08:26:00.297951"], ["updated_at", "2019-06-06 08:26:00.297951"], ["id", 1]]

### Actual behavior
Wait a second, what happened, It threw an error :-(

    Traceback (most recent call last):
    2: from (irb):2
    1: from (irb):2:in `rescue in irb_binding'
    ActiveRecord::StatementInvalid (OCIError: ORA-01861: literal does not match format string: INSERT INTO "POSTS" ("TITLE", "TEXT", "POSTED_AT", "CREATED_AT", "UPDATED_AT", "ID") VALUES (:a1, :a2, :a3, :a4, :a5, :a6))

what is that, I am not sure, It should create a new `post` in `posts` table. Why it is not creating a record?
and it is not working for update as well. Owner please help :-(

### System configuration
**Rails version**: 5.2.3

**Oracle enhanced adapter version**: 5.2.6

**Ruby version**: 2.6.3

**Oracle Database version**: 11.2.0.4

**Comment by brahamshakti** [comment]
It seems no one is interested in this issue. @yahonda do you think you can help?

**Comment by braham-shakti** [comment]
Issue seems to be related with `DATE` column. If `data_type` is `datetime` or `TIMESTAMP(6)` it works fine, I am not sure why, but in your [README.md](https://github.com/rsim/oracle-enhanced/blob/master/README.md) I saw a [note](https://github.com/rsim/oracle-enhanced#upgrade-rails-42-or-older-version-to-rails-5),  recommending to change each date column to datetime column. Is that true means it won't work with date column anymore.

**Comment by delonnewman** [comment]
I seem to be having a similar issue, but in my case the it's a field with a `date` data type that is being used to store time information also. In the model the attributes have been declared with a `:datetime` data type which worked fine in of Rails 4 but upon upgrading to Rails 5.2 we're having date formatting issues.

    # model
    class Referral
      attributes :ended_at, :datetime
    end

    # migration
    class CreateReferrals ...
      def change
        create_table :referrals do |t|
          ...
          t.date :ended_at
        end
      end
    end

    # Query
    Referral.where(id: id, referral_status_id: status_id).update_all(ended_at: Time.now)
    # throws the error 'OCIError: ORA-01830: date format picture ends before converting entire input string:'

**Rails version:** 5.2.3
**Oracle enhanced adapter version:** 5.2.6
**Ruby version:** 2.5.1

Please let me know if you'd like more details.
Thank You.
