### ISSUE TITLE
Missing sequences and tablespaces for tables in Oracle

### ISSUE THREAD

**Issue by pasku** [rsim/oracle-enhanced#1889]
I'm using this gem along with [standalone-migrations](https://github.com/thuss/standalone-migrations](https://github.com/thuss/standalone-migrations)) @thuss. I have an Oracle DB with some tables, indices and sequences. When I run **db:schema:dump**:

### Expected behavior

The schema.rb file is generated and it includes the sequences defined in the DB and the tablespaces defined for both indices and tables.

### Actual behavior

The schema.rb file is generated but it does not include the sequences defined in the DB. It includes the tablespaces defined for indices but not for tables.

### System configuration

**Oracle enhanced adapter version**: 6.0.0.rc1

**Ruby version**: 2.6.3

**Oracle Database version**: 11.2.0.4.0

**Comment by chriger** [comment]
@pasku and everyone else
I had the same issue. I want to create a custom sequence (not for primary key) in my oracle db. Set  `config.active_record.schema_format` to `:sql` and run `rake db:migrate` again. Now you have got a file called `db/structure.sql` where you have a db dump ins SQL. Rails recommend to use this format in such situations: https://edgeguides.rubyonrails.org/active_record_migrations.html#types-of-schema-dumps
