### ISSUE TITLE
group() + count() = exception

### ISSUE THREAD

**Issue by ioev** [rsim/oracle-enhanced#1899]
### Steps to reproduce
Try doing a group by and count expression.  This works fine in older versions of rails/oracle_enhanced, but it looks like there was a code change for the group by to reference the column alias and not the column itself:
https://github.com/rails/rails/commit/c9e4c848eeeb8999b778fa1ae52185ca5537fffe

This generates an OCIError: ORA-00904: invalid identifier, since aliases cannot be used in group by expressions?

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "master"
  gem "activerecord-oracle_enhanced-adapter",  github: "rsim/oracle-enhanced", branch: "master"
  gem "minitest"

  platforms :ruby do
    gem "ruby-oci8"
  end
end

require "active_record"
require "minitest/autorun"
require "logger"
require "active_record/connection_adapters/oracle_enhanced_adapter"

# Set Oracle enhanced adapter specific connection parameters
DATABASE_NAME = ENV["DATABASE_NAME"] || "dev"
DATABASE_HOST = ENV["DATABASE_HOST"]
DATABASE_PORT = ENV["DATABASE_PORT"]
DATABASE_USER = ENV["DATABASE_USER"] || "oracle_enhanced"
DATABASE_PASSWORD = ENV["DATABASE_PASSWORD"] || "oracle_enhanced"
DATABASE_SYS_PASSWORD = ENV["DATABASE_SYS_PASSWORD"] || "admin"

CONNECTION_PARAMS = {
  adapter: "oracle_enhanced",
  database: DATABASE_NAME,
  host: DATABASE_HOST,
  port: DATABASE_PORT,
  username: DATABASE_USER,
  password: DATABASE_PASSWORD
}

ActiveRecord::Base.establish_connection(CONNECTION_PARAMS)

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments << Comment.create!

    # this will raise an exception
    Comment.group(:post_id).count
  end
end
```

### Expected behavior
Shouldn't raise an Oracle exception

### Actual behavior
Does raise an exception

### System configuration
**Rails version**: master/6.0.rc1

**Oracle enhanced adapter version**: master/6.0.rc1

**Ruby version**: 2.6.3

**Oracle Database version**: 12.2

**Comment by yahonda** [comment]
Thanks for the report. I am also able to reproduce this issue. Let me have some more look at this.

**Comment by yahonda** [comment]
I have opened https://github.com/rails/rails/issues/36613 to rails/rails.

**Comment by yahonda** [comment]
rails/rails#36616 has been merged to Rails master branch and backported into 6-0-stable branch. 
I believe this issue has been addressed.
