### ISSUE TITLE
ArgumentError: Index name 'index_spree_line_items_on_order_id' on table 'spree_line_items' is too long; the limit is 30 characters

### ISSUE THREAD

**Issue by rootcfg** [rsim/oracle-enhanced#1907]
### Steps to reproduce
As user i try to install e-Commerce Spring framework on ruby ver 2.6 Rails 5.3 and Oracle 12.2.0.1. When i try todo rails db migrate, i catch exception

### Expected behavior
all migration successed

### Actual behavior
db exception
### System configuration
**Rails version**:
5.3
**Oracle enhanced adapter version**:
gem 'activerecord-oracle_enhanced-adapter', '~> 5.2.0'
**Ruby version**:
2.6
**Oracle Database version**:
12.2.0.1

**Comment by rootcfg** [comment]
Caused by:
ArgumentError: Index name 'index_active_storage_attachments_uniqueness' on table 'active_storage_attachments' is too long; the limit is 30 characters
/Users/dolgashov-ds/.rvm/gems/ruby-2.6.3/gems/activerecord-oracle_enhanced-adapter-5.2.6/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:308:in `add_index_options'
/Users/dolgashov-ds/.rvm/gems/ruby-2.6.3/gems/activerecord-oracle_enhanced-adapter-5.2.6/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:285:in `add_index'
/Users/dolgashov-ds/.rvm/gems/ruby-2.6.3/gems/activerecord-oracle_enhanced-adapter-5.2.6/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:239:in `block in create_table'
/Users/dolgashov-ds/.rvm/gems/ruby-2.6.3/gems/activerecord-oracle_enhanced-adapter-5.2.6/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:239:in `each'
/Users/dolgashov-ds/.rvm/gems/ruby-2.6.3/gems/activerecord-oracle_enhanced-adapter-5.2.6/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:239:in `create_table'
/Users/dolgashov-ds/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.3/lib/active_record/migration.rb:871:in `block in method_missing'

**Comment by rootcfg** [comment]
Google say that oracle version 12.2 allow naming up to 128 bytes.

**Comment by rootcfg** [comment]
The problem in file: 

/Users/dolgashov-ds/.rvm/gems/ruby-2.6.3/gems/activerecord-oracle_enhanced-adapter-5.2.6/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:308

just comment this records or change value:
         # if index_name.to_s.length > max_index_length
           # raise ArgumentError, "Index name '#{index_name}' on table '#{table_name}' is too long; the limit is #{max_index_length} characters"
         # end

**Comment by yahonda** [comment]
Hi, Thanks for opening an issue.

Longer identifier support is only available for Oracle enhanced adapter 6.0 https://github.com/rsim/oracle-enhanced/pull/1703 However, No plan to backport this change into Oracle enhanced adapter 5.2 or lower version of Oracle enhanced adapter.

Thanks.

**Comment by rootcfg** [comment]
Thaks!
