### ISSUE TITLE
rails 6 insert_all not working

### ISSUE THREAD

**Issue by saslani** [rsim/oracle-enhanced#1920]
### Steps to reproduce
- create a hash of objects i.e. use attributes_for
- Model.insert_all (rails 6)

### Expected behavior
Bulk insert all the rows

### Actual behavior
```
Event.insert_all(details)
ArgumentError: ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter does not support skipping duplicates
```

### System configuration
**Rails version**:
6.0 stable

**Oracle enhanced adapter version**:
gem "activerecord-oracle_enhanced-adapter", git: "https://github.com/rsim/oracle-enhanced.git", branch: "release60"

**Ruby version**:
2.6.3

**Oracle Database version**:
12c

**Comment by sandrods** [comment]
Any reason this issue got ignored? Having the same problem here and couldn't find any guidance anywhere...

**Comment by koic** [comment]
Oracle enhanced adapter implementation has not caught up with the `insert_all`, `insert_all!`, and `upsert_all` added at https://github.com/rails/rails/pull/35077. I think PR that solves the problem is welcome.

**Comment by wtholt** [comment]
Do you happen to have any updates on this feature? 

I'm on version `6.1.6` and getting the same error message. 

Has this been fixed in version 7?
