### ISSUE TITLE
When will Active Record oracle enhanced adapter 6.0.1 and 5.2.7 be gem pushed?

### ISSUE THREAD

**Issue by koic** [rsim/oracle-enhanced#1973]
Thanks for your maintenance. I looked the PR [Prepare release v6.0.2](https://github.com/rsim/oracle-enhanced/pull/1971).
OTOH, [Prepare release v6.0.1](https://github.com/rsim/oracle-enhanced/pull/1965) and [Prepare release v5.2.7](https://github.com/rsim/oracle-enhanced/pull/1967) has not been released.
https://rubygems.org/gems/activerecord-oracle_enhanced-adapter/versions

When will Active Record oracle enhanced adapter 6.0.1 and 5.2.7 be gem pushed?

**Comment by yahonda** [comment]
Short answer is no. Due to SimpleCov compatibility issue, these versions cannot be built. https://github.com/rsim/oracle-enhanced/pull/1970 removes SimpleCov. I decided to bump the version because tag v5.2.7 has been pushed.

**Comment by koic** [comment]
I get it. Thanks always!
