### ISSUE TITLE
Rails 5.1.7 / gem 1.8.2 gets undefined method 'substitute_at' for ...OracleEnhancedAdapter

### ISSUE THREAD

**Issue by matthewkrom** [rsim/oracle-enhanced#2014]
### Steps to reproduce

Save any ActiveRecord model

### Expected behavior

Save

### Actual behavior

undefined method 'substitute_at'

I see in oracle-enhanced history, some discussion of how this was removed in rails. But I am seeing this behavior still. Are there patches to the 1.8 branch that were never rolled into a gem?

### System configuration
**Rails version**: 5.1.7

**Oracle enhanced adapter version**: 1.8.2

**Ruby version**: 2.5.1

**Oracle Database version**: uncertain

**Comment by koic** [comment]
Rails 5.1 has not been maintained, also Oracle enhanced adapter 1.8 has not been maintenaned.
https://guides.rubyonrails.org/maintenance_policy.html

Please upgrade to the version Rails is maintaining. Thank you.

**Comment by matthewkrom** [comment]
OK — makes sense, will do, thank you. My best guess is that Rails 5.1.7 has breaking changes for Rails 5.1 since you tested/rolled 1.8.2 for oracle-enhanced.
