### ISSUE TITLE
sqlnet encryption

### ISSUE THREAD

**Issue by pcsgithubid** [rsim/oracle-enhanced#2058]
is oracle-enhanced adapter supports sqlnet encryption for JDBC client using DataIntegrityLevel=accepted;EncryptionLevel=accepted

**Comment by yahonda** [comment]
Thanks for opening an issue.
Oracle enhanced adapter does not support any Oracle Advanced Option security features and I have no plan to implement it by myself. If someone opens a pull request I'm happy to review them.

**Comment by yahonda** [comment]
Closing this issue.
