### ISSUE TITLE
Optimization hints radically slowing down Oracle

### ISSUE THREAD

**Issue by jacobat** [rsim/oracle-enhanced#2090]
After the optimization hints added in #2055 the following query have become much slower against our Oracle installation:

```sql
              SELECT /*+ OPTIMIZER_FEATURES_ENABLE('11.2.0.2') */ owner, table_name, 'TABLE' name_type
              FROM all_tables
              WHERE owner = '#{table_owner}'
                AND table_name = '#{table_name}'
              UNION ALL
              SELECT owner, view_name table_name, 'VIEW' name_type
              FROM all_views
              WHERE owner = '#{table_owner}'
                AND view_name = '#{table_name}'
              UNION ALL
              SELECT table_owner, table_name, 'SYNONYM' name_type
              FROM all_synonyms
              WHERE owner = '#{table_owner}'
                AND synonym_name = '#{table_name}'
              UNION ALL
              SELECT table_owner, table_name, 'SYNONYM' name_type
              FROM all_synonyms
              WHERE owner = 'PUBLIC'
                AND synonym_name = '#{real_name}'
```

The query is now running in ~4.3s whereas without the `OPTIMIZER_FEATURES_ENABLE` it runs in ~0.3s.

The problem appears to lie with the `all_synonyms` table. Running:

```sql
SELECT table_owner, table_name, 'SYNONYM' name_type FROM all_synonyms;
```
takes ~0.3s without the hint and 2-3s with the hint.

I don't know if the slowdown is caused by us having a large amount of synonyms (~13K).

Would it be possible to make the hints optional / configurable?

### System configuration
**Rails version**:
6.0.3.4

**Oracle enhanced adapter version**:
6.0.5

**Ruby version**:
2.7.2

**Oracle Database version**:
Oracle Database 19c Standard Edition 2 Release 19.0.0.0.0 - Production

**Comment by yahonda** [comment]
Thanks for the report. Let me consider that.

**Comment by yahonda** [comment]
I'd like to know if there are any other queries slowed down with `/*+ OPTIMIZER_FEATURES_ENABLE('11.2.0.2') */` hint.

**Comment by jacobat** [comment]
I tried a few of the other queries from the PR. I didn't experience any significant changes in performance between executing with the hint and without.

For instance:
```
SELECT /*+ OPTIMIZER_FEATURES_ENABLE('11.2.0.2') */ owner, table_name
            FROM all_tables;
```
With hint: 0.03 - 0.04 secs, without hints: 0.01 - 0.02 secs

```
SELECT /*+ OPTIMIZER_FEATURES_ENABLE('11.2.0.2') */ 1 FROM all_indexes i
            WHERE i.owner = SYS_CONTEXT('userenv', 'current_schema')
               AND i.table_owner = SYS_CONTEXT('userenv', 'current_schema')
               AND i.table_name = '#{table_name}'
```
Same with or without hint.

```
            SELECT /*+ OPTIMIZER_FEATURES_ENABLE('11.2.0.2') */ r.table_name to_table
                  ,rc.column_name references_column
                  ,cc.column_name
                  ,c.constraint_name name
                  ,c.delete_rule
              FROM all_constraints c, all_cons_columns cc,
                   all_constraints r, all_cons_columns rc
             WHERE c.owner = SYS_CONTEXT('userenv', 'current_schema')
               AND c.table_name = :desc_table_name
               AND c.constraint_type = 'R'
               AND cc.owner = c.owner
               AND cc.constraint_name = c.constraint_name
               AND r.constraint_name = c.r_constraint_name
               AND r.owner = c.owner
               AND rc.owner = r.owner
               AND rc.constraint_name = r.constraint_name
               AND rc.position = cc.position
            ORDER BY name, to_table, column_name, references_column
```
With hint: 0.01s, without hint 0.1s.

**Comment by rammpeter** [comment]
I recognized the same massive slowing down while selecting from All_Synonyms with OPTIMIZER_FEATURES_ENABLE('11.2.0.2').
DB is 19.3

**Comment by yahonda** [comment]
I'd like to hear some more information from users who are affected.
Please provide this information.

- Oracle Database version not just like 19c or 18c. 
I'd like to know some more detail by running
`select * from v$version`

- Are you running Oracle CDB or non CDB?

**Comment by jacobat** [comment]
Banner: `Oracle Database 19c Standard Edition 2 Release 19.0.0.0.0 - Production`
Banner full: `"Oracle Database 19c Standard Edition 2 Release 19.0.0.0.0 - Production
Version 19.7.0.0.0"`
Banner Legacy: `Oracle Database 19c Standard Edition 2 Release 19.0.0.0.0 - Production`
Con ID: `0`

Running CDB.

**Comment by scott-aveda** [comment]
check out on https://isqlplus.com/oracle/oracle-performance-tuning/

Thanks,
Scott

**Comment by yahonda** [comment]
For those who have been affected by this issue, please use this patched Oracle enhanced adapter and provide any feedback.

```ruby
gem "activerecord-oracle_enhanced-adapter", git: "https://github.com/yahonda/oracle-enhanced.git", branch: "diag_2090_release60"
```

Thank you.

**Comment by jacobat** [comment]
This version works better for me - in so far that I can now boot the Rails server. It's still somewhat slower on the first request.

The log shows me this:

Query on `diag_2090_release60`:
```
  synonyms (1764.4ms)  SELECT /*+ OPTIMIZER_FEATURES_ENABLE('11.2.0.2') */ synonym_name, table_owner, table_name FROM all_synonyms where owner = SYS_CONTEXT('userenv', 'current_schema')
```

Same query on `6.0.4`:
```
  synonyms (378.6ms)  SELECT synonym_name, table_owner, table_name FROM all_synonyms where owner = SYS_CONTEXT('userenv', 'current_schema')
```

**Comment by yahonda** [comment]
Thanks for the testing. Let me include this fix and release the newer version of Oracle enhanced adapter within a couple of days.

**Comment by jacobat** [comment]
It would be good if we could remove the hint from the query above as well. Thanks.

**Comment by yahonda** [comment]
Agreed. Updated this pull request.

**Comment by jlahtinen** [comment]
@yahonda 

I am running Version 23.4.0.24.05
I also use activerecord-oracle_enhanced-adapter 6.1.6
And jruby 9.4.12.0
And rails 6.1.x

Running

`select table_owner,
       table_name,
       'SYNONYM' name_type
  from all_synonyms
 where owner = 'PUBLIC'
   and synonym_name = 'USERS';`

takes 0.2-0.4s

while running

`select /*+ OPTIMIZER_FEATURES_ENABLE('11.2.0.2') */ table_owner,
       table_name,
       'SYNONYM' name_type
  from all_synonyms
 where owner = 'PUBLIC'
   and synonym_name = 'USERS';`

takes 0.04 - 0.09

I added line
`sql = sql.gsub(/^SELECT/i, "SELECT /*+ OPTIMIZER_FEATURES_ENABLE('11.2.0.2') */")` before https://github.com/rsim/oracle-enhanced/blob/d5b3daf8bdac7578055467329bcb6600114ea47a/lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb#L427

and `bin/rails db:schema:dump` time improved from 107s to 28s

**Comment by jlahtinen** [comment]
Could this feature be set enabled when using 23.X versions and let 19.X versions alone? Ofc better implementation is needed anyhow.
