### ISSUE TITLE
DESC teble_name failed; does it exist?

### ISSUE THREAD

**Issue by Matalo** [rsim/oracle-enhanced#21]
Hi,
I found weird behavior inside oracle_enhanced_connection.rb (version 1.3.0) file, from where i always get error mentioned in title. I looked into source code of this file at line 68, which states "if result = select_one(sql)"
before this statement I created code "puts sql" which returns SELECT statement which is about to be executed, when I run this statement inside sql developer, under same connection(user,password) as set in database.yml, I get result one line, but inside oracle_enhanced_connection.rb will return nil and cause exception from line 76.

**Comment by colepanike** [comment]
I'm seeing this error with the rails42 branch, which i switched to to solve this: https://github.com/rails/rails/issues/18739

Here's the error:

`ActiveRecord::ConnectionAdapters::OracleEnhancedConnectionException: "DESC famous_databases" failed; does it exist?`

Here's my setup:

Gemfile:

    ...
    # Oracle adapter
    gem "activerecord-oracle_enhanced-adapter", github: 'rsim/oracle-enhanced', branch: 'rails42' 
    gem "ruby-oci8"
    ....

database.yml:

    famous: 
      adapter: oracle_enhanced
      host: <IP>
      port: 1521
      database: famous
      # database: //192.168.0.25:1521/famous
      username: secret
      password: secret

The database is a legacy readonly and not the only database that will be used so I'm set up like this, but I don't think that should cause issues:

    class ArTrxHeader < FamousDatabase
    	self.table_name = :AR_TRX_HEADER

    	self.primary_key = "ARTRXHDRIDX"
    end

That inherits from:

    class FamousDatabase < ActiveRecord::Base
    	establish_connection :famous
    	# Prevent creation of new records and modification to existing records
    	def readonly?
    		return true
    	end

    	# Prevent objects from being destroyed
    	def before_destroy
    		raise ActiveRecord::ReadOnlyRecord
    	end
    end

**Comment by colepanike** [comment]
As I wrote that I found the issue. It's the inheritance. All I had to do was add: `self.abstract_class = true` to the FamousDatabase model and it worked. Should have been obvious. I'll just leave it here for anyone else who runs into the issue though.
