### ISSUE TITLE
Test failed for pull requests at step "run bug report templates"

### ISSUE THREAD

**Issue by rammpeter** [rsim/oracle-enhanced#2100]
### Steps to reproduce
Retry test of pull request  #2087

### Expected behavior
test without errors

### Actual behavior
Currently the Github test for pull request #2087 fails at step "run bug report templates" with:
/opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/bundler/gems/rails-03516a924e71/activesupport/lib/active_support/dependencies.rb:332:in `require': cannot load such file -- rspec/core/formatters/progress_formatter (LoadError)

Can this possibly be caused by commit e3c59d6 (Require `rspec/autorun` to run one line spec file) of file 
oracle-enhanced/guides/bug_report_templates/active_record_gem_spec.rb
that changed 'require "rspec"' to 'require "rspec/autorun"' ?

**Comment by yahonda** [comment]
#2102 has been merged to master branch then CI should work.

**Comment by rammpeter** [comment]
pull request checks are successful
