### ISSUE TITLE
Oracle 19c

### ISSUE THREAD

**Issue by scott-aveda** [rsim/oracle-enhanced#2105]
Is it possible to setup a test Oracle RAC ASM env on 2 Microsoft Hyper-v VMs using Vagrant?

I have setup Oracle Database 19c RAC On Oracle Linux 7 Using Vagrant following https://isqlplus.com/oracle/installation/oracle-database-19c-rac-on-oracle-linux-7-using-vagrant/

https://isqlplus.com/
and was hoping this could also be done with Microsoft Hyper-V.

Thanks,
Scott

**Comment by yahonda** [comment]
Thanks for opening an issue. This topic is not related to Oracle enhanced adapter, then let me close this issue. Please contact somewhere right place.
