### ISSUE TITLE
[v1.4.3] Add support for ENV variables

### ISSUE THREAD

**Issue by coding-bunny** [rsim/oracle-enhanced#2127]
### Steps to reproduce
Attempt to setup a DB in a CI system

### Expected behavior
I'd expect the rake task to take/respect environment variables.

### Actual behavior
The line is hard-coded to ask for a value using stdin

### System configuration
**Rails version**: 3.2.12

**Oracle enhanced adapter version**: 1.4.3

**Ruby version**: 1.9.3

**Oracle Database version**: 12.10

## Notes

Basically instead of using https://github.com/rsim/oracle-enhanced/blob/v1.4.3/lib/active_record/connection_adapters/oracle_enhanced.rake#L22 would it be possible to read out the correct ENV variable? E.g `ORACLE_SYSTEM_PASSWORD` ?

**Comment by yahonda** [comment]
Thanks for opening an issue. This feature has been available since Oracle enhanced adapter 1.5.6 via https://github.com/rsim/oracle-enhanced/pull/529 and I have no plan to maintain 1.4.x now.  If you need this feature you can apply monkey-patch by yourself or upgrade to the newer version of the Oracle enhanced adapter.

**Comment by coding-bunny** [comment]
Can I use the newer version on Rails 3.2 and ruby 1.9?

**Comment by koic** [comment]
No, Rails also needs to be upgraded to use newer Oracle enhanced adapter. e.g.:

- Rails 3.2 / Oracle enhanced adapter adapter 1.4
- Rails 4.0 / Oracle enhanced adapter adapter 1.5
- Rails 4.1 / Oracle enhanced adapter adapter 1.5
- Rails 4.2 / Oracle enhanced adapter adapter 1.6
- Rails 5.0 / Oracle enhanced adapter adapter 1.7
(snip)
- Rails 6.1 / Oracle enhanced adapter adapter 6.1

Please see the documents below for combination details.
https://github.com/rsim/oracle-enhanced#installation

**Comment by coding-bunny** [comment]
Then upgrading is not an option right now :/
I've gotten around it using Rake task hooks and overwriting the task defined by the adapter, which works. and is good enough for now.
