### ISSUE TITLE
Record save error after upgrade Rails 5.2 to Rails 6.0 and adapter ver. 5.2.8 to 6.0.4

### ISSUE THREAD

**Issue by JenniferMB** [rsim/oracle-enhanced#2131]
### Steps to reproduce
Performed recommended actions to upgrade application gems for Rails to 6.0 and OracleEnhancedAdapter to 6.04.
Ran rails update utility and applied recommended changes.
Application launches successfully, browse and update transactions perform as expected, create transactions fail on submit.

### Expected behavior
Record should save

### Actual behavior
Action Controller Exception: NoMethodError in TicketsController#create
undefined method 'ArgumentError' for #<ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter:0x00007f5a74135580>
at statement:
`if @ticket.save!`

### System configuration
**Rails version**: 5.2.3 to 6.0.3.4

**Oracle enhanced adapter version**: 5.2.8 to 6.0.4

**Ruby version**: 2.6.2

**Oracle Database version**: 12c

**Comment by koic** [comment]
Thank you for the feedback.
Can you provide an executable test case to reproduce this error? The following is bug report templates:
https://github.com/rsim/oracle-enhanced/tree/master/guides/bug_report_templates

**Comment by JenniferMB** [comment]
I would like to, very much, but my environment is isolated and github access is expressly forbidden. I'm sure you can understand the challenge of maintaining an application under these conditions. Is there any insight you might be able to provide? I will endeavor to provide a test case, but it may take some time to obtain organizational approvals for access.

I understand there may not be much you can advise under these circumstances, I just hoped there might be a well known solution based on my description of the problem.

Thank you for your assistance.

**Comment by JenniferMB** [comment]
I have found a way to identify the error being thrown, it is 'Trigger based primary key is not supported'. It is true that I have set the sequence name to :autogenerated in my models which was the accepted solution in Rails 5.2 and activerecord-oracle_enhanced-adapter 5.2.8.

Do I have to make a different kind of configuration to my Rails application so that it allows the sequence numbering to be managed by the database?

**Comment by koic** [comment]
> I have found a way to identify the error being thrown, it is 'Trigger based primary key is not supported'. It is true that I have set the sequence name to :autogenerated in my models

#1669 changes seem to be affecting. It seems good to ask lead maintainer and the PR author @yahonda.

**Comment by JenniferMB** [comment]
> I have found a way to identify the error being thrown, it is 'Trigger based primary key is not supported'. It is true that I have set the sequence name to :autogenerated in my models

> #1669 changes seem to be affecting. It seems good to ask lead maintainer and the PR author @yahonda.

This appears to be the answer. It is consistent with the result I saw when I removed :autogenerated from the sequence name when performing a simple insert on a single table.

Thank you for finding a way to help me, even in the absence of bug report diagnostics.
