### ISSUE TITLE
OCIError: ORA-01935: missing user or role name

### ISSUE THREAD

**Issue by pandu-49** [rsim/oracle-enhanced#2132]
### Steps to reproduce
I recently upgraded my project rails version to `rails 6.1.1` and `activerecord-oracle_enhanced-adapter` to `6.1.1`. I'm getting error while running database tasks `bundle exec ./bin/rails db:environment:set db:reset` or `bundle exec rake db:create`. I found that https://github.com/rsim/oracle-enhanced/blob/v6.1.1/lib/active_record/connection_adapters/oracle_enhanced/database_tasks.rb#L22 is trying to get config data from string keys which is not available in 6.1.1. Available config is like below 
`{:adapter=>"oracle_enhanced", :username=>"username", :password=>"passwd", :statement_limit=>250, :database=>"host/xepdb1"}`. It must be required to change the way we accessing the config in database tasks.

### Expected behavior
The database tasks should read the config in a right way so they will run as earlier.

### Actual behavior
The database tasks are throwing an error - OCIError: ORA-01935: missing user or role name

### System configuration
**Rails version**: 6.1.1

**Oracle enhanced adapter version**: 6.1.1

**Ruby version**: 2.7.2

**Oracle Database version**: 12

**Comment by yahonda** [comment]
Close via #2135
