### ISSUE TITLE
With rails 6.1.1 jndi connection fails if driver is not set

### ISSUE THREAD

**Issue by jlahtinen** [rsim/oracle-enhanced#2139]
oracle-enhanced adapter tries to set driver to oracle.jdbc.driver.T4CConnection when jndi is used.

this fails with rails 6.1.1 with error

    FrozenError (can't modify frozen Hash):
    
    org/jruby/RubyHash.java:1053:in `[]='
    activerecord-oracle_enhanced-adapter (6.1.1) lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb:101:in `new_connection'

Works with rails 6.1.0

A workaround is to set driver in file config/database.yml

**Comment by koic** [comment]
Thank you for the feedback.
Can you provide an executable test case to reproduce this error? The following is bug report templates:
https://github.com/rsim/oracle-enhanced/tree/master/guides/bug_report_templates

**Comment by koic** [comment]
Additional information. Current JRuby stable version (9.2) does not work with Rails 7.0.0.alpha (edge). So it need to specify the stable branch for Rails 6.1.

```diff
 # frozen_string_literal: true

 require "bundler/inline"

 gemfile(true) do
   source "https://rubygems.org"

   git_source(:github) { |repo| "https://github.com/#{repo}.git" }

-  gem "rails", github: "rails/rails", branch: "main"
-  gem "activerecord-oracle_enhanced-adapter",  github: "rsim/oracle-enhanced", branch: "master"
+  gem "rails", github: "rails/rails", branch: "6-1-stable"
+  gem "activerecord-oracle_enhanced-adapter",  github: "rsim/oracle-enhanced", branch: "release61"
   gem "minitest"

   platforms :ruby do
     gem "ruby-oci8"
   end
 end

(snip)
```

https://github.com/rsim/oracle-enhanced/pull/2136#issuecomment-773842219

**Comment by jlahtinen** [comment]
https://github.com/jlahtinen/oracle-enhanced/commit/fbc4d68b2b2b38695b09fd4870e8ba604fe7af66

Service, user and password is in context.xml, not read from ENV ...

You can download needed jars with `mvn dependency:copy-dependencies -DoutputDirectory=lib`. I added ojdbc driver to lib folder manually.

**Comment by jlahtinen** [comment]
@koic is something still missing?

**Comment by yahonda** [comment]
Thanks for providing the test case. Somehow I'm not able to reproduce it.

```ruby
$ jruby -v
jruby 9.2.14.0 (2.5.7) 2020-12-08 ebe64bafb9 OpenJDK 64-Bit Server VM 25.282-b08 on 1.8.0_282-8u282-b08-0ubuntu1~20.10-b08 +jit [linux-x86_64]

$ jruby active_record_gem_spec.rb
NameError: missing class name (`hthurow.tomcatjndi.TomcatJNDI')
  method_missing at org/jruby/javasupport/JavaPackage.java:252
          <main> at active_record_gem_spec.rb:9
$
```

Based on the `FrozenError (can't modify frozen Hash):` message, I've made a quick dirty commit. 
Would you test if this branch addresses this issue?


```ruby
gem "activerecord-oracle_enhanced-adapter" git: "https://github.com/yahonda/oracle-enhanced", branch: "diag_2139"

**Comment by jlahtinen** [comment]
You need libraries described in pom.xml + ojdbc driver (could be added to pom.xml also ...)

They can be downloaded with `mvn dependency:copy-dependencies -DoutputDirectory=lib`

**Comment by jlahtinen** [comment]
[diag_2139](/yahonda/oracle-enhanced/tree/diag_2139) seems to fix this. Test passes.
