### ISSUE TITLE
support for function based default values needed

### ISSUE THREAD

**Issue by areman** [rsim/oracle-enhanced#214]
Hi,

if a new ActiveRecord object is created the default value of the columns will be copied into the attributes of the ActiveRecord objects. But what about default columns which based on a function like sysdate ? This column can't be stored in the attributes because the value will be calculated in insert. 
My Idea is a simple enhancement, if the value of a ActiveRecord attribute is nil and the column is not nullable and the column has a default value use the Default keyword for the DML statement.
Here my code patch for this solution

```ruby
module ActiveRecord
  module ConnectionAdapters
  
    class OracleEnhancedColumn
      
      alias_method :initialize_without_default, :initialize
      
      def initialize(name, default, sql_type = nil, null = true, table_name = nil, forced_column_type = nil) #:nodoc:
    
        @default_present = default.present?   
        initialize_without_default( name, default, sql_type, null, table_name, forced_column_type )
      end
      
      def default_present?
        @default_present
      end
      
    end

    class OracleEnhancedAdapter
      
      alias_method :quote_without_default, :quote
      
      def quote(value, column = nil) #:nodoc:
        
        if not value and column and column.default_present? and not column.null
          'DEFAULT'
        else
          quote_without_default( value, column )
        end
    
      end
      
    end

  end
end
```

is it possible to include something like this in the next release ?

Regards,
André

**Comment by yahonda** [comment]
Closing since it has not been updated recently.
