### ISSUE TITLE
OCIError: ORA-00907  missing right parenthesis where lock => true

### ISSUE THREAD

**Issue by pickerel** [rsim/oracle-enhanced#223]
I got error when run the script 
BrwTask lock.where(:status => 1).order("priority desc, id").first

 failed: (OCIError: ORA-00907: 缺失右括号: SELECT * FROM (SELECT  "BRW_TASKS".* FROM "BRW_TASKS"  WHERE "BRW_TASKS"."STATUS" = 0 ORDER BY priority desc, id FOR UPDATE) WHERE ROWNUM <= 1
stmt.c:253:in oci8lib_191.so

when i change it to 
BrwTask lock.where(:status => 1).order("priority desc, id").take(1).first,  everything is ok.

**Comment by yahonda** [comment]
Closing since it has not been updated recently.
