### ISSUE TITLE
Feature Request: rake db:test:prepare for environments other than :test

### ISSUE THREAD

**Issue by jspooner** [rsim/oracle-enhanced#230]
My team uses MySQL for :development and :test environments but the integration and production environments use Oracle.  I recently set up CI with Jenkins and created a new env for testing with Oracle.  Since this env is named :jenkins `rake db:test:prepare` doesn't run the special oracle drop user command :(

I made this change below to fit our specific situation.  If other people have this problem and you have a cleaver ideas around this issue I'd be happy to make submit a patch.

https://github.com/jspooner/oracle-enhanced/compare/patch-1

**Comment by yahonda** [comment]
Closing since it has not been updated recently.
