### ISSUE TITLE
Can we expect a new release

### ISSUE THREAD

**Issue by rammpeter** [rsim/oracle-enhanced#2311]
Hi,
This is only a question. 
Do you have a plan when to expect the next release of this exciting adapter?
This question comes especially regarding #2284. 
Thanks
Peter

**Comment by yahonda** [comment]
Hi, #2284 implements new features, and there is no plan to backport this change to Active Record Oracle enhanced adapter 7.0.z, which will be available once Oracle enhanced adapter 7.1 to support Rails 7.1

**Comment by rammpeter** [comment]
Thanks for the information and good luck for 7.1
