### ISSUE TITLE
Question: Will you support JDBC Reactive Extensions?

### ISSUE THREAD

**Issue by stackmystack** [rsim/oracle-enhanced#2315]
Hello,

Are you planning on supporting [Reactive Extensions](https://docs.oracle.com/en/database/oracle/oracle-database/21/jjdbc/jdbc-reactive-extensions.html#GUID-1C40C43B-3823-4848-8B5A-D2F97A82F79B)?

**Comment by yahonda** [comment]
Thanks for opening an issue here.
I have no plan to add JDBC driver-specific features. 
Please feel free to open a pull request if necessary.
