### ISSUE TITLE
Incorrectly dumping computed indexes in schema

### ISSUE THREAD

**Issue by milaniliev** [rsim/oracle-enhanced#232]
Hi Raimonds,

It seems like oracle_enhanced, which we love and use daily, has a small bug when dumping a database schema. 

An index named "INDEX_DATE" defined as TRUNC(DATE_COLUMN) gets dumped as:

create index "INDEX_DATE" "TRUNC(DATE_COLUMN)", which of course crashes. 

It seems it should output "INDEX_DATE" TRUNC(DATE_COLUMN).

Is there anything you can do about this, or should I try and hack this and submit a pull request if I manage?

Thanks so much,
Milan Iliev

**Comment by yahonda** [comment]
Closing since it has not been updated recently.
