### ISSUE TITLE
Remove the OPTIMIZER_FEATURES_ENABLE in schema_dumper.rb for version 6

### ISSUE THREAD

**Issue by santosral** [rsim/oracle-enhanced#2416]
### Steps to reproduce
The OPTIMIZER_FEATURES_ENABLE was already removed for v7

### Expected behavior
Remove the OPTIMIZER_FEATURES_ENABLE in schema_dumper.rb

### Actual behavior
Slow schema generation

### System configuration
**Rails version**: 6.1

**Oracle enhanced adapter version**: v6.1.6

**Ruby version**: 3.1

**Oracle Database version**: 19

**Comment by yahonda** [comment]
Hi, We do not backport changes to lower versions of Oracle enhanced adapter.
