### ISSUE TITLE
Table and column comments do not appear in schema or structure dump.

### ISSUE THREAD

**Issue by juanitogan** [rsim/oracle-enhanced#259]
Any hope of getting table and column comments in the schema and/or structure dumps soon?  Or did I miss something?  I can add comments to the migration (thank you to oracle_enhanced) but lose them with the dumps.  Without this feature I will have to stop using migrations and will have to use something else to manage the data model.  Table and column comments are an extremely important part of our documentation.

**Comment by kodram** [comment]
:+1:

**Comment by AgeevAndrew** [comment]
:+1:

**Comment by yahonda** [comment]
#734 has been merged to master.
