### ISSUE TITLE
Encoding issues - jruby 1.7.1 on Windows - incompatible character encodings: UTF-8 and Windows-1252

### ISSUE THREAD

**Issue by rajesh-jangam** [rsim/oracle-enhanced#261]
Hi,

We are trying to use jruby 1.7.1  (rails 3.2.6) to work with oracle database.
Applications internal, external and System encoding shows:
```ruby
irb(main):001:0> ____ENCODING____
=> #<Encoding:Windows-1252>
irb(main):002:0> Encoding.default_internal
=> #<Encoding:UTF-8>
irb(main):003:0> Encoding.default_external
=> #<Encoding:UTF-8>
irb(main):004:0>
```

We get the following error while rendering templates:

```ruby
ActionView::Template::Error (incompatible character encodings: UTF-8 and Windows-1252):
```

We tried to use oracle_enhanced adapter version 1.4.2.rc1, but no help.
Finally, after some deep dive, we were able to work-around by overriding the method:
get_ruby_value_from_result_set(rset, i, type_name, get_lob_value = true)

Here, we encoded the string type data to UTF before returning it to the caller.
when :VARCHAR2, :CHAR, :LONG, :NVARCHAR2, :NCHAR
          rset.getString(i).try(:encode, 'UTF-8')

This has temporarily resolved the problem for us.
Atleast now it does not give this error, but it still does not show the characters properly in the UI (shows "??????").

But, this works well with the postgresql database/adapter. So, i was not sure if this was a jruby issue.
Thus, i have posted it for this adapter. 

Thanks in advance!

**Comment by yahonda** [comment]
Closing this since there was a solution provided but no updates since that.
