### ISSUE TITLE
ORA-00904 Error - Update to NCLOB type field fails

### ISSUE THREAD

**Issue by hermiti** [rsim/oracle-enhanced#272]
When attempting to update a NCLOB field value a ORA-00904 error is thrown as Oracle does not understand "empty_nclob()".  It looks like the exceptions that were implemented to solve this error with CLOB and BLOB were not implemented for NCLOB.  Below is the link regarding the patch to Rails back in 2007:

http://blog.rayapps.com/2007/08/30/rails-patch-for-oracle-clob-defaults/

Based on the patch the following would not evaluate correctly as it would not catch empty_nclob():

*row['data_default'] = nil if row['data_default'] =~ /^(null|empty_[bc]lob\(\))$/i*

*(some characters were escaped by github)*

Here is the resulting sample error:

*ActiveRecord::StatementInvalid: OCIError: ORA-00904: "EMPTY_NCLOB": invalid identifier: UPDATE "COBRA"."COB_NTX" SET "NOTE_TEXT" = empty_nclob() WHERE "COBRA"."COB_NTX"."FK_ID_CHAR" = N'01.01.01.01.01' from stmt.c:230:in oci8lib_191.so*

This error was generated in active-oracle_enhanced-adapter version (1.4.2.rc1) and ruby-oci8 (2.1.4), Oracle DB was 11g - 11.2.0.3.0 - 64bit.

**Comment by yahonda** [comment]
Closing due to recent inactivity.
