### ISSUE TITLE
Loading issue: rake tasks not loaded in test environment

### ISSUE THREAD

**Issue by jgracin** [rsim/oracle-enhanced#305]
Hi!

I'm using activerecord-oracle_enhanced-adapter 1.4.2 with rails 3.2.13, and ruby 1.9.3.  I'm trying to run my application tests using Oracle DB but I keep getting an error which indicates that oracle_enhanced.rake tasks are not loaded, or at least not loaded after rails.  

When calling 'rake db:test:purge', the default task from activerecord gets called instead of the one defined in active_record/connection_adapters/oracle_enhanced.rake.

If I add an explicit 'require activerecord-oracle_enhanced-adapter' to the Rakefile of the project, and I add the following line:

load 'active_record/connection_adapters/oracle_enhanced.rake'

within ActiveSupport.on_load(:active_record) block (in activerecord-oracle_enhanced-adapter.rb), everything works.

What could be the problem?

Here's a log of running rake:

$ rake db:test:purge --trace
[... some probably irrelevant stuff deleted ...]
** Execute environment
"Database adapter oracle_enhanced not supported. Use:\nForeigner::Adapter.register 'oracle_enhanced', 'path/to/adapter'"
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:test:purge
rake aborted!
Task not supported by 'oracle_enhanced'
/home/.../.rvm/gems/ruby-1.9.3-p385@gset/gems/activerecord-3.2.13/lib/active_record/railties/databases.rake:551:in `block (3 levels) in <top (required)>'

**Comment by yahonda** [comment]
Closing since this error is out of scope from Oracle enhanced adapter code base.
