### ISSUE TITLE
json serialization broken when text type (clob) is used

### ISSUE THREAD

**Issue by ovesh** [rsim/oracle-enhanced#315]
Consider the following migration:

```
add_column    :items, :json_list, :text
```

and the following model:
```
class Item < ActiveRecord::Base
  serialize :json_list, JSON
end
```

When attempting to save the model, like this:
```
p = Item.first
p.json_list = ["hello"]
p.save
```

The following sql is executed (excerpt):
```
UPDATE "ITEMS" SET "WARNING_LIST" = empty_clob() WHERE....
```

Then, calling
```
Item.all
```

causes this error:
```
JSON::ParserError: 795: unexpected token at '---
- hello
'
```

The record was serialized as YAML 

This doesn't occur when the type is a string.

**Comment by yahonda** [comment]
I think #591 addresses similar issues. Please reopen if it still reproduces using the latest version of Oracle enhanced adapter.
