### ISSUE TITLE
db:test:clone_structure task fails because it doesn't call db:test:load_structure

### ISSUE THREAD

**Issue by abeger** [rsim/oracle-enhanced#326]
Here's the original rake task for db:test:clone_structure in ActiveRecord:

````ruby
task :clone_structure => [ "db:structure:dump", "db:test:load_structure" ]
````

This is the same task in [oracle_enhanced.rake](https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced.rake), line 82:
````ruby
redefine_task :clone_structure => [ "db:structure:dump", "db:test:purge" ] do |existing_actions|
````

db:test:load_structure got dropped at some point. As a consequence, all test runs via rake destroy the test database but don't rebuild it.

**Comment by yahonda** [comment]
#402 removes this task from Oracle enhanced adapter. Then closing this issue.
