### ISSUE TITLE
Time Zone versus DATE datatype

### ISSUE THREAD

**Issue by juanitogan** [rsim/oracle-enhanced#328]
Please document use of TZ (and other time zone use and correction) better for us noobs.

No matter what I was doing, my time data was storing in the database in DATE columns as UTC instead of EST or any other time zone.  I fiddled with ENV['TZ'].  I fiddled with setting TZ in the OS.  I fiddled with time_zone in database.yml.  I fiddled with config.time_zone in application.rb.  I fiddled with set_datetime_columns.  I checked the app server and db server time zones many times.  I asked around.  Nothing.  What it finally came down to after much digging was that I needed to add this to application.rb:

``` ruby
config.active_record.default_timezone = :local
```

Apparently, :utc is the default on my installation and not :local for some reason (as opposed to what the Rails doc says).

TZ was a big red herring.  I commented out the ENV['TZ'] line and it makes no difference either way in my particular setup.  Regardless, some more info and examples on how to use TZ would be nice because I wasn't sure which of the following would be correct considering I have Ruby running on Linux on one server and Oracle running on AIX on another server:

ENV['TZ'] = 'EST'
ENV['TZ'] = 'EDT'
ENV['TZ'] = 'US/Eastern'
ENV['TZ'] = 'Eastern Time (US & Canada)'
ENV['TZ'] = 'UTC -04:00'
ENV['TZ'] = 'GMT-04:00'

Thanks,

Matt

**Comment by ericschoville** [comment]
Thanks, Matt.  You ended a bunch of frustration.

**Comment by juanitogan** [comment]
Thanks, Eric.  It is always good to know when my effort to share something actually helps somebody else save some time and misery.  It makes the pain I went through more worth it.  I think we were live in production for a year before I had a chance to hunt down this obscure config setting that is not included in the generated code (and that the regular developers gave up trying to solve and kept trying to fake).  I makes me consider designing databases to only store UTC (if given the option) and/or timestamps and not date types.

**Comment by yahonda** [comment]
Thanks for reporting. Since Rails 4 `default_timezone = :utc` is default. 
https://github.com/rails/rails/pull/4573

Closing this issue since https://github.com/rsim/oracle-enhanced/blob/master/README.md#adapter-settings explains this ENV environment variables.

**Comment by juanitogan** [comment]
I see no improvement to the documentation regarding how to handle DATE columns and whatever TZ is good for.  `:utc` being default is the primary frustration with DATE columns, not the fix.

But I don't use ActiveRecord anymore (thankfully) so I'll let someone else reopen this if they agree all this could be explained and documented much better.
