### ISSUE TITLE
Legacy with rails4 branch 'changed' issue

### ISSUE THREAD

**Issue by lustremedia** [rsim/oracle-enhanced#367]
I have a legacy table with a column name `changed` which is reserved by ActiveRecord 

`ActiveRecord::DangerousAttributeError in Events#show`
`changed is defined by Active Record`

How can I tell oracle enhanced adapter to use a different name for that column name?

Is there something like `self.column_name changed,  AS othername`

It would also be good to have this in the legacy documentation if it exists ...

**Comment by yahonda** [comment]
Closed.
