### ISSUE TITLE
OCIError: ORA-01858: a non-numeric character was found where a numeric was expected

### ISSUE THREAD

**Issue by sw779** [rsim/oracle-enhanced#396]
I'm trying to perform a simple query on an Oracle view but getting this error.

<b>OCIError: ORA-01858: a non-numeric character was found where a numeric was expected</b>

I'm told this line in the view is causing the problem. It is using an NVL on an outer join. If this line is removed from the view query, it works...

<b>AND TRUNC (SYSDATE) BETWEEN xoh.date_from(+)
                                      AND          NVL (xoh.date_to(+), '31-DEC-4712')</b>

The query executes in SQL Developer, so I'm assuming either I've done something wrong in my Rails app or the gem has issues with NVLs on outer joins?

For info, I have a single model for the view (referenced using self.table_name). I'm attempting queries such as .first, .all, where etc with the same result.

**Comment by malav-rirev** [comment]
@sw779 how did you changed the date format?
