### ISSUE TITLE
only on first 3 attempts, then it works. OCIError: ORA-12545: Connect failed because target host or object does not exist

### ISSUE THREAD

**Issue by ctroncoso** [rsim/oracle-enhanced#408]
Using:
Ruby 2.0.0
OCI8::VERSION  --->"2.1.6"
activerecord-oracle_enhanced-adapter 1.5.1
activerecord 4.0.2

Regular initialize procedure:

    require 'active_record'
    require 'activerecord-oracle_enhanced-adapter'
    ActiveRecord::Base.establish_connection(
	:adapter => "oracle_enhanced", 
	:database => "xxx.xxx.xxx.xxx:1521/Sd",
	:username => "user",
	:password => "passt"
    )
    ActiveRecord::Base.pluralize_table_names = false

    class All_tables < ActiveRecord::Base; end;

Executing this next line in PRY render the title error ONLY the first 2 or 3 attempts. After giving it a few seconds, it works.

    pry(main)> Admision.take
    OCIError: ORA-12545: Connect failed because target host or object does not exist

.... 3 to 5 seconds .....

    pry(main)> Admision.take
    # Admision cod_empresa: 11,.......

Looks like a timeout of some sort. 

There are workarounds to this, but I am hoping to find a simpler solution that this:

    retrylimit=5
    begin
      All_tables.take
    rescue
      sleep 2
      retrylimit -= 1
      retry if retrylimit > 0
    end

**Comment by yahonda** [comment]
Setting timeout described in #761 may help this. Would you reopen if you are getting the same error even after setting timeouts. 

Thanks.
