### ISSUE TITLE
possible error in date/time operation

### ISSUE THREAD

**Issue by scottillogical** [rsim/oracle-enhanced#413]
I'm getting the error

```
possible error in date/time operation:
```

Interestingly enough, I get this even when I'm not executing a datetime query.   This behavior doesn't happen in sqlplus.  

There is a thread on ruby-oci8 with some solutions
https://github.com/kubo/ruby-oci8/issues/28

Basically it involves setting the following before Before require 'oci8'

```
OCI8::BindType::Mapping[Time] = OCI8::BindType::LocalTime
OCI8::BindType::Mapping[:date] = OCI8::BindType::LocalTime
```

Any idea how I can get this working using oracle_enhanced?

**Comment by scottschulthess** [comment]
Okay so we actually it's not mismatched timezone files, this is an issue with handling datetime with zone or some such
