### ISSUE TITLE
Application hangs up after Oracle restart

### ISSUE THREAD

**Issue by stricte** [rsim/oracle-enhanced#419]
When Oracle db restart, my application hangs up. Cant find where I can set any timeout parameter or auto reconnect or sth like this. Is this adapter supports any?

**Comment by vjt** [comment]
Hi @stricte, have a look at #419 on how to set timeouts.

**Comment by yahonda** [comment]
Closing this if it still reproduce after setting timeouts #761 please reopen with detailed information.

Thanks.
