### ISSUE TITLE
specify schema name for use only in from clause

### ISSUE THREAD

**Issue by landesjm** [rsim/oracle-enhanced#425]
I'm using Rails 3.2, Ruby 2.0, ActiveRecord 3.2 and Oracle Enhanced Adaptor 1.4.3. The Oracle DB is XE for development and 11.2 for test/production. Each database is setup with two schemas; MY_PROJ and MY_PROJ_APP. The MY_PROJ_APP schema has assigned roles for all CRUD privileges into MY_PROJ but does not have DDL privileges.

I've setup the following database.yml entries 
development 
    username: MY_PROJ_APP

db_admin 
    username: MY_PROJ

DDL tasks (drop, migrate, seed) are run specifying the RAILS_ENV="db_admin" and are working as expected.

A model definitions has the following definition: 
class Category < ActiveRecord::Base
  self.table_name = 'my_proj.categories'
  self.sequence_name = 'my_proj.categories_seq'
...
end

I'm looking for a way to specify the schema name for use only in the FROM clause and not have it included with the table_name. Some other gems are using the table name in the WHERE clause which is causing ORACLE errors.

**Comment by yahonda** [comment]
#742 implements this feature. Please consider to upgrade to Oracle enhanced adapter 1.6.5.
