### ISSUE TITLE
ENV['RAILS_GEM_VERSION'] not honored by "rake spec"

### ISSUE THREAD

**Issue by rst** [rsim/oracle-enhanced#430]
The output from "rake spec" claims to use the rails version given by ENV['RAILS_GEM_VERSION'], if specified --- but in fact, it's always running against Rails head.  This may be verified by looking at the deprecation messages elsewhere in the output, or by adding the new test below to the specs and observing that it fails.  

The problem is that commit 3c540e deleted the code from the Gemfile that actually selected the gem versions indicated in ENV['RAILS_GEM_VERSION'], leaving only the code in spec_helper.rb which prints out the value.

I've dealt with this locally by reverting 3c540e.  (The intent of that patch isn't clear to me, but I'm pretty sure I don't need it.)  I'm not sure that's the right action for other releases, but it seems like some change is necessary; right now, the specs just aren't behaving as documented.

A simple test to check that the loaded version of ActiveRecord matches what's specified in the environment (if anything): 

```
--- a/spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb
+++ b/spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb
@@ -34,6 +34,15 @@ describe "OracleEnhancedAdapter establish connection" do
 end
 
 describe "OracleEnhancedAdapter" do
+
+  describe "test environment" do
+    it "should run against proper ActiveRecord version, if specified" do
+      unless ENV['RAILS_GEM_VERSION'].end_with?('-master')
+        ActiveRecord.version.to_s.should == ENV['RAILS_GEM_VERSION']
+      end
+    end
+  end
+
   include LoggerSpecHelper
   include SchemaSpecHelper
```

**Comment by yahonda** [comment]
Thanks for opening a issue.
I think it can be fixed by #550, which enables to show ActiveRecord version tested with.

```ruby
==> Effective ActiveRecord version 4.2.3
```
