### ISSUE TITLE
Support rails/rails#13435 - Remove the default 255 char limit on string columns

### ISSUE THREAD

**Issue by yahonda** [rsim/oracle-enhanced#434]
The following ActiveRecord unit test fails after https://github.com/rails/rails/pull/13435 implemented, remove the default 255 char limit on string columns.

```ruby
$ ARCONN=oracle ruby -Itest test/cases/migration/column_attributes_test.rb -n test_add_column_without_limit
Using oracle
Run options: -n test_add_column_without_limit --seed 16927

# Running:

F

Finished in 0.222267s, 4.4991 runs/s, 4.4991 assertions/s.

  1) Failure:
ActiveRecord::Migration::ColumnAttributesTest#test_add_column_without_limit [test/cases/migration/column_attributes_test.rb:43]:
Expected 255 to be nil.

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
$
```

As of right now, rails master branch implements this feature for sqlite3 and pg adapter,
not implemented yet for mysql and mysql2 adapter, but will be fixed.

I think this feature will be available next version of Rails after 4.1, I assume it 4.2. 
It should not be backported into 4.1 and previous version of Rails because it is a new feature.

Oracle database itself requires to specify the length. n is mandatory for VARCHAR2(n CHAR) datatype. Then we cannot implement this feature for Oracle enhanced adapter just removing `:limit => 255`.

I'd like to hear from users and developers of Oracle enhanced adapter for this features. Here are some plans.

- Extend `limit: 255` to the max length of VARCHAR2 datatype,
  4000 bytes or 32767 bytes when 12c and `MAX_STRING_SIZE = EXTENDED` specified.
  Also needs to consider this length means characters, not bytes 
  because Oracle enhanced adapter uses character length semantics, then 1333 characters and 10922 characters.

- Keep the current behavior `limit: 255` for :string datatype of Rails and VARCHAR2(255 CHAR) for Oracle

Thanks,

**Comment by sockmonk** [comment]
I personally like the default limit of 255 characters. Apparently the change in Rails was driven by the fact that in Postgresql, there is no difference between a varchar and text field, while in Oracle there is a difference, and if users need unlimited characters they need to specify a TEXT field. Although it makes the driver behavior different, the current default is probably better.

**Comment by yahonda** [comment]
Thanks for the comment. Let's keep the current behavior.
