### ISSUE TITLE
Is self.primary_key case sensitive and if so, is it intentionally? 

### ISSUE THREAD

**Issue by lustremedia** [rsim/oracle-enhanced#446]
I had a model on a legacy table where
```
self.primary_key="ID" 
```
was set.

This gave me following error on rails side ...
NoMethodError: undefined method `returning_id?' for nil:NilClass: INSERT INTO "FEEDBACK" ("ID", "ADDED", "EMAIL", "FEEDBACK", "FIRSTNAME", "LANG", "LASTNAME", "NL", "TOPIC") VALUES (:a1, :a2, :a3, :a4, :a5, :a6, :a7, :a8, :a9) RETURNING "ID" INTO :returning_id

It worked fine when setting the primary key to:
```
self.primary_key="id" 
```
I also noticed that I could just not provide it at all, and it would work fine, probably falling back to default "id".

My question is, does pk have to be case sensitive or could one always escape to lowercase even if CAPS is provided? If this is a case then, this might be a bug and needs some escaping.

**Comment by yahonda** [comment]
Closed as duplicate with #570
