### ISSUE TITLE
Backtick issue

### ISSUE THREAD

**Issue by duffyjp** [rsim/oracle-enhanced#450]
I'm having an issue with backticks being used in generated SQL.  I think it's happening in the to_sql method.

As a workaround I added a gsub command to strip backticks in columns_for_distinct in oracle_enhanced_adapter.rb

```ruby
s = s.to_sql unless s.is_a?(String)
```

to

```ruby
s = s.to_sql.gsub(/\`/, '') unless s.is_a?(String)
```

We're connecting to an external oracle database.  I don't have anything inhouse I can build a test app against to demonstrate the issue.  

Here is an anonymized error message: 

```
OCIError: ORA-00911: invalid character: SELECT * FROM (SELECT  DISTINCT "PERSON_DATABASE"."EMPLID", FIRST_VALUE(`person_database`.`emplid`) OVER (PARTITION BY "PERSON_DATABASE"."EMPLID" ORDER BY `person_database`.`emplid`) AS alias_0__ FROM "PERSON_DATABASE" LEFT OUTER JOIN "JOB_DATABASE" ON "JOB_DATABASE"."EMPLID" = "PERSON_DATABASE"."EMPLID" WHERE (job_database.deptid IN ('ABC2000','ABC2001'))  ORDER BY alias_0__) WHERE ROWNUM <= 1
```

**Comment by yahonda** [comment]
Would you create an entire testcase not just a code snippet. If you need an environment to run Oracle database you can use https://github.com/yahonda/rails-dev-box-runs-oracle 

Thanks,

**Comment by yahonda** [comment]
Here is a sample testcase. 

```ruby
# Activate the gem you are reporting the issue against.
gem 'activerecord', '4.2.3'
gem 'activerecord-oracle_enhanced-adapter', '1.6.3'
require 'active_record'
require 'minitest/autorun'
require 'logger'
require 'active_record/connection_adapters/oracle_enhanced_adapter'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# Set Oracle enhanced adapter specific connection parameters
DATABASE_NAME = ENV['DATABASE_NAME'] || 'orcl'
DATABASE_HOST = ENV['DATABASE_HOST']
DATABASE_PORT = ENV['DATABASE_PORT']
DATABASE_USER = ENV['DATABASE_USER'] || 'oracle_enhanced'
DATABASE_PASSWORD = ENV['DATABASE_PASSWORD'] || 'oracle_enhanced'
DATABASE_SYS_PASSWORD = ENV['DATABASE_SYS_PASSWORD'] || 'admin'

CONNECTION_PARAMS = {
  :adapter => "oracle_enhanced",
  :database => DATABASE_NAME,
  :host => DATABASE_HOST,
  :port => DATABASE_PORT,
  :username => DATABASE_USER,
  :password => DATABASE_PASSWORD
}

ActiveRecord::Base.establish_connection(CONNECTION_PARAMS)

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, :force => true do |t|
  end

  create_table :comments, :force => true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments << Comment.create!

    assert_equal 1, post.comments.count
    assert_equal 1, Comment.count
    assert_equal post.id, Comment.first.post.id
  end
end
```

**Comment by fruwe** [comment]
same problem here

**Comment by duffyjp** [comment]
@fruwe Are you by chance using mysql and oracle at the same time?  I realized I never mentioned that in my original issue write up.  We use mysql for the local database, and connect to probably four or five oracle DBs from vendors.  Backticks in SQL are very much a mysql behavior.  I'd bet some combination of mysql2 and oracle-enchanced both extending ActiveRecord is the culprit.  

It's hard to find time at work to look into it deeper when the one-line monkey patch posted above solves the immediate problem...

**Comment by yahonda** [comment]
Thanks for reporting, if I understand this correctly updating `columns_for_distinct` method like this addresses this issue and it only happens at the environment where mysql2 and Oracle enhanced adapter are used.

```ruby
s = s.to_sql.gsub(/\`/, '') unless s.is_a?(String)
```
I'd suggest to implement this workaround for users who need to use mysql2 and Oracle enhanced adapter at the same time.

Thanks for reporting and providing the workaround.
