### ISSUE TITLE
Functions loaded from db/structure.sql missing semi-colon and result in compile error.

### ISSUE THREAD

**Issue by openface** [rsim/oracle-enhanced#454]
After recreating my test environment from db/structure.sql (with structure_dump enabled), none of my database functions were available.   Calling them resulted in an error: ORA-O6575: package or function manager_of is in invalid state.

Upon further inspection, I narrowed the problem down to where the db/structure.sql was being read and statements were being executed.  

```
# oracle_enhanced_structure_dump.rb

def execute_structure_dump(string)
    string.split(STATEMENT_TOKEN).each do |ddl|
      ddl.chop! if ddl[-1,1] == ';'
      execute(ddl) unless ddl.blank?
    end
end
```

That chop! line is removing semi-colons from the last line of the functions, causing compilation to fail on those functions.

Link to source:
https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced_structure_dump.rb#L243

After commenting out the chop! line, the functions all load, compile, and are available within the test environment.   

I'm now wondering why the semi-colons are ever chopped?

**Comment by yahonda** [comment]
Closed as #456 has been merged to rails42 branch.
