### ISSUE TITLE
db:structure:load doesn't load procedures, functions properly

### ISSUE THREAD

**Issue by palfvin** [rsim/oracle-enhanced#461]
This method removes a trailing semicolon from each DDL statement which results in procedures, functions, etc. being defined without the necessary trailing semicolon and thus not compiling.  This removal is unnecessary for processing structure.sql files generated by the adapter since the adapter doesn't generate a trailing semicolon unless it's needed.

      def execute_structure_dump(string)
        string.split(STATEMENT_TOKEN).each do |ddl|
          ddl.chop! if ddl[-1,1] == ';'
          execute(ddl) unless ddl.blank?
        end
      end

**Comment by yahonda** [comment]
Closed as #456 has been merged.
