### ISSUE TITLE
Generation of db/schema.rb

### ISSUE THREAD

**Issue by alexfalkowski** [rsim/oracle-enhanced#462]
Hi,

I am on version 1.4.3. In one of my migrations I have the following:

```
add_context_index :annual_departments, [:name],
                      name: 'i_annual_dep_context_name',
                      index_column: :name,
                      sync: 'ON COMMIT'
```

Though in my db/schema.rb it generates:

```
add_context_index "annual_departments", ["name"], :name => "i_annual_dep_context_name"
```

Missing all the options. This seems to work if the collection of columns has 2 or more elements.

**Comment by chao-xian** [comment]
I am also having this issue. I added the `sync: "ON_COMMIT"` on a single column:

`add_context_index :items, :title, sync: 'ON COMMIT'`

produces:

`add_context_index "items", ["title"], name: "i_content_items_title"` 

in schema.rb.

Using reload instead of migrate breaks our tests/app.
