### ISSUE TITLE
possible memory leak in oracle temporary tablespace

### ISSUE THREAD

**Issue by metaphalon** [rsim/oracle-enhanced#534]
I've encountered the problem, that my oracle database runs out of memory in the temporary tablespace.
This is reflected by the oracle error message "Java::JavaSql::SQLException: ORA-01652: unable to extend temp segment by 128 in tablespace TEMP".

I tracked this down to the OracleEnhancedJDBCConnection::Cursor class.
Every time a binary or text has to be inserted into the database, the Cursor class creates a temporary blob (Java::OracleSql::BLOB.createTemporary).
But the space which is reserved will only be freed when the sql connection is closed, due usage of Java::OracleSql::BLOB::DURATION_SESSION.

In a jruby webapp the sql connections don't get closed very often, but over time many binaries may get inserted.

**Comment by yahonda** [comment]
ORA-01652 is not a memory related issue, it run out of temporary tablespace usage. 
Please contact with your DBA to see if there is enough temporary tablespace is available.
