### ISSUE TITLE
wrong number of arguments (3 for 1..2)

### ISSUE THREAD

**Issue by lustremedia** [rsim/oracle-enhanced#540]
When calling ".save" on an ActiveRecord::Base object I got the error "wrong number of arguments (3 for 1..2)" on rails 4.2

Version 1.5.2 was in gemset. Updating to 1.5.5 made the error go away.

may be related to #414

**Comment by yahonda** [comment]
Closed since you do not get errors using 1.5.5.

**Comment by lustremedia** [comment]
That is fine! I just thought I'd leave it here if someone else is using an older version and running into that issue. Thanks @yahonda !

**Comment by yahonda** [comment]
Thanks.
