### ISSUE TITLE
:null => false constrains from migration don't get written into schema

### ISSUE THREAD

**Issue by suung** [rsim/oracle-enhanced#543]
after getting suggested to post this here, please see: https://github.com/rails/rails/issues/18738

thanks!

**Comment by yahonda** [comment]
Would you provide more detailed information here including from which version to which version you are going to upgrade, not just pointing out the rails issue number. 

Also testcase with necessary migration files are helpful.

**Comment by yahonda** [comment]
Closing since no feedback available.
