### ISSUE TITLE
Auto_retry does nothing as the exception raised is not "OracleEnhancedConnectionException"

### ISSUE THREAD

**Issue by ctroncoso** [rsim/oracle-enhanced#544]
Test environment. 
1.- Standard connection to database works fine set with auto_retry=true and logging to STDOUT.
2.- Pull the ethernet cable.
3.- Fetch some row

    SomeTable.take
    => ActiveRecord::StatementInvalid: OCIError: ORA-03113......

4.- Try again

    SomeTable.take
    => ActiveRecord::StatementInvalid: OCIException: OCI8 was already closed.

5.- Force reconnect.

    ActiveRecord::Base.connection.reconnect!
    => nil

Ooops... wasn't it supposed to [log a warning](
https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb#L712)?
Rescue is never called as the exception doesn't match.

6.- Connect the cable

7.- Try again

    SomeTable.take
    => ActiveRecord::StatementInvalid: OCIException: OCI8 was already closed.

8.- Force reconnect.

    ActiveRecord::Base.connection.reconnect!
    => true

Now it works fine, but auto_retry didn't work.

As far as I see, the [auto-recover funtionality](https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced_oci_connection.rb#L424) is not getting called as the exceptions don't match.

**Comment by yahonda** [comment]
Closing this if it still reproduce after setting timeouts #761 please reopen with detailed information.
