### ISSUE TITLE
Rails42: Issue with non-existent columns

### ISSUE THREAD

**Issue by apeiros** [rsim/oracle-enhanced#545]
Commit https://github.com/rsim/oracle-enhanced/commit/af27085c34d1ff7bf60cccad4f6f506a10bd13cf#diff-c35523ec2d21d10ec6feb4fd2c62098b introduces a bug with non-existent columns. It has an unconditional column_for_attribute.
I have a working fix in https://github.com/swisslife-select/oracle-enhanced/commit/bad2de93d77813fc7182943d58936b25474d10bc and in an additional commit https://github.com/swisslife-select/oracle-enhanced/commit/bc7e8128ea476ad9e5c53a3b5d9a25b2fc704987 I avoid a compatibility warning generated by rails 4.2.

We will submit a pull request as soon as we've added a test-case.

**Comment by yahonda** [comment]
Closed as #551 has been merged to rails42.
