### ISSUE TITLE
rails42: ORA-00907 missing right paren on `rake db:reset` for timestamp with limit

### ISSUE THREAD

**Issue by wconrad** [rsim/oracle-enhanced#546]
When using Rails 4.2 and the rails42 branch of oracle_enhanced, a "rake db:reset" on a schema that contains a timestamp with a limit generates an "ORA-00907 missing right paren" error.

Versions:
* oracle-enhanced, rails42 branch, commit c2d65949799852b85a9479ec75dffeae33bd5bbf
* Rails 4.2.0
* Ruby 2.2.0

db/schema.rb

```
ActiveRecord::Schema.define(version: 20150122201003) do
  create_table "jobs", force: true do |t|
    t.timestamp "run_time",             limit: 6
  end
end
```

The command: `rake db:reset`

The error:

```
Warning: NLS_LANG is not set. fallback to US7ASCII.
-- create_table("jobs", {:force=>true})
rake aborted!
ActiveRecord::StatementInvalid: OCIError: ORA-00907: missing right parenthesis: CREATE TABLE "JOBS" ("ID" NUMBER(38) NOT NULL PRIMARY KEY, "RUN_TIME" DATE(6))
```

# How it used to work

This worked in oracle_enhanced 1.5.5 and Rails 4.1.9.  The SQL generated when it worked was:

    CREATE TABLE "JOBS" ("ID" NUMBER(38) NOT NULL PRIMARY KEY, "RUN_TIME" TIMESTAMP(6))

In the working query, the column's type is `TIMESTAMP(6)`.  In the non-working query, the column's type is `DATE(6)`.

**Comment by yahonda** [comment]
I can reproduce it. Somehow `timestamp` sql data type has gone or incorrectly assigned to `date` sql type.

**Comment by wconrad** [comment]
@yahonda That's good news.  Thank you for looking at this.

**Comment by yahonda** [comment]
@wconrad Would you try to see if it reproduces by adding this entry to your Gemfile.

```ruby
gem 'activerecord-oracle_enhanced-adapter', github: 'yahonda/oracle-enhanced', branch: 'rails42_546'
```

**Comment by yahonda** [comment]
@wconrad Nevermind. The previous update should not fix your issue.

**Comment by wconrad** [comment]
@yahonda Sorry for the delay.  I'll be able to look at this Monday or Tuesday.

**Comment by yahonda** [comment]
@wconrad It would need some more work to fix this error. So probably you are getting the same error with `rails42_546` branch. Will update when I find some fixes.

**Comment by wconrad** [comment]
Yes, I got the same error.

I should have created a standalone gist to reproduce this.  I'll try to do that now.

**Comment by wconrad** [comment]
Here's a [gist to reproduce the issue](https://gist.github.com/wconrad/ee056b63084e3f9ac9ca)

**Comment by wconrad** [comment]
By the way: The gist is just a tool for you to use if you want.  I am of course willing to run any tests you want.

**Comment by yahonda** [comment]
@wconrad Thanks for providing the test case.

I've found a kind of dirty workaround by mapping Rails `:datetime` to Oracle TIMESTAMP.
In the master branch Rails `:datetime` is mapped to Oracle `DATE` by default, then 
it would cause other datatype issue. Then this commit itself cannot be merged to `rails42` branch. 

Still I think it works for you to test this branch.

```ruby
gem 'activerecord-oracle_enhanced-adapter', github: 'yahonda/oracle-enhanced', branch: 'rails42_546_2'
```

**Comment by wconrad** [comment]
@yahonda Thanks for the rails42_546_2 test branch.  That branch caused my "rake db:reset" to succeed.  Whatever regressions the branch introduces are not noticed by the project's unit tests, which pass (except for the one affected by https://github.com/rsim/oracle-enhanced/issues/542)

**Comment by yahonda** [comment]
@wconrad Thanks for testing and glad to hear it's working. I'm trying to find more comprehensive fix to address this issue.

**Comment by wconrad** [comment]
Thank you for your hard work on this.

**Comment by yahonda** [comment]
Discussed @rsim and we've found a relatively comprehensive way to address it.
@wconrad Would you try to see if it reproduces by adding this entry to your Gemfile.

```ruby
gem 'activerecord-oracle_enhanced-adapter', github: 'yahonda/oracle-enhanced', branch: 'rails42_546'
```

Note: If you use other database adapter other than Oracle, your non Oracle application using :timestamp will not work.

**Comment by yahonda** [comment]
#575 has been merged to rails42 branch. I believe #546 has been addressed. @rsim Thanks for your advice. @wconrad If you still reproduce it by using `rails42` branch, please update it.
