### ISSUE TITLE
Renaming table with associated sequence

### ISSUE THREAD

**Issue by negativalpha** [rsim/oracle-enhanced#547]
When renaming a table name to the maximum allowed number of characters the generated sequence name is longer than allowed and therefore the migration fails. This however doesn't happen when creating a table, because if the sequence name is not specified, it's being processed from the table name by the `default_sequence_name` method.

**Comment by yahonda** [comment]
Sorry for late update. I think current implementation is fair enough. Users can get the new table name or the new sequence name is too long in advance, then they can think other alternatives including not renaming table name.

Unlike other databases commonly used with ActiveRecord - such as MySQL `auto_increment` and PostgreSQL `serial` datatype - Oracle sequence objects and table objects have no relationship in database system. i.e even if you drop `USERS` tables from Oracle database using sql statement `USERS_SEQ` sequence objects remain. Therefore Oracle enhanced adapter need to take care of these dependencies mainly based on its table name as `#{table_name}` and sequence name as `#{table_name}_seq`. 

Maintenance these relationships is one of  difficult task. Fortunately Oracle 12c introduces `IDENTITY` datatype like `auto_increment` in MySQL, Here implicit sequence objects depend on its base table, then we as ActiveRecord adapter maintainer will not need to manage sequence names. Unforatunately Oracle enhanced adapter does not support `IDENTITY` data type yet, I'd like to moving forward like this way, supporting new features which makes Rails support easier, not making current status complex.

**Comment by yahonda** [comment]
I'm changing my mind and thinking about to address it. Please give me some more time..

**Comment by yahonda** [comment]
Closed as #676 has been merged to master.
