### ISSUE TITLE
Deprecation Warning under Ruby 2.2

### ISSUE THREAD

**Issue by DVG** [rsim/oracle-enhanced#562]
While it doesn't seem to be causing a problem, persay, I am seeing a ton of errors that look like this:

```
/home/dvg/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-oracle_enhanced-adapter-1.4.2/lib/active_record/connection_adapters/oracle_enhanced_dirty.rb:21: warning: Comparable#== will no more rescue exceptions of #<=> in the  next release.

/home/dvg/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-oracle_enhanced-adapter-1.4.2/lib/active_record/connection_adapters/oracle_enhanced_dirty.rb:21: warning: Return nil in #<=> if the comparison is inappropriate or avoid such comparison.
```

**Comment by sockmonk** [comment]
Have you tried version 1.4.3, which I think is the latest version in the 1.4.x series? Using ruby 2.2.0 or 2.2.1?

It seems like if you're using ruby 2.2, you might consider upgrading to Rails 4.x and the latest oracle_enhanced 1.5.x release.

**Comment by yahonda** [comment]
Thanks for opening a issue.
This code has been removed in #479. Unfortunately no plan to suppress just warnings into 1.4.x version.
