### ISSUE TITLE
Boolean values are improperly serialized in Rails 4.2

### ISSUE THREAD

**Issue by jestraw** [rsim/oracle-enhanced#563]
In the rails42 branch, we have some columns which are defined as
```ruby
serialize :some_column, JSON
```
My expectation is that setting a boolean value in this column:
```ruby
obj.some_column = true
```
will serialize the data to the string ```"true"```:
```ruby
> true.to_json
 => "true"
```
However, instead the data gets serialized to the string ```"Y"```, which then doesn't parse as valid JSON on read: ```JSON::ParserError: 795: unexpected token at 'Y'```.

I think the issue is in ```type_cast``` -- https://github.com/rsim/oracle-enhanced/blob/rails42/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb#L670  which doesn't consider the configured column coder at all before deciding how to map data types that Oracle doesn't understand.

As @apeiros pointed out in issue #549, it looks like in active_record-4.2 this code should somehow be using ```type_cast_for_database```, which gets the defined column coder and tells it to dump the value.

**Comment by jestraw** [comment]
This fairly simple change seems to avoid the problem -- we just short-circuit the type conversion if the column is serialized:

```ruby
      # Cast a +value+ to a type that the database understands.
      def type_cast(value, column)
        if column && column.cast_type.is_a?(Type::Serialized)
          # serialized columns should be able to take care of themselves
          super
        else
          case value
          when true, false
            if emulate_booleans_from_strings || column && column.type == :string
              self.class.boolean_to_string(value)
            else
              value ? 1 : 0
            end
          when Date, Time
            if value.acts_like?(:time)
              zone_conversion_method = ActiveRecord::Base.default_timezone == :utc ? :getutc : :getlocal
              value.respond_to?(zone_conversion_method) ? value.send(zone_conversion_method) : value
            else
              value
            end
          else
            super
          end
        end
      end```

**Comment by yahonda** [comment]
Thanks for the suggestion. #591 has been merged to rails42 branch. Then it should be fixed.
