### ISSUE TITLE
Incorrect timezone offset applied on insert of a timestamp during DST when using JDBC connection

### ISSUE THREAD

**Issue by nguyent** [rsim/oracle-enhanced#566]
I'm opening this issue as a heads up to anyone using this gem, the JDBC adapter and JRuby. I have been pulling my hair out over this for a while and if I can save just one person from this issue it will have been worth it.

Upon inserting a Time in DST to a Timestamp column (Timestamp with Time Zone in my case), Ruby Time values are converted by `ruby_to_java_value` via `lib/active_record/connection_adapters/oracle_enhanced_jdbc_connection.rb:450`

And in the case of a Time column, this call is made to get the java value:
```ruby
Java::java.sql.Timestamp.new(value.year-1900, value.month-1, value.day, value.hour, value.min, value.sec, value.usec * 1000)
```

When inserting a DST UTC Time, without `TZ=UTC` explicitly passed into the environment prior to JRuby loading, an offset is incorrectly applied to the DST UTC Time initially passed in.

```ruby
$ bundle exec rails c
[1] pry(main)> value = "2015-03-08T02:00:00.000+00:00".to_time
=> 2015-03-08 02:00:00 +0000
[2] pry(main)> Java::java.sql.Timestamp.new(value.year-1900, value.month-1, value.day, value.hour, value.min, value.sec, value.usec * 1000).toString
=> "2015-03-08 03:00:00.0"
[3] pry(main)> ENV['TZ']
=> "UTC"
```

```ruby
$ TZ=UTC bundle exec rails c
[1] pry(main)> value = "2015-03-08T02:00:00.000+00:00".to_time
=> 2015-03-08 02:00:00 +0000
[2] pry(main)> Java::java.sql.Timestamp.new(value.year-1900, value.month-1, value.day, value.hour, value.min, value.sec, value.usec * 1000).toString
=> "2015-03-08 02:00:00.0"
[3] pry(main)> ENV['TZ']
=> "UTC"
```

Even if you set TZ as an environment variable in Ruby (in an initializer), it will not get picked up by the parent JRuby process, for reasons explained here: https://github.com/jruby/jruby/issues/2760 . This of course will wreak havoc during DST, so you should ensure this value is explicitly passed in to the parent process.

**Comment by yahonda** [comment]
Thanks for providing information. Closing this since no more available actions for this issue so far.
