### ISSUE TITLE
rails 4.1.10 TypeError: superclass mismatch for class OracleEnhancedAdapter

### ISSUE THREAD

**Issue by lustremedia** [rsim/oracle-enhanced#567]
This seems to be the same issue as #523, however the fix #526 does not apply to the latest stable 1.5.5

I recently updated Rails to 4.1.10 and noticed the issue.
When applying the fix manually in 4.1.10 I get my rake tasks back.

4.1.10 was released with the latest rails 4.2

Using activesupport (4.1.10)
Using activemodel (4.1.10)
Using activerecord (4.1.10)
Using activerecord-oracle_enhanced-adapter (1.5.5)

**Comment by yahonda** [comment]
Oracle enhanced adapter 1.5.6 has been released which includes #526. Please try it and open if you still reproduce this TypeError.
