### ISSUE TITLE
model.find(<id>) doesn't work when primary_key is explicitly set with ALLCAPS

### ISSUE THREAD

**Issue by colepanike** [rsim/oracle-enhanced#570]
This is a funny little issue and I'm not familiar with the internal mechanics of adapters so I can't tell you quite why this happens. Here's my error though

I'm working with a legacy database and use this class as a super for all models that work with that database (names altered):

    class LegacyDatabase < ActiveRecord::Base
        self.abstract_class = true
    	establish_connection :legacy
    	# Prevent creation of new records and modification to existing records
    	def readonly?
    		return true
    	end

    	# Prevent objects from being destroyed
    	def before_destroy
    		raise ActiveRecord::ReadOnlyRecord
    	end
    end

Here is an inheriting class:

    class LegacyTable < LegacyDatabase
    	self.table_name = :LEGACY_TABLE
    	self.primary_key = "LEGACYTABLEIDX"
    end

When the model is called like so: `LegacyTable.find(<id>)`

I get this as a generated SQL:

`SELECT "LEGACY_TABLE".* FROM "LEGACY_TABLE" WHERE "LEGACY_TABLE"."LEGACYTABLEIDX" = '--- !ruby/object:ActiveRecord::StatementCache::Substitute {} ' AND ROWNUM <= 1`

Which is obviously failing. 

-----

**Found workaround:**
The solution turns out to be decapitalizing the `primary_key`:

    class LegacyTable < LegacyDatabase
    	self.table_name = :LEGACY_TABLE
    	self.primary_key = "legacytableidx"
    end

Must be a bug in the adapter parser I guess

Thanks for your time.

**Comment by sockmonk** [comment]
This looks like it's related to https://github.com/rsim/oracle-enhanced/issues/446.

**Comment by colepanike** [comment]
Yes that looks like the same issue.

**Comment by yahonda** [comment]
I think this is an expected behavior since `primary_key=` is defined inside Rails itself. except for MixedCase, every `primary_key=` are tested with lowercase string.

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/attribute_methods/primary_key.rb#L105-L124

https://github.com/rails/rails/blob/master/activerecord/test/cases/primary_keys_test.rb

**Comment by lustremedia** [comment]
Thanks for clarifications @yahonda ! I just took it as a given to use lowercase PKs and moved on and even forgot about that ticket :+1:

**Comment by yahonda** [comment]
Thanks for the update.
