### ISSUE TITLE
Y/N boolean values are read incorrectly in Rails 4.2

### ISSUE THREAD

**Issue by edwagner** [rsim/oracle-enhanced#573]
When emulate_booleans_from_strings = true, my 'Y' values are read as false. These columns used to work in my Rails 3 app, and I can't figure out exactly what changed in the upgrade to Rails 4.2 (using the rails42 branch of oracle_enhanced_adapter) that caused them to stop working. I've gotten around this by including this in an initializer:
```ruby
ActiveRecord::ConnectionAdapters::Column::FALSE_VALUES << 'N'
ActiveRecord::ConnectionAdapters::Column::TRUE_VALUES << 'Y'
```
I'm not sure if this logic belongs in oracle_enhanced_adapter or in active_record, but it seems like since oracle_enhanced_adapter has specific logic for turning true/false into Y/N when writing to the database, it ought to have the logic for translating Y/N to true/false when reading too.

**Comment by yahonda** [comment]
Thanks for the info. Let me review.

**Comment by yahonda** [comment]
#574 has been merged to rails42 branch. I was not able to find which commit caused that change you reported. Rails 42 introduces a lot of type related behavior such as https://github.com/rails/rails/commit/0b682e4b05c8f58c77c655650af6638c483ac903 Probably one of these changes, but not sure.

@edwagner Thanks for the useful information.

**Comment by edwagner** [comment]
Great, thanks for the quick turnaround!
