### ISSUE TITLE
Recommended Rails version?

### ISSUE THREAD

**Issue by andreynering** [rsim/oracle-enhanced#602]
The README is not clear about Rails versions compatibility.

Seems that this gem is not done for 4.2, right? Is it done for 4.1? Or should I use 4.0?

**Comment by sockmonk** [comment]
I'm using version 1.5.6 of the gem with Rails 4.1.10 with no problems. It looks like the rails42 branch may be usable for Rails 4.2, but has enough outstanding issues that it hasn't been officially released yet.

**Comment by andreynering** [comment]
@sockmonk Thank you for commenting.

Tried `rails42` branch but had few problems.

I'll use Rails 4.1.
