### ISSUE TITLE
Could not load Oracle Enhanced Adapter error in Rails 4.2 app after rebooting 

### ISSUE THREAD

**Issue by JimEvansIntox** [rsim/oracle-enhanced#649]
Summary: 
--------------------
Was on Rails 3, was connecting to Oracle dev box via the rails console for more than month with no issues. 
Update to Rails 4.2, updated the adapter, was still able to connect via the rails console with no issues. 
Rebooted. No longer able to connect via the rails console. Have researched and experimented.

Details:
--------------------
My config/database.yml file contains:

ab_conv_development:
 adapter: oracle_enhanced
 database: 127.0.0.1/ORCL
 username: username
 password: password
 schema: SCHEMA

 I run bundle exec rails c
 and then run ActiveRecord::Base.establish_connection(:ab_conv_development)
I get:
LoadError: Could not load 'active_record/connection_adapters/oracle_enhanced_adapter'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql', 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem to the Gemfile.
from /Users/[USERNAME]/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/oracle-enhanced-a8b05cbd4e84/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:7:in `rescue in <top (required)>'

I log out of the rails console.
I run irb and enter:

require 'rubygems' 
require 'active_record' 

ActiveRecord::Base.establish_connection( 
 :adapter => "oracle_enhanced",
 :database => "127.0.0.1/ORCL",
 :username => "username",
 :password => "password",
 :schema => "SCHEMA"
)
class AbCalendar < ActiveRecord::Base 
  self.table_name = "SCHEMA.CALENDAR"
end

puts AbCalendar.all.size

And I get an integer result. Yay. So everything is in theory installed and working from irb. 
Where else can I look to figure out why the adapter isn't working with my Rails app?

Environment:
-----------------------------------------------
On Mac OSX 10.10.3
Rails 4.2.2
Ruby 2.1.5p273
Gemfile inlcudes:
  gem 'activerecord-oracle_enhanced-adapter', :git => 'git://github.com/rsim/oracle-enhanced.git'
  gem 'ruby-oci8'
I've confirmed I've run
export NLS_LANG="AMERICAN_AMERICA.UTF8"
export ORACLE_HOME=/bin/oracle/instantclient_11_2
export DYLD_LIBRARY_PATH=$ORACLE_HOME
and the rails console ENV reflects that.
I used Time Machine to pull my .bash_history file from the day after a reboot from two weeks ago to make sure there wasn't an additional command I forgot to enter.

Appreciation:
-------------------------------------
Thank you for this gem and your help. The gem has made life much easier.

**Comment by yahonda** [comment]
Oracle enhanced adapter does not have `:schema` option. You might have modified to do something. Please remove this entry or make necessary changes to your local gem to make `:schema` option works.

```ruby
:schema => "SCHEMA"
```

**Comment by JimEvansIntox** [comment]
I removed that and it still isn't working. However after more investigation, it appears that the root issue is related to ruby-oci8's bundle. From irb & ruby I can run "require 'oci8'" and it returns true. From rails console it returns 
LoadError: dlopen(/Users/jevans/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-14/2.1.0-static/ruby-oci8-2.1.8/oci8lib_210.bundle
9): Library not loaded: /ade/b/3071542110/oracle/rdbms/lib/libclntsh.dylib.11.1
I have that symlinked in the bin/oracle directory. It seems to be an issue with the bundler ruby-oci8.
If you have any suggestions, please let me know. However I am closing this since it is not an issue with the oracle adapter.

**Comment by yahonda** [comment]
Thanks for the clarify.
