### ISSUE TITLE
when a serialized column is assigned a hash value in the code, the value is stored as string instead of yaml

### ISSUE THREAD

**Issue by lramamoo** [rsim/oracle-enhanced#655]
When a hash value is assigned to a serialized column which is a text field in table, the value is stored as string on save instead of yaml.

@udf_attribute.field_constraints = {:length=>{:is=>4}}

This work fine when a record is created. The problem happens only on update. On update the value is stored as "{:length=>{:is=>4}}"

Rails version used is 4.2.2

**Comment by yahonda** [comment]
Would you provide an entire test case to reproduce this?

**Comment by yahonda** [comment]
Here what I mean "an entire test case" is like this. https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb

**Comment by lramamoo** [comment]
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '4.2.2'
  gem 'activerecord-oracle_enhanced-adapter',:git => 'git://github.com/rsim/oracle-enhanced.git'
  gem 'ruby-oci8'
  gem 'minitest'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'oracle_enhanced', database: 'inw')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :udf_tests do |t|
    t.text :select_options
  end
end

class UdfTest < ActiveRecord::Base
  serialize :select_options
end

class BugTest < Minitest::Test
  def test_association_stuff
    udf = UdfTest.new
    udf.select_options = {:length=>{:is=>1}} 
    udf.save
    udf.reload
    assert_equal udf.select_options, {:length=>{:is=>1}} 

    udf.select_options = {:length=>{:is=>2}} 
    udf.save
    udf.reload
    assert_equal udf.select_options, {:length=>{:is=>2}} 
  end
end

**Comment by lramamoo** [comment]
The above test case passes with following gems:

  gem 'activerecord', '3.2.13'
  gem 'activerecord-oracle_enhanced-adapter', '1.4.2'

**Comment by yahonda** [comment]
Thanks for providing a testcase.

**Comment by yahonda** [comment]
#657 should have fixed this issue. At least your testcase works. Please validate and update how it works.

**Comment by lramamoo** [comment]
Thanks. This is working fine in my environment after the update.

**Comment by yahonda** [comment]
Good to know. your testcase helps a lot. Thanks again.
