### ISSUE TITLE
rake db:migrate: NoMethodError: undefined method `foreign_keys'

### ISSUE THREAD

**Issue by gkobluk** [rsim/oracle-enhanced#666]
I'm using a new clean database oracle 11 xe. And when I try to execute rake db:migrate after generate a simple create script like:
rails g model comentario descripcion:string

I get something like this:
```ruby
rake aborted!
NoMethodError: undefined method `foreign_keys' for #<ActiveRecord::ConnectionAdapters::OracleEnhanced::TableDefinition:0x00000004fe8040>
~/.rvm/gems/ruby-2.2.2@oracle/gems/activerecord-oracle_enhanced-adapter-1.6.1/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:93:in `create_table'
```

I'm using rails 4.2.0 and 
```ruby
#gem 'activerecord-oracle_enhanced-adapter', '~> 1.6.0'
or
#gem 'activerecord-oracle_enhanced-adapter', github: 'rsim/oracle-enhanced', branch: 'rails42'
or
#gem 'activerecord-oracle-adapter'
or
gem "activerecord-oracle_enhanced-adapter", "~> 1.6.0.beta1"
```
same result.

Thank you.

**Comment by yahonda** [comment]
It is duplicated with #651. Oracle enhanced adapter requires Rails 4.2.1 or upper version of Rails.

**Comment by yahonda** [comment]
Closing this. Please reopen if it still reproduce using Rails 4.2.1 or later version of Rails.
