### ISSUE TITLE
Hardcoded TO_DATE and TO_TIMESTAMP formats in quote methods

### ISSUE THREAD

**Issue by tolgap** [rsim/oracle-enhanced#669]
I've been battling weird date coercion errors for a few weeks now. Here's an example:

```
pry> Model.update_attributes(last_updated_at: DateTime.now)
ActiveRecord::StatementInvalid (TypeError: failed to coerce oracle.sql.DATE to oracle.sql.DATE)
```

As you can see, the error is a weird cast/coerce error from `oracle.sql.DATE` to an `oracle.sql.DATE`. This makes me think it's a format issue.

In the adapter source code, I found a few hardcoded `TO_DATE` and `TO_TIME` formats when passing a `Date` or `DateTime` value to the quote methods:

See:
https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb#L675

      def quote_timestamp_with_to_timestamp(value) #:nodoc:
        # add up to 9 digits of fractional seconds to inserted time
        value = "#{quoted_date(value)}:#{("%.6f"%value.to_f).split('.')[1]}" if value.acts_like?(:time)
        "TO_TIMESTAMP('#{value}','YYYY-MM-DD HH24:MI:SS:FF6')"
      end

And:
https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb#L657

      def quote_date_with_to_date(value) #:nodoc:
        # should support that composite_primary_keys gem will pass date as string
        value = quoted_date(value) if value.acts_like?(:date) || value.acts_like?(:time)
        "TO_DATE('#{value}','YYYY-MM-DD HH24:MI:SS')"
      end

Why are these formats hardcoded? Wouldn't this interfere with my own NLS_SESSION parameters? The session parameters I set in my `database.yml` are:

```
  nls_timestamp_format: ! "DD-MM-RR HH24:MI:SSXFF"
  nls_timestamp_tz_format: ! "DD-MM-RR HH24:MI:SSXFF TZR"
  nls_time_format: ! "HH24:MI:SSXFF"
  nls_time_tz_format: ! "HH24:MI:SSXFF TZR"
```

Thanks.

**Comment by yahonda** [comment]
Please refer #341

**Comment by tolgap** [comment]
@yahonda Thanks for pointing that issue out. I had skimmed over other issues, but it seems I glanced over that one.

But I still don't quite understand what ":db" format is, and how I could check whether it's being changed (as mentioned in that issue).

**Comment by tolgap** [comment]
A bit of a late comment...

It turns out, there was a discrepancy between our local database settings and the production database settings in the timezones, including the Rails default timezone. I will close this issue.

**Comment by yahonda** [comment]
Thanks for reporting. Sorry I did not answer your questions.

**Comment by tolgap** [comment]
No problem, that issue actually had the solution. I figured out the `:db` format in the Rails source code for `ActiveSupport::TimeWithZone`
