### ISSUE TITLE
DATE columns are retrieved as Time objects

### ISSUE THREAD

**Issue by coorasse** [rsim/oracle-enhanced#674]
Columns with datatype DATE are currently retrieved as Time objects in Ruby, instead of Date.

**Comment by rsim** [comment]
Oracle DATE type is date with time and therefore it is mapped to Ruby Time which is date with time.

**Comment by coorasse** [comment]
But this brings to incongruencies with other adapters, if also DATE is a Time, what is the datatype for a Date?

**Comment by coorasse** [comment]
If I have a table with a DATE field called `remainder_until_at` I'm not able to perform searches on that table. I show you the output:

    PunchCardPoint.where(remainder_until_at: Date.today.to_time).count

    SELECT COUNT(*) FROM "PUNCH_CARD_POINTS" WHERE "PUNCH_CARD_POINTS"."REMAINDER_UNTIL_AT" = :a1  [["remainder_until_at", 2015-07-20 22:00:00 UTC]]
    => 0

weird, there are data there.

    PunchCardPoint.where(remainder_until_at: Date.today.to_time).to_sql
    => "SELECT \"PUNCH_CARD_POINTS\".* FROM \"PUNCH_CARD_POINTS\" WHERE \"PUNCH_CARD_POINTS\".\"REMAINDER_UNTIL_AT\" = TO_DATE('2015-07-20 22:00:00','YYYY-MM-DD HH24:MI:SS')"

the query looks fine as well, so I tried this:

    PunchCardPoint.find_by_sql(PunchCardPoint.where(remainder_until_at: Date.today.to_time).to_sql).count
    PunchCardPoint Load (7.1ms)  SELECT "PUNCH_CARD_POINTS".* FROM "PUNCH_CARD_POINTS" WHERE "PUNCH_CARD_POINTS"."REMAINDER_UNTIL_AT" = TO_DATE('2015-07-20 22:00:00','YYYY-MM-DD HH24:MI:SS')
    => 8

et voilà!

**Comment by coorasse** [comment]
The same error happens if I change the type of the column from DATE to TIMESTAMP(6)

**Comment by rsim** [comment]
Oracle does not have a date type which contains only date, DATE type is actually a datetime type (and without a time zone).

In your case it seems that the issue is that you pass Time objects in local time zone which are converted to UTC time zone by ActiveRecord and then you get 2015-07-20 22:00:00 and not 2015-07-21 00:00:00 in your SQL statements.

If you want to map particular Oracle table columns to Date then see `set_date_columns` method https://github.com/rsim/oracle-enhanced/blob/master/README.md#legacy-schema-support

**Comment by coorasse** [comment]
Using `set_date_columns` worked great. Still I think there should be no difference between

    PunchCardPoint.where(remainder_until_at: Date.today.to_time).count

and

    PunchCardPoint.find_by_sql(PunchCardPoint.where(remainder_until_at: Date.today.to_time).to_sql).count

I leave it to you if you want o close the issue or not. Thanks btw for the suggestion!

**Comment by rsim** [comment]
The difference was that `PunchCardPoint.where(remainder_until_at: Date.today.to_time)` generated SQL with bind variable :a1
`SELECT COUNT(*) FROM "PUNCH_CARD_POINTS" WHERE "PUNCH_CARD_POINTS"."REMAINDER_UNTIL_AT" = :a1  [["remainder_until_at", 2015-07-20 22:00:00 UTC]]`
and it seems that then the time zone handling happened differently. But in this case you don't need to use `.to_time` method and just pass `Date.today` as it will be converted to `2015-07-21` in SQL which is what you probably want.
