### ISSUE TITLE
undefined method `type_cast_for_database'  for "INTEGER":String:

### ISSUE THREAD

**Issue by lustremedia** [rsim/oracle-enhanced#675]
I am running into following issue when calling an UPDATE statement

ActiveRecord::StatementInvalid (NoMethodError: undefined method `type_cast_for_database' for "INTEGER":String: UPDATE USERS SET CHANGED=SYSDATE WHERE ID=:1)
```
col1=ActiveRecord::ConnectionAdapters::OracleEnhancedColumn.new('id', nil, 'INTEGER')
ActiveRecord::Base.connection.exec_update("UPDATE USERS SET CHANGED=SYSDATE WHERE ID=:1", 'Update Webuser Changed', [[col1,@user.id]])
```

I just switched to rails 4.2.3
Using activerecord-oracle_enhanced-adapter (1.6.2)
This is a legacy database.

I saw #486 but apparently this is a different issue.

**Comment by yahonda** [comment]
In Rails 4.2 `cast_type` is not just a string. it cannot be 'INTEGER'.

https://github.com/rails/rails/commit/98a7dde0

**Comment by lustremedia** [comment]
Would this be the right usage:

https://github.com/rsim/oracle-enhanced/blob/d22964ed051d491b128e8554720f2c681474b793/spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb#L230

**Comment by yahonda** [comment]
Please refer this commit.

**Comment by lustremedia** [comment]
Hi @yahonda 
Yes great, thanks a lot for your time. Issue resolved!

**Comment by lustremedia** [comment]
@yahonda Just a quick question:
What is the difference between ActiveRecord::Type and ActiveRecord::ConnectionAdapters::Type

Are the latter abstractions for specific ConnectionAdapters such as OracleEnhanced MySQL Postgress Adapters?

**Comment by yahonda** [comment]
It was just a name space change in Rails itself. Then ` ActiveRecord::ConnectionAdapters::Type` does not exist anymore. 

https://github.com/rails/rails/commit/728fa69839d2c3b839391f9077896c06df80bddf

The reason why I pointed out the commit using `ActiveRecord::ConnectionAdapters::Type` was it would make you clear which kind of object needs to pass to `cast_type`. Glad you have resolved your issue.
