### ISSUE TITLE
Locking can lock up entire MRI process

### ISSUE THREAD

**Issue by mperham** [rsim/oracle-enhanced#677]
http://stackoverflow.com/questions/31715275/sidekiq-stuck-threads-not-responding-to-ttin-signal
https://gist.github.com/Dharshi/ec55411d24f9fd153f01#file-gistfile1-txt-L1186

See SO question and gist.  It would appear, due to a mixture of Ruby and native mutexes, that this Oracle driver can cause MRI to lock up completely.

**Comment by mperham** [comment]
Sorry, I didn't realize how the code was split across gems.

https://github.com/kubo/ruby-oci8/issues/90

**Comment by yahonda** [comment]
No problem. Thanks.
