### ISSUE TITLE
Deprecation warning from write_lobs

### ISSUE THREAD

**Issue by walterdavis** [rsim/oracle-enhanced#687]
This line: https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb#L829 is being reported in my logs as a deprecated method. Is there a substitute available?

Over and over...
```
DEPRECATION WARNING: `serialized_attributes` is deprecated without replacement, and will be removed in Rails 5.0. (called from block in write_lobs at /home/waldavis/gems/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:829)
```

**Comment by walterdavis** [comment]
I just tried this in a branch, and while I have not tested it thoroughly, it does appear to silence the warning and still seems to work:

```
value = value.to_yaml if col.cast_type.is_a?(Type::Serialized)
```

**Comment by yahonda** [comment]
Thanks for reporting. Let me close since it is duplicate with #687. Also feel free to open a pull request.

**Comment by walterdavis** [comment]
Sorry, what is it a duplicate of? It looks like you linked to this issue (from itself).

**Comment by yahonda** [comment]
It was my typo. #548 is a correct number.
