### ISSUE TITLE
oracle_enhanced_adapter issue with apache and passenger 

### ISSUE THREAD

**Issue by Jrsnow8921** [rsim/oracle-enhanced#706]
I have this app I am using and need to have the ability to connect to an oracle datatbase and a sqlserver database. Since upgrading this app on my server I keep getting this error in my apache error.log. Any help will be greatly appreciated!!!

    App 28881 stdout:
    App 28881 stdout:
    [ 2015-09-04 10:00:45.6148 28805/7f1b538a4700 App/Implementation.cpp:287 ]: Could not spawn process for application /home/rails/apps/Employee-      Time-Off-App: An error occured while starting up the preloader.
    Error ID: 1ebaec70
    Error details saved to: /tmp/passenger-error-rlN16f.html
    Message from application: ERROR: 'cannot load such file -- oci8lib_210'. ActiveRecord oracle_enhanced adapter could not load ruby-oci8 library. You may need install ruby-oci8 gem. (LoadError)
    /usr/local/rvm/gems/ruby-1.9.3-p551/bundler/gems/oracle-enhanced-4eb68ac7acb6/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:7:in `rescue in <top (required)>'
    /usr/local/rvm/gems/ruby-1.9.3-p551/bundler/gems/oracle-enhanced-4eb68ac7acb6/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:3:in `<top (required)>'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
    /usr/local/rvm/gems/ruby-1.9.3-p551/bundler/gems/oracle-enhanced-4eb68ac7acb6/lib/active_record/connection_adapters/oracle_enhanced/connection.rb:112:in `<top (required)>'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
    /usr/local/rvm/gems/ruby-1.9.3-p551/bundler/gems/oracle-enhanced-4eb68ac7acb6/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:33:in `<top (required)>'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
    /usr/local/rvm/gems/ruby-1.9.3-p551/bundler/gems/oracle-enhanced-4eb68ac7acb6/lib/activerecord-oracle_enhanced-adapter.rb:12:in `block in   <class:OracleEnhancedRailtie>'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.4/lib /active_support/lazy_load_hooks.rb:38:in `instance_eval'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:44:in `each'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.4/lib/active_record/base.rb:315:in `<module:ActiveRecord>'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.4/lib/active_record/base.rb:26:in `<top (required)>'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/audited-activerecord-4.0.0/lib/audited/adapters/active_record/audit.rb:18:in `<module:ActiveRecord>'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/audited-activerecord-4.0.0/lib/audited/adapters/active_record/audit.rb:6:in `<module:Adapters>'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/audited-activerecord-4.0.0/lib/audited/adapters/active_record/audit.rb:5:in `<module:Audited>'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/audited-activerecord-4.0.0/lib/audited/adapters/active_record/audit.rb:4:in `<top (required)>'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/audited-activerecord-4.0.0/lib/audited/adapters/active_record.rb:3:in `require'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/audited-activerecord-4.0.0/lib/audited/adapters/active_record.rb:3:in `<top (required)>'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/audited-activerecord-4.0.0/lib/audited-activerecord.rb:2:in `require'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/audited-activerecord-4.0.0/lib/audited-activerecord.rb:2:in `<top (required)>'
    /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `require'
    /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `each'
    /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `block in require'
    /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `each'
    /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `require'
    /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler.rb:133:in `require'
    /home/rails/apps/Employee-Time-Off-App/config/application.rb:9:in `<top (required)>'
    /home/rails/apps/Employee-Time-Off-App/config/environment.rb:2:in `require'
    /home/rails/apps/Employee-Time-Off-App/config/environment.rb:2:in `<top (required)>'
    config.ru:3:in `require'
    config.ru:3:in `block in <main>'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.4/lib /rack/builder.rb:55:in `instance_eval'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.4/lib /rack/builder.rb:55:in `initialize'
    config.ru:1:in `new'
    config.ru:1:in `<main>'
    /usr/local/lib/ruby/gems/2.1.0/gems/passenger-5.0.4/helper-scripts/rack-preloader.rb:111:in `eval'
    /usr/local/lib/ruby/gems/2.1.0/gems/passenger-5.0.4/helper-scripts/rack-preloader.rb:111:in `preload_app'
    /usr/local/lib/ruby/gems/2.1.0/gems/passenger-5.0.4/helper-scripts/rack-preloader.rb:157:in `<module:App>'
    /usr/local/lib/ruby/gems/2.1.0/gems/passenger-5.0.4/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
    /usr/local/lib/ruby/gems/2.1.0/gems/passenger-5.0.4/helper-scripts/rack-preloader.rb:28:in `<main>'

    [ 2015-09-04 10:00:45.6250 28805/7f1b4d1e2700 age/Hel  /Req/CheckoutSession.cpp:252 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 1ebaec70. Please see earlier logs for details about the error.

Here is my Gemfile 

    source 'https://rubygems.org'

    gem 'rails', '4.2.4'
    gem 'jquery-rails' 
    gem 'jbuilder', '~> 2.0'
    gem 'jquery-scrollto-rails'
    gem 'jquery-ui-sass-rails'
    gem 'simple_form'
    gem 'jquery-timepicker-rails'
    gem 'best_in_place'
    gem 'airbrake'
    gem 'thin'
    gem 'fullcalendar-rails'
    gem "font-awesome-rails"
    gem 'jquery-ui-rails'

    #database
    gem 'ruby-oci8', '2.1.7'
    #gem 'activerecord-oracle_enhanced-adapter', '~> 1.6.0'
    gem "activerecord-oracle_enhanced-adapter", git: 'https://github.com/rsim/oracle-enhanced.git', branch: 'rails42'
    gem 'audited-activerecord', '~> 4.0.0.rc1'

    #when using sqlserver make sure rails version is 4.2 and higher
    gem 'tiny_tds'
    gem 'activerecord-sqlserver-adapter', '~> 4.2.0'

    gem 'nested_form'
    gem 'composite_primary_keys'
    gem 'protected_attributes'
    gem 'capistrano'
    gem 'html2haml'
    gem 'rvm-capistrano', :require => false
    gem 'whenever', :require => false
    gem 'net-ssh', '~> 2.6.8'
    gem 'htmlentities'
    gem 'kaminari'

    gem 'json', '1.8.1'
    gem 'sweetalert-rails'

    # Authentication/Authorization
    gem 'devise'
    gem 'cancan'

    gem 'sass-rails'
    gem 'bootstrap-sass'
    gem 'coffee-rails'
    gem 'therubyracer', platforms: :ruby
    gem 'uglifier', '>= 1.3.0'

    # Angular stuff
    gem 'angularjs-rails'
    gem 'ng-rails-csrf'
    gem 'angular-rails-templates'
    gem 'angular-ui-bootstrap-rails'

    # Metrics  --Need Istanbul node package installed for JS coverage reporting to work
    gem 'simplecov'

    # Keep your server logs clean
    gem 'quiet_assets'
    gem 'webrick'

    # Heroku configs  --Comment these out if deploying somewhere else
    #ruby '2.1.2'
    #gem 'rails_12factor'

#Output of Bundle install is successful 

    ra@Rails-Server:~/apps/Employee-Time-Off-App$ bundle install 
    Resolving dependencies...
    Using rake 10.4.2
    Using i18n 0.7.0
    Using json 1.8.1
    Using minitest 5.8.0
    Using thread_safe 0.3.5
    Using tzinfo 1.2.2
    Using activesupport 4.2.4
    Using builder 3.2.2
    Using erubis 2.7.0
    Using mini_portile 0.6.2
    Using nokogiri 1.6.6.2
    Using rails-deprecated_sanitizer 1.0.3
    Using rails-dom-testing 1.0.7
    Using loofah 2.0.3
    Using rails-html-sanitizer 1.0.2
    Using actionview 4.2.4
    Using rack 1.6.4
    Using rack-test 0.6.3
    Using actionpack 4.2.4
    Using globalid 0.3.6
    Using activejob 4.2.4
    Using mime-types 2.6.1
    Using mail 2.6.3
    Using actionmailer 4.2.4
    Using activemodel 4.2.4
    Using arel 6.0.3
    Using activerecord 4.2.4
    Using activerecord-oracle_enhanced-adapter 1.5.6 from https://github.com/rsim/oracle-enhanced.git (at rails42)  
    Using activerecord-sqlserver-adapter 4.2.4
    Using multi_json 1.11.2
    Using airbrake 4.3.1
    Using thor 0.19.1
    Using railties 4.2.4
    Using hike 1.2.3
    Using tilt 1.4.1
    Using sprockets 2.12.4
    Using angular-rails-templates 0.1.5
    Using angular-ui-bootstrap-rails 0.13.3
    Using angularjs-rails 1.4.4
    Using execjs 2.6.0
    Using autoprefixer-rails 5.2.1.3
    Using bcrypt 3.1.10
    Using best_in_place 3.0.3
    Using debug_inspector 0.0.2
    Using binding_of_caller 0.7.2
    Using sass 3.4.18
    Using bootstrap-sass 3.3.5.1
    Using bundler 1.7.6
    Using cancan 1.6.10
    Using highline 1.7.3
    Using net-ssh 2.6.8
    Using net-scp 1.2.1
    Using net-sftp 2.1.2
    Using net-ssh-gateway 1.2.0
    Using capistrano 2.15.6
    Using chronic 0.10.2
    Using coffee-script-source 1.9.1.1
    Using coffee-script 2.4.1
    Using coffee-rails 4.1.0
    Using composite_primary_keys 8.1.1
    Using daemons 1.2.3
    Using orm_adapter 0.5.0
    Using responders 2.1.0
    Using warden 1.2.3
    Using devise 3.5.2
    Using docile 1.1.5  
    Using eventmachine 1.0.8
    Using font-awesome-rails 4.4.0.0
    Using jquery-rails 4.0.5
    Using momentjs-rails 2.10.3
    Using fullcalendar-rails 2.3.1.0
    Using haml 4.0.7
    Using sexp_processor 4.6.0
    Using ruby_parser 3.7.1 
    Using html2haml 2.0.0
    Using htmlentities 4.3.4
    Using jbuilder 2.3.1
    Using jquery-scrollto-rails 1.4.3
    Using jquery-timepicker-rails 1.4.3
    Using jquery-ui-rails 4.0.3
    Using jquery-ui-sass-rails 4.0.3.0
    Using kaminari 0.16.3
    Using libv8 3.16.14.11
    Using nested_form 0.3.2
    Using ng-rails-csrf 0.1.0
    Using protected_attributes 1.1.3
    Using quiet_assets 1.1.0
    Using sprockets-rails 2.3.2
    Using rails 4.2.4
    Using redcarpet 2.2.2
    Using ref 2.0.0
    Using ruby-oci8 2.1.7  
    Using rvm-capistrano 1.5.6
    Using sass-rails 5.0.4
    Using simple_form 3.1.1
    Using simplecov-html 0.10.0
    Using simplecov 0.10.0
    Using sweetalert-rails 0.5.0
    Using therubyracer 0.12.2  
    Using thin 1.6.3
    Using tiny_tds 0.7.0
    Using uglifier 2.7.2
    Using webrick 1.3.1
    Using whenever 0.9.4
    Using yard 0.7.5
    Using yard-rails 0.3.0
    Updating files in vendor/cache
    Your bundle is complete!
    Use `bundle show [gemname]` to see where a bundled gem is installed.

**Comment by yahonda** [comment]
`rails42` is a development branch to work with Rails 4.2 support, which is not for production use.

Remove this entry from your Gemfile
```ruby
gem "activerecord-oracle_enhanced-adapter", git: 'https://github.com/rsim/oracle-enhanced.git', branch: 'rails42'
```
And add this line
```ruby
gem 'activerecord-oracle_enhanced-adapter', '~> 1.6.0'
```
Would you try and update if it works or not.

**Comment by Jrsnow8921** [comment]
@yahonda 

Thanks for the response unfortunatly I am still getting the same issue..

   [ 2015-09-04 14:00:30.7768 1847/7fab0cc5c700 App/Implementation.cpp:287 ]: Could not spawn process for application /home/rails/apps/Employee-Time-Off-App: An error occ$
    Error ID: 54bab37f
    Error details saved to: /tmp/passenger-error-iwdTHQ.html
  Message from application: ERROR: 'cannot load such file -- oci8lib_210'. ActiveRecord oracle_enhanced adapter could not load ruby-oci8 library. You may need install $
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-oracle_enhanced-adapter-1.6.3/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:7:in `res$


ra@Rails-Server:~/apps/Employee-Time-Off-App$ bundle install 
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.1
Using minitest 5.8.0
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.4
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.7
Using loofah 2.0.3
Using rails-html-sanitizer 1.0.2
Using actionview 4.2.4
Using rack 1.6.4
Using rack-test 0.6.3
Using actionpack 4.2.4
Using globalid 0.3.6
Using activejob 4.2.4
Using mime-types 2.6.1
Using mail 2.6.3
Using actionmailer 4.2.4
Using activemodel 4.2.4
Using arel 6.0.3
Using activerecord 4.2.4
Using activerecord-oracle_enhanced-adapter 1.6.0 
Using activerecord-sqlserver-adapter 4.2.4
Using multi_json 1.11.2
Using airbrake 4.3.1
Using thor 0.19.1
Using railties 4.2.4
Using hike 1.2.3
Using tilt 1.4.1
Using sprockets 2.12.4
Using angular-rails-templates 0.1.5
Using angular-ui-bootstrap-rails 0.13.3
Using angularjs-rails 1.4.4
Using execjs 2.6.0
Using autoprefixer-rails 5.2.1.3
Using bcrypt 3.1.10
Using best_in_place 3.0.3
Using debug_inspector 0.0.2
Using binding_of_caller 0.7.2
Using sass 3.4.18
Using bootstrap-sass 3.3.5.1
Using bundler 1.7.6
Using cancan 1.6.10
Using highline 1.7.3
Using net-ssh 2.6.8
Using net-scp 1.2.1
Using net-sftp 2.1.2
Using net-ssh-gateway 1.2.0
Using capistrano 2.15.6
Using chronic 0.10.2
Using coffee-script-source 1.9.1.1
Using coffee-script 2.4.1
Using coffee-rails 4.1.0
Using composite_primary_keys 8.1.1
Using daemons 1.2.3
Using orm_adapter 0.5.0
Using responders 2.1.0
Using warden 1.2.3
Using devise 3.5.2
Using docile 1.1.5  
Using eventmachine 1.0.8
Using font-awesome-rails 4.4.0.0
Using jquery-rails 4.0.5
Using momentjs-rails 2.10.3
Using fullcalendar-rails 2.3.1.0
Using haml 4.0.7
Using sexp_processor 4.6.0
Using ruby_parser 3.7.1 
Using html2haml 2.0.0
Using htmlentities 4.3.4
Using jbuilder 2.3.1
Using jquery-scrollto-rails 1.4.3
Using jquery-timepicker-rails 1.4.3
Using jquery-ui-rails 4.0.3
Using jquery-ui-sass-rails 4.0.3.0
Using kaminari 0.16.3
Using libv8 3.16.14.11
Using nested_form 0.3.2
Using ng-rails-csrf 0.1.0
Using protected_attributes 1.1.3
Using quiet_assets 1.1.0
Using sprockets-rails 2.3.2
Using rails 4.2.4
Using redcarpet 2.2.2
Using ref 2.0.0
Using ruby-oci8 2.1.7  
Using rvm-capistrano 1.5.6
Using sass-rails 5.0.4
Using simple_form 3.1.1
Using simplecov-html 0.10.0
Using simplecov 0.10.0
Using sweetalert-rails 0.5.0
Using therubyracer 0.12.2  
Using thin 1.6.3
Using tiny_tds 0.7.0
Using uglifier 2.7.2
Using webrick 1.3.1
Using whenever 0.9.4
Using yard 0.7.5
Using yard-rails 0.3.0
Updating files in vendor/cache
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.

**Comment by yahonda** [comment]
My last update needs update to use the latest version of Oracle enhanced adapter 1.6.3.

```ruby
gem 'activerecord-oracle_enhanced-adapter', '~> 1.6'
```

Give it a try and update the result.
