### ISSUE TITLE
Number precision and average

### ISSUE THREAD

**Issue by wagurano** [rsim/oracle-enhanced#732]
I don't know how to use activerecord aggregation methods(average, count ...).
I expected average result type is real number(float, double ...), but result type is BigDecimal.
How can I fix my code?
Here is my simplified code:

----------

environments
===
 * jruby 9.0.0.0.pre1 (2.2.0p0) 2015-01-20 d537cab Java HotSpot(TM) Client VM 24.79
-b02 on 1.7.0_79-b15 +jit [Windows 7-x86]
 * rails 4.2.3
 * activerecord-jdbc-adapter (1.3.18)
 * activerecord-oracle_enhanced-adapter (1.6.3)
 * oracle 10g

table name: data
===

| colunm | type |
|---|---|
| item | CHAR(5 BYTE) |
| base_time | CHAR(10 BYTE) |
| value | NUMBER(15,5) |

app/model/xxx_data.rb
====
````ruby
    class XxxData  < ActiveRecord::Base
        self.table_name = "xxx_yyydata"
        def self.test
          where(base_time: '2012030100'..'2012033123', item: 'XXXYY').average(:value)
        end
    end
````

Test
=====
$ rails c
```ruby
    Xxxdata.test
    => #<BigDecimal:c56cbd,'8.0',1(4)>  # exptected 8.4
```

**Comment by yahonda** [comment]
Would you update your testcase i.e. such as which value inserted to `value` column.

**Comment by yahonda** [comment]
Closing this since no feedback available.
