### ISSUE TITLE
Structure dump is invalid 

### ISSUE THREAD

**Issue by scottschulthess** [rsim/oracle-enhanced#735]
```

CREATE TABLE "USERS" (
"USER_ID" NUMBER,
 CONSTRAINT USERS_ID_PK PRIMARY KEY (USER_ID)
)

/

CREATE UNIQUE INDEX "USERS_ID_PK" ON "USERS" ("USER_ID")
```

This generates an error
```Java::JavaSql::SQLSyntaxErrorException: ORA-00955: name is already used by an existing object```

This is because adding the primary key constraint automatically creates the index of the same name. 

Any suggestions on how to resolve this?

**Comment by scottschulthess** [comment]
I ran structure dump again and it went away.  Not sure exactly whats going on here.  Will investigate

**Comment by yahonda** [comment]
Closing this since no updates so far, please reopen with some more information if it still reproduces.
