### ISSUE TITLE
Rails 4.2.x gives ORA-01008: not all variables bound

### ISSUE THREAD

**Issue by claptimes5** [rsim/oracle-enhanced#753]
I have a project running on 4.1.14 and when upgrading to 4.2.5, I receive this error. Looking at the SQL, there is indeed a missing bind variable. 

`ActiveRecord::StatementInvalid: OCIError: ORA-01008: not all variables bound`

I've written a test that recreates the structure and relationship of my models and gives the same error:

https://github.com/claptimes5/oracle-enhanced/blob/not-all-variables-bound-error/spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb#L902

Let me know If I can provide any more information.

Thanks!

**Comment by yahonda** [comment]
- Rails `4-1-stable` branch and Oracle enhanced adapter `release14` branch cherry-pick 
```sql
SELECT *
FROM
  (SELECT "TEST_EMPLOYEES".*
   FROM "TEST_EMPLOYEES"
   INNER JOIN "TEST_RELATED_EMPLOYEES" ON "TEST_EMPLOYEES"."ID" = "TEST_RELATED_EMPLOYEES"."RELATED_EMPLOYEE_ID"
   INNER JOIN "TEST_EMPLOYEES" "EMPLOYEES_SUBORDINATES_JOIN" ON "TEST_RELATED_EMPLOYEES"."EMPLOYEE_ID" = "EMPLOYEES_SUBORDINATES_JOIN"."ID"
   INNER JOIN "TEST_EMPLOYEE_ROLES" ON "EMPLOYEES_SUBORDINATES_JOIN"."ID" = "TEST_EMPLOYEE_ROLES"."EMPLOYEE_ID"
   WHERE "TEST_RELATED_EMPLOYEES"."ENABLED_P" = 't'
     AND "TEST_EMPLOYEES"."ENABLED_P" = 't'
     AND "TEST_EMPLOYEE_ROLES"."ENABLED_P" = 't'
     AND "TEST_EMPLOYEE_ROLES"."ROLE_ID" = :a1
   ORDER BY "TEST_EMPLOYEES"."ID" ASC)
WHERE ROWNUM <= 1
```
- Bind value(s)
```ruby
[["role_id", "1.0"]]
```

- Rails `4-2-stable` and Oracle enhanced adapter `release14` branch 

```sql
SELECT *
FROM
  (SELECT "TEST_EMPLOYEES".*
   FROM "TEST_EMPLOYEES"
   INNER JOIN "TEST_RELATED_EMPLOYEES" ON "TEST_EMPLOYEES"."ID" = "TEST_RELATED_EMPLOYEES"."RELATED_EMPLOYEE_ID"
   INNER JOIN "TEST_EMPLOYEES" "EMPLOYEES_SUBORDINATES_JOIN" ON "TEST_RELATED_EMPLOYEES"."EMPLOYEE_ID" = "EMPLOYEES_SUBORDINATES_JOIN"."ID"
   INNER JOIN "TEST_EMPLOYEE_ROLES" ON "EMPLOYEES_SUBORDINATES_JOIN"."ID" = "TEST_EMPLOYEE_ROLES"."EMPLOYEE_ID"
   WHERE "TEST_RELATED_EMPLOYEES"."ENABLED_P" = :a1
     AND "TEST_EMPLOYEES"."ENABLED_P" = :a2
     AND "TEST_EMPLOYEE_ROLES"."ENABLED_P" = :a3
     AND "TEST_EMPLOYEE_ROLES"."ROLE_ID" = :a4
   ORDER BY "TEST_EMPLOYEES"."ID" ASC)
WHERE ROWNUM <= 1
```
- Bind values
```ruby
[["enabled_p", "t"], ["enabled_p", "t"], ["role_id", "1.0"]]
```

**Comment by yahonda** [comment]
Looks like one of bind values :a1, :a2 or :a3 is missing related with default scope.

**Comment by yahonda** [comment]
Would you try to create a testcase using sqlite3 to see if this is Oracle enhanced adapter related or Rails itself? https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb

**Comment by claptimes5** [comment]
Looks like it's an AR issue. Thanks for investigating!

https://github.com/rails/rails/issues/22723

**Comment by yahonda** [comment]
good catch. It looks like duplicate.
