### ISSUE TITLE
Blocking I/O

### ISSUE THREAD

**Issue by westlakem** [rsim/oracle-enhanced#763]
Is it possible to implement a non-blocking I/O version of this gem?

Proof of blocking

ActiveRecord::Base.estabilsh_connection(my_db)
start_time = Time.now

begin
   Timeout::timeout(0.01){
      Users.all.map {|e| e}  #map needed so sql statement will actually run
   }
rescue Timeout::Error
  puts "sql took: #{start_time - Time.now} seconds"
end
###### #######console output

sql took: 4.82 seconds

**Comment by yahonda** [comment]
If you use ruby-oci8 and CRuby, set `:allow_concurrency` to true in your database.yml then `non_blocking` becomes true at oci8 layer.

https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb#L314

https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb#L335

Actually I'm not familiar with non-blocking i/o implementations, please test at your own environment.

**Comment by westlakem** [comment]
@yahonda I'm on a JRUBY implementation, and not ruby-oci8/CRuby

**Comment by kubo** [comment]
FYI.

CRuby:
`non_blocking` in ruby-oci8 is enabled by default if the ruby version is 1.9 or upper.

JRuby:
As far as I checked jruby source code, [RubyThread.executeTask](https://github.com/jruby/jruby/blob/4dee7b1c98003c8a0761d7d3ca4c823d9b09c323/core/src/main/java/org/jruby/RubyThread.java#L1345) should be used to cancel jruby method calls. IMO, SQL statement executions can be cancelled by implementing [Task.wakeup](https://github.com/jruby/jruby/blob/4dee7b1c98003c8a0761d7d3ca4c823d9b09c323/core/src/main/java/org/jruby/RubyThread.java#L1267) which calls [Statement.cancel](https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#cancel%28%29). However I could not find any code using `executeTask` outside of jruby itself.

**Comment by westlakem** [comment]
@kubo Do you have any ideas how to implement this?

**Comment by kubo** [comment]
@westlakem 
I tries but failed to implement [Task](https://github.com/jruby/jruby/blob/4dee7b1c98003c8a0761d7d3ca4c823d9b09c323/core/src/main/java/org/jruby/RubyThread.java#L1265). However I could use deprecated [BlockingTask](https://github.com/jruby/jruby/blob/4dee7b1c98003c8a0761d7d3ca4c823d9b09c323/core/src/main/java/org/jruby/RubyThread.java#L1256) and [RubyThread.executeBlockingTask](https://github.com/jruby/jruby/blob/4dee7b1c98003c8a0761d7d3ca4c823d9b09c323/core/src/main/java/org/jruby/RubyThread.java#L1332).

The following code may work instead of `result = stmt.execute`.
```ruby
class StatementExecuteTask
  include org.jruby.RubyThread::BlockingTask
  def initialize(stmt)
    @stmt = stmt
  end
  def run
    @result = @stmt.execute
  end
  def wakeup
    @stmt.cancel
  end
  def result
    @result
  end
end

task = StatementExecuteTask.new(stmt)
JRuby.reference(JRuby.runtime.getCurrentContext.getThread).executeBlockingTask(task)
result = task.result
```

Here is test code to check whether `cancel` is called.
```ruby
require 'timeout'

class DummyStmt
  def execute
    puts 'call `execute`'
    sleep(10)
  end
  def cancel
    puts 'call `cancel`'
  end
end
stmt = DummyStmt.new

class JDBCExecuteTask
  include org.jruby.RubyThread::BlockingTask
  def initialize(stmt)
    @stmt = stmt
  end
  def run
    @stmt.execute
  end
  def wakeup
    @stmt.cancel
  end
end

start_time = Time.now
begin
  Timeout::timeout(2) do
    task = JDBCExecuteTask.new(stmt)
    JRuby.reference(JRuby.runtime.getCurrentContext.getThread).executeBlockingTask(task)
  end
rescue Timeout::Error
  puts "sql took: #{Time.now - start_time} seconds"
end
```
result:
```
call `execute`
call `cancel`
sql took: 2.009 seconds
```

I hope that the deprecated `BlockingTask` won't be deleted in future.

**Comment by kubo** [comment]
I found a bit simple way.

Use
```ruby
JRuby.reference(Thread.current).executeBlockingTask(task)
```
instead of
```ruby
JRuby.reference(JRuby.runtime.getCurrentContext.getThread).executeBlockingTask(task)
```

**Comment by kubo** [comment]
@westlakem
Timeout doesn't work in the following case.
* The Oracle server is running on Windows.

  As far as I tested with [OCIBreak](https://docs.oracle.com/database/121/LNOCI/oci17msc007.htm#LNOCI17285), executions on Unix can be cancelled, but not on Windows. I guess that [Statement.cancel](https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#cancel%28%29) has same limitation.
  Note that it depends only on the platform where the Oracle server is running, not on the platform where a client program runs.

* A firewall blocks [OOB packets](https://en.wikipedia.org/wiki/Out-of-band_data) between the Oracle client and server.

  You need to add [DISABLE_OOB=on](http://www.orafaq.com/wiki/SQL*Net_FAQ#What_are_inband_and_out_of_band_breaks.3F) in `sqlnet.ora` for workaround.

**Comment by kubo** [comment]
There are demerits in the case of ruby-oci8 and CRuby.
https://github.com/kubo/ruby-oci8/issues/86#issuecomment-186575856

JDBC and JRuby may have some demerits by using `Statement.cancel`.

**Comment by yahonda** [comment]
@kubo If you have a support contract with Oracle, would you refer "OCIBreak does not break calls to DBMS_LOCK.SLEEP (Doc ID 856709.1)" wince on Windows platform, `OCIBreak` does not work as expected for the session running dbms_lock.sleep.

```
On Window platforms, OCIBreak becomes effective when the socket is explicitly checked for break packets.  This only happens during the period when a
session thread is given CPU time. 

With the DBMS_LOCK.SLEEP package, the sleep means that the session thread is not given any CPU time.  Hence no check is made for break packets.
```

**Comment by westlakem** [comment]
@kubo @yahonda Was anyone able to reach out and get any answers?

**Comment by westlakem** [comment]
@kubo @yahonda 

I have found a solution that works, but I am unsure the best way to pass the value down to the jdbc_connection.  Ultimately we need to modify `exec` in  `activerecord-oracle_enhanced-adapter-1.6.4\lib\active_record\connection_adapters\oracle_enhanced\jdbc_connection.rb` (line 371).

Current method

        def exec
          @raw_result_set = @raw_statement.executeQuery
          true
        end

Needs to be

        def exec
          @raw_statement.setQueryTimeout(TIMEOUT_VALUE) #this is the new line
          @raw_result_set = @raw_statement.executeQuery
          true
        end
