### ISSUE TITLE
Ignores self.sequence_name during test execution

### ISSUE THREAD

**Issue by jesmith17** [rsim/oracle-enhanced#773]
I am getting the following error when trying to execute tests against my app. 

Specific error is this. 

``` bash
MerchantTest#test_should_not_save_merchant_empty:
ActiveRecord::StatementInvalid: OCIError: ORA-02289: sequence does not exist: DROP SEQUENCE "CH_INVOICE_SEQ"
```

To re-create

Create oracle table and sequence that does not match the standard Ruby names.  (Requires overriding via the adapters self.xxxxx options
``` SQL

create table ch_merchant (
merchant_id number(11,0) NOT NULL,
merchant_name varchar(2) );

create sequence CH_MERCHANT_ID_SQ;

create table ch_invoice (
invoice_id number(11,0) NOT NULL,
merchant_id number(11,0) NOT NULL);

create sequence CH_INVOICE_ID_SQ;


```
Create corresponding model for the table
``` bash
rails s scaffold merchant merchant_name
rails s scaffold invoice merchant:belongs_to

```

Update your resulting merchant model to have
``` ruby
self.table_name = 'ch_merchant'
self.sequence_name = 'ch_merchant_id_sq'
```
Then update those models 

``` ruby


update your structure.sql file so that it's accurate

``` bash
rake db:structure:dump
```

Create a test against that model object and execute. 

``` ruby

require 'test_helper'

class MerchantTest < ActiveSupport::TestCase
  # test "the truth" do
  #   assert true
  # end

  test 'should not save merchant empty' do
    merchant = Merchant.new
    assert_not merchant.save
  end

end

```

Notice that the sequence it can't find matches the standard naming scheme for oracle sequences.
Also notice that it's not the sequence tied to the model under test.

**Comment by yahonda** [comment]
Please keep working at #767.
