### ISSUE TITLE
uninitialized constant ActiveRecord::ConnectionAdapters::ForeignKeyDefinition

### ISSUE THREAD

**Issue by zouis** [rsim/oracle-enhanced#780]
Hello!
I've just installed activerecord-oracle_enhanced-adapter and I got the following error:
uninitialized constant ActiveRecord::ConnectionAdapters::ForeignKeyDefinition

My gemfile looks like this : 
...
gem 'activerecord-oracle_enhanced-adapter', '~> 1.6.0'
gem 'ruby-oci8', '~> 2.1.0'
...

Environment:
rails 4.2, webrick, windows7

**Comment by yahonda** [comment]
Would you execute `bundle show` and provide actual gem list installed in your environment.

**Comment by zouis** [comment]
Hi Yahonda!
here are the gems I use:
Gems included by the bundle:
  * actionmailer (4.1.8)
  * actionpack (4.1.8)
  * actionview (4.1.8)
  * activemodel (4.1.8)
  * activerecord (4.1.8)
  * activerecord-oracle_enhanced-adapter (1.6.6)
  * activesupport (4.1.8)
  * akami (1.3.1)
  * arel (5.0.1.20140414130214)
  * builder (3.2.2)
  * bundler (1.11.2)
  * coffee-rails (4.0.1)
  * coffee-script (2.4.1)
  * coffee-script-source (1.8.0)
  * erubis (2.7.0)
  * execjs (2.6.0)
  * gyoku (1.3.1)
  * hike (1.2.3)
  * httpi (2.4.1)
  * i18n (0.7.0)
  * jbuilder (2.4.1)
  * jquery-rails (3.1.4)
  * json (1.8.3)
  * mail (2.6.3)
  * mime-types (2.99)
  * mini_portile2 (2.0.0)
  * minitest (5.8.4)
  * multi_json (1.11.2)
  * nokogiri (1.6.7.2)
  * nori (2.6.0)
  * rack (1.5.5)
  * rack-test (0.6.3)
  * rails (4.1.8)
  * railties (4.1.8)
  * rake (10.5.0)
  * rdoc (4.2.2)
  * ruby-oci8 (2.1.8)
  * sass (3.2.19)
  * sass-rails (4.0.5)
  * savon (2.11.1)
  * sdoc (0.4.1)
  * sprockets (2.12.4)
  * sprockets-rails (2.3.3)
  * sqlite3 (1.3.11)
  * thor (0.19.1)
  * thread_safe (0.3.5)
  * tilt (1.4.1)
  * turbolinks (2.5.3)
  * tzinfo (1.2.2)
  * tzinfo-data (1.2016.1)
  * uglifier (2.7.2)
  * wasabi (3.5.0)

**Comment by yahonda** [comment]
It shows that this application configured to use Rails 4.1.8, not 4.2.x.  Please update your Gemfile to use Rails 4.2.x or use Oracle enhanced adapter 1.5.x which supports Rails 4.1.
```ruby
activerecord (4.1.8)
```

**Comment by zouis** [comment]
My fault, railsinstaller is saying 4.2.
thanks Yahonda.
PS: the time exec of a query is 2.5 times more than Taod !
