### ISSUE TITLE
NLS_Language Setting: UTF8 Problem

### ISSUE THREAD

**Issue by macabolic** [rsim/oracle-enhanced#792]
I have problem writing UTF8 character to the oracle database. We are using 12c now.
What settings do we need to set in database.yml?

In mysql, we use  "encoding: utf8" in database.yml. How about Oracle?

**Comment by yahonda** [comment]
Would you explain your problem and update these information.

* Ruby version, using CRuby or JRuby
* If you use JRuby please update which jdbc driver you are using `OCI` or `THIN`
* Output of this query at your database
```sql

SQL> select PARAMETER, VALUE  from v$nls_parameters
  2   where PARAMETER = 'NLS_CHARACTERSET'
  3  ;

PARAMETER
----------------------------------------------------------------
VALUE
----------------------------------------------------------------
NLS_CHARACTERSET
AL32UTF8


SQL>
```

**Comment by macabolic** [comment]
Here is the information. When we are trying to do a update with UTF8 characters, here is the error.

E, [2016-03-18T13:18:06.592451 #26919] ERROR -- : Encoding::UndefinedConversionError: U+5DE5 from UTF-8 to US-ASCII: UPDATE "BANKS" SET "NAME" = :a1, "UPDATED_AT" = :a2 WHERE "BANKS"."ID" = :a3
I, [2016-03-18T13:18:06.593446 #26919]  INFO -- : U+5DE5 from UTF-8 to US-ASCII

ruby 2.2.1

SQL> select PARAMETER, VALUE from v$nls_parameters where PARAMETER = 'NLS_CHARACTERSET';

PARAMETER
----------------------------------------------------------------
VALUE
----------------------------------------------------------------
NLS_CHARACTERSET
AL32UTF8

**Comment by yahonda** [comment]
Thanks for the update. I have added some markdown tags to format them.

Would you show `NLS_LANG` environment variable configured correctly, like this.
```
NLS_LANG=American_America.AL32UTF8
```
If you have already configured NLS_LANG correctly,  There is no more configuration done at Oracle database adapter point of view.

**Comment by yahonda** [comment]
Closing since no updates available.
