### ISSUE TITLE
ActiveRecord not updating with oracle-enhanced

### ISSUE THREAD

**Issue by lreisoliveira** [rsim/oracle-enhanced#825]
This is my problem. This code

`
p = People.find_by(id: 123456)  
p.name = 'Mr Goiaba'  
p.save
`

return true to p.save but the field in the table don't is changed when I use gem 'activerecord-oracle_enhanced-adapter', '~> 1.6.0'  but... if I use mysql its Ok. In mysql works but oracle no, the same code.

ruby -v 2.3.1
rails -v 4.2.3

How to resolve?

**Comment by sockmonk** [comment]
Some more details about how you're testing would help.
Are you executing the code from the Rails console? In the Rails app itself?
Is there an implicit transaction?
Does the Rails development.log show that the UPDATE was successful and was committed?
How are you examining the oracle table for the change?
Do you have both a mysql and oracle database set up within the same rails application or different apps?

Just as an aside, by convention ActiveRecord classes are singular, while the tablename's are plural, unless you override the defaults. The model name 'People' is slightly surprising; I would have expected it to be 'Person'.

**Comment by lreisoliveira** [comment]
Thanks sockmonk for your response

I solved the problem using update_columns

       p = People.find_by(id: 123456) 
       p.update_columns(name: 'Mr Goiaba') 
       p.save 

- There is no other transaction, its a simple update
- The problem happens environment production, develop and Rails console.
- Oracle and Mysql server are in differents machines and the app is the same I just change the appointment database in database.yml


Well, I do not know what the exact problem but decided using the above solution
