### ISSUE TITLE
Escape LIKE Conditions

### ISSUE THREAD

**Issue by mits87** [rsim/oracle-enhanced#852]
Hello, 
I have problem with escape like conditions in oracle-enhanced gem.
For example I would like do something like this: 

`SELECT id FROM table WHERE name LIKE '%\_1%' ESCAPE '\' OR id LIKE '%1\_%' ESCAPE '\';`

Now it's impossible.
At this moment I override select method in initializers/oracle.rb:

```
ActiveSupport.on_load(:active_record) do
  ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter.class_eval do
    def select(sql, name = nil, binds = [])
      sql = sql.gsub(/(LIKE '[^']*')/, "\\1 ESCAPE '\\\\'") if sql['LIKE']
      super sql, name, binds
    end
  end
end
```

this works fine but it isn't perfect solution.
Can you add ESCAPE support to gem?

**Comment by remofritzsche** [comment]
Support for this would be amazing.

+1

**Comment by remofritzsche** [comment]
Is there a chance this might get addressed?

**Comment by yahonda** [comment]
There are couple of sanitizing methods defined in `ActiveRecord::Sanitization::ClassMethods`
http://api.rubyonrails.org/classes/ActiveRecord/Sanitization/ClassMethods.html#method-i-sanitize_sql_like

If these methods do not satisfy requirements, what I can say now is please consider to open a pull request to Rails or Oracle enhanced adapter.
