### ISSUE TITLE
structure_dump.rb is not working when session user is not the current_schema

### ISSUE THREAD

**Issue by khaing211** [rsim/oracle-enhanced#884]
Usecase:
Single user (dba) dump different schema

All tables start with user_ should switch to the respective all_ tables
user_sequences => all_sequences
user_tab_columns => all_tab_columns
user_cons_columns => all_cons_columns
user_constraints => all_constraints
user_views => all_views
user_object => all_objects

Also in drop_sql_for_feature() method (dynamically generate table); 

Use SQL WHERE filter owner = SYS_CONTEXT('userenv', 'current_schema') except for all_sequences, please sequence_owner column instead.

**Comment by yahonda** [comment]
Thanks for opening a issue. #713 has been merged to master which is available as Oracle enhanced adapter 1.7 with Rails 5. This is kind of new features then will not backport to Oracle enhanced adapter 1.6 or older version.
