### ISSUE TITLE
Renaming column takes a long time

### ISSUE THREAD

**Issue by negativalpha** [rsim/oracle-enhanced#932]
Recently updated the adapter (from 1.4.3 to 1.6.7) and am experiencing performance issues when migrating the database. Setting up the database takes a very long time mainly because of `rename_column` operation being very slow. Looking at the [`rename_column`](https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb#L302) implementation, the issue seems clear - the index cache is cleared and rebuilt right after every `RENAME COLUMN` statement (#286). On my non-production database this takes from 20 seconds to 12 minutes per migration (depending on how far the migration process has gone and how many objects exist in the database).

**Comment by coorasse** [comment]
+1

**Comment by coorasse** [comment]
This issue is still open. I think the problem is in the generation of the schema.rb file which takes a very long time
