### ISSUE TITLE
cpk table with lob saving fails

### ISSUE THREAD

**Issue by toddwf** [rsim/oracle-enhanced#97]
The composite_where_clause used in write_lobs in oracle_enhanced_adapter.rb:676 no longer seems to be defined.
cpk 3.1.10, activerecord-oracle_enhanced-adapter (1.3.2) 
Create a cpk table with lob column.
Create instance.
Save and get:
NoMethodError: undefined method `composite_where_clause' for #Class:0xa384924

Grepping cpk seems to show def for where_cpk_id(id) method on relation.rb, but it is not defined in the klass object in the write_lob method, despite the class being a cpk class (and the is_with_cpk value being true)

Candidate test fails in my code, but haven't forked and tried in oracle-enhanced. project.  Looking at your cpk lob tests in oracle_enhanced_cpk_spec.rb, they look like they haven't been updated in awhile.   Do these tests pass for you in newer cpk versions?

I really have to get a test environment running for your code.  :)

-Todd

**Comment by PaulBabka** [comment]
An alternative solution that works is to add a "composite_where_clause" to the model in question:

Example:

  # For Oracle Enhanced - to support tables with LOBs
  def self.composite_where_clause(values)
    cwc = []
    self.primary_keys.each_with_index do |pk,index|
      if values[index].is_a?(Fixnum)
        cwc << "\"#{self.table_name.upcase}\".\"#{pk.upcase}\" = #{values[index]}"
      else
        cwc << "\"#{self.table_name.upcase}\".\"#{pk.upcase}\" = '#{values[index]}'"
      end
    end
    cwc.join(" AND ")
  end

I'm sure the gurus in the Ruby world can write it cleaner, but this works for me.
