### ISSUE TITLE
Delete statement fails with 1.7.1, Jruby 9.1.5.0, Oracle 11g Express, ojdbc6/7.jar

### ISSUE THREAD

**Issue by pandar1** [rsim/oracle-enhanced#993]
The ruby statement 

Authkey.delete_all(["created_at < ?",1.day.ago])

translates to 

DELETE FROM "AUTHKEYS" WHERE (created_at < ’2016-09-12 12:38:49.395000’)

and fails

Java::JavaSql::SQLDataException: ORA-01830: date format picture ends before converting entire input string : DELETE FROM "AUTHKEYS" WHERE (created_at < ’2016-09-12 12:38:49.395000’)

I'm using ojdbc6.jar and tried also with ojdbc7.jar, same result...

**Comment by pandar1** [comment]
the columns for the authkeys table

 ID            NUMBER(10)                      NOT NULL,
  USERNAME      VARCHAR2(4000 BYTE),
  CREATED_AT    DATE,
  UPDATED_AT    DATE,
  LOCK_VERSION  NUMBER(10),
  COMPANY_ID    NUMBER(10)                      NOT NULL,
  SERVICE_ID    NUMBER(10)                      NOT NULL,
  AUTHKEY       VARCHAR2(4000 BYTE)

**Comment by pandar1** [comment]
Before with rails 4.2.5, activerecord-oracle_enhanced-adapter 1.6.5 the statement was translated to

DELETE FROM AUTHKEYS WHERE (created_at < TO_TIMESTAMP('2016-07-27 12:12:56:614000','YYYY-MM-DD HH24:MI:SS:FF6'))

and it worked

**Comment by yahonda** [comment]
Thanks for using Oracle enhanced adapter 1.7.1. 

Would you try 1 of these two options and update how they work.

* Specify :datetime attribute to created_at
```ruby
class Authkey < ActiveRecord::Base
  attribute :created_at, :datetime
end
```
* Modify created_at to timestamp data type. Please take a backup before executing this command.
```sql
alter table authkeys modify created_at timestamp;
```
Thanks

**Comment by pandar1** [comment]
Sure, tomorrow I will try and let you know...

**Comment by pandar1** [comment]
Sorry for the delay...

Method 1 (attribute :created_at, :datetime): no change, same error
Method 2 (changing the column type): it works

**Comment by pandar1** [comment]
P.S. I also noticed that since I updated to rails 5 and oracle enhanced 1.7.1 the created_at and updated_at fields contains only the date part with the time part set to zero... it's related to rails 5.0 or a bug of oracle enhanced?

**Comment by pandar1** [comment]
Any news about a possible fix?

**Comment by pandar1** [comment]
Hello? is there anybody out there? ;)

**Comment by yahonda** [comment]
In Oracle enhanced adapter 1.6 or early version, Rails both `:datetime` and `:date` are mapped to Oracle `DATE` sql type. To make these two types differently `set_date_columns` handles if Oracle `DATE` type needs to be mapped Rails `:date` type.

Starting from Oracle enhanced adapter 1.7 Oracle `TIMESTAMP` sql type is mapped to  Rails `:datetime` type to support microsecond datetime precision. Also Oracle `DATE` type is mapped to Rails `:date` type to follow Rails ActiveRecord type mapping.

Then database `DATE` type columns whose Rails type are intended to be `:datetime` in Rails 4.2 or earlier are now mapped to Rails `:date` type in Rails 5.

It applies to Rails `:timestamps` attribute which corresponds to two `:datetime` attributes named `created_at` and `updated_at`

If your database table underlying Rails :datetime attributes, it needs to migrate them to Rails 5 `:datetime`

```ruby
change_column :posts, :created_at, :datetime
change_column :posts, :updated_at, :datetime
```

or execute these sql statements.

```sql
ALTER TABLE "POSTS" MODIFY "CREATED_AT" TIMESTAMP
ALTER TABLE "POSTS" MODIFY "UPDATED_AT" TIMESTAMP
```

I'm going to open a pull request to add UPGRADE section to inform this behavior.

**Comment by pandar1** [comment]
Many thanks for the information.

**Comment by yahonda** [comment]
Closing this since the document for upgrade #1009 has been merged to master.  Thanks for reporting and testing.
