### ISSUE TITLE
Table and column names all in caps?

### ISSUE THREAD

**Issue by bpatram** [rsim/oracle-enhanced#997]
Hi, Im running the latest version of this gem and have it all configured correctly to an Oracle DB XE instance. When I run my migrations all table and column names are in full CAPS. Is there a setting or better way to define my migrations to prevent this?

Here is an excerpt from my `schema.rb` file which clearly shows tables and columns in lower case:
```ruby
create_table "org_types", force: :cascade do |t|
  t.string "name"
  t.string "description"
end
```

This ends up creating and running the following query: 
```sql
CREATE TABLE "ORG_TYPES" ("ID" NUMBER(38) NOT NULL PRIMARY KEY, "NAME" VARCHAR2(255), "DESCRIPTION" VARCHAR2(255)
```

**Comment by bpatram** [comment]
It seems as though all SQL statements are made in all CAPS, including creating sequence names, constraints, etc etc.

**Comment by bpatram** [comment]
It seems to be on this line:

https://github.com/rsim/oracle-enhanced/blob/6979c9fb5177ca11271ccccf33983e2051105e9e/lib/active_record/connection_adapters/oracle_enhanced/quoting.rb#L29

Where it will `upcase` the name even if it's valid

**Comment by yahonda** [comment]
Thanks for reporting. This behavior is by design since 1.3.0.

https://github.com/rsim/oracle-enhanced/blob/master/History.md

```
1.3.0 / 2010-06-21

Enhancements:
...
Table and column names are always quoted and in uppercase to avoid the need for checking Oracle reserved words
```

**Comment by bpatram** [comment]
Ah okay. How come you do this instead of just letting the database throw an error during migrations? That's what the mysql2 adapter lets happen for example.
